### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by peterbrittain** [peterbrittain/asciimatics#1]
This is a pure Python package and uses packages that already support Python 3.  How hard can it be?  :-)

**Comment by Poorchop** [comment]
Do you plan on supporting both Python 2 and 3? Doesn't look like it would be too hard to convert to Python 3, but supporting both version simultaneously could get a little cumbersome.

**Comment by peterbrittain** [comment]
Thank you.  Not having made the jump to Python 3 before now, I was thinking I'd use this project to find out about it.  If the conversion isn't too painful, I will maintain both.

**Comment by peterbrittain** [comment]
Looks like the code was pretty compatible. It is now running on v3.3 quite happily with some minor modifications.  First release supporting will be V1.1.0.  Still some tidy up left to help prevent version cross-compatibility regressions, though, so not closing just yet.

**Comment by Poorchop** [comment]
Nice. Python 3 will be standard in Fedora 22 and I'm guessing other distros will follow suit soon enough, so this was just in time.

**Comment by peterbrittain** [comment]
Yeah - it's definitely reaching the tipping point.  

Now closing this issue as I have futurized the code.  Doesn't look quite so pretty on the imports, but the rest is good to go.
