### ISSUE TITLE
Dynamic Listbox

### ISSUE THREAD

**Issue by robinsiebler** [peterbrittain/asciimatics#102]
Here is what I am trying to do:

I am writing a simple MP3 player. I have a layout with 2 columns. The 1st column has a ListBox with the playback controls and a couple of other widgets. What I would like in the 2nd column is a ListBox containing the list of songs available to play. However, I won't know what that list is until run-time, so I would like to be able to dynamically determine the number of rows and their contents.

**Comment by peterbrittain** [comment]
If I were you, I'd make your ListBox in the 2nd column fill the space available (http://asciimatics.readthedocs.io/en/latest/widgets.html#filling-the-space) and then just set the `options` property (http://asciimatics.readthedocs.io/en/latest/asciimatics.html#asciimatics.widgets.ListBox.options) once you know what the tracks are.

**Comment by robinsiebler** [comment]
Thanks! I figured it out!
