### ISSUE TITLE
Visible grouping of widgets

### ISSUE THREAD

**Issue by peterbrittain** [peterbrittain/asciimatics#104]
See https://github.com/peterbrittain/asciimatics/issues/103 for context.  This issue tracks the request to add more visual cues to the grouping of widgets.

The simplest use case is just to allow for a clear division between columns in a Layout, so that widgets in one don't touch the widgets in another - e.g. by having a vertical divider between each.

The more complex case is to provide a box around any arbitrary set of widgets.  To keep things sane on the automatic placement logic, I think this will need to be restricted to widgets in the same column, or, at the very least, in the same Layout.

**Comment by peterbrittain** [comment]
As per 117, make sure that disabled works in a sensible manner.

**Comment by peterbrittain** [comment]
No problem and thanks!

**Comment by peterbrittain** [comment]
With the vertical divider case now done, the more complex case is left.  Do you think you need that, or can I punt this into the long grass?

**Comment by garfieldnate** [comment]
The case that I needed was to set disabled on an entire group at once. Does that work now?

**Comment by peterbrittain** [comment]
No.  Nothing provides that sort of function.  I guess I could provide something like that within a Layout - e.g. a new method to disable all widgets in a column or the whole layout

**Comment by garfieldnate** [comment]
Alrighty. Maybe close this and reopen #117?

**Comment by peterbrittain** [comment]
Yeah that's probably a better trail for the missing function than this one.
