### ISSUE TITLE
Failure on GNU screen when TERM=screen

### ISSUE THREAD

**Issue by brycepg** [peterbrittain/asciimatics#105]
I've noticed that for some reason asciimatics doesn't work when the TERM environment variable is set to `screen` when using GNU screen. On one of my systems, the GNU screen default is `TERM=screen-256color`, but on others `TERM=screen`. manually changing the TERM variable to `screen-256color` fixes the issue, however I'm confused as to why this TERM value matters so much.

Anyway here's the traceback for when asciimatics fails with `TERM=screen`. This failure occurs with any code that uses asciimatics, so I used `samples/forms.py` on the master branch in this traceback:

    Traceback (most recent call last):
      File "samples/forms.py", line 147, in <module>
        Screen.wrapper(demo, catch_interrupt=False, arguments=[last_scene])
      File "/root/asciimatics/asciimatics/screen.py", line 1168, in wrapper
        func(screen, *arguments)
      File "samples/forms.py", line 142, in demo
        ], -1)], stop_on_resize=True, start_scene=scene)
      File "/root/asciimatics/asciimatics/screen.py", line 1343, in play
        scenes, unhandled_input=unhandled_input, start_scene=start_scene)
      File "/root/asciimatics/asciimatics/screen.py", line 1412, in set_scenes
        self.clear()
      File "/root/asciimatics/asciimatics/screen.py", line 1232, in clear
        self._change_colours(Screen.COLOUR_WHITE, 0, 0)
      File "/root/asciimatics/asciimatics/screen.py", line 2224, in _change_colours
        self._fg_color, colour).decode("utf-8"))
    TypeError: a bytes-like object is required, not 'NoneType'

I tried catching this exception and ignoring it for both fg and bg, however the asciimatics display just fills with a bunch of dollar sign characters instead of any meaningful text

**Comment by brycepg** [comment]
My current workaround for this issue is to programatically change the TERM variable and reset it after asciimatics is done

**Comment by peterbrittain** [comment]
I'm going to guess that your terminfo DB for `screen` has no colour support.  In particular, I bet it has no `setaf` entry.  You should be able to verify that by running `infocmp screen`.  If so you could try updating the definition.

**Comment by peterbrittain** [comment]
Ok, it looks like `screen` provides a load of options on how to tweak which terminfo definitions you use.  See https://www.gnu.org/software/screen/manual/screen.html#Termcap.  I suggest you either tweak the terminfo definition or install a new one to reflect your specific terminal running screen.

**Comment by brycepg** [comment]
For some reason I can no longer reproduce this issue. I'm not sure what changed. `setaf` is set right now.
I did find a session which had `TERM=vt100` where none of the asciimatics samples worked however the windows just froze instead of emitting an error. 

Thanks for bearing with me. If I can repro this again I'll try to figure out what awry setting caused the error.
