### ISSUE TITLE
Update PyPi?

### ISSUE THREAD

**Issue by Michal-Gagala** [peterbrittain/asciimatics#106]
Hi guys, 
so I'm going to use this for my computer science coursework, and I noticed that the git files have 'hide_char' in the Text widget, but the build on PyPi doesn't have this yet. Does anyone know when that will be updated?
Thanks for the help

**Comment by peterbrittain** [comment]
I've been thinking about refreshing PyPI, but wanted to try to sort the reduced dependencies issue first.

While you're waiting you could probably use the git install from pip. See https://stackoverflow.com/questions/8247605/configuring-so-that-pip-install-can-work-from-github

**Comment by Michal-Gagala** [comment]
The problem I have is that I don't have admin access in school where I'm going to be using it, sorry to bother you but it would be great if you could provide a wheel of the github version because I'm able to get those installed. Thanks for the quick response and I must say I really like how easy this library is, is there any list of things I could do to contribute?

**Comment by peterbrittain** [comment]
As per your other issue, I've answered the final question on how you could help...  And I think we're nearly there now on the reduced dependencies...  So hopefully not long now.

If you can't wait, you can always build the wheel yourself.  Simply run `pip install wheel`, then `python setup.py bdist_wheel` and you have the wheel ready for use in the `dist` directory.

**Comment by Eeems** [comment]
I've been attempting to install with the following command: ``pip install git+https://github.com/peterbrittain/asciimatics.git@v1.8`` or ``pip install git+https://github.com/peterbrittain/asciimatics.git@master`` and I'm getting an index out of range error.  Here is the stack trace
```
Collecting git+https://github.com/peterbrittain/asciimatics.git@master
  Cloning https://github.com/peterbrittain/asciimatics.git (to master) to /tmp/pip-HiLQv3-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-HiLQv3-build/setup.py", line 24, in <module>
        while long_description[0] != "ASCIIMATICS":
    IndexError: list index out of range

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-HiLQv3-build/
```

You get the same error when attempting to run ``python setup.py bdist_wheel``. Seems like a simple fix. I'm able to get it to build with the following change:
```diff
diff --git a/setup.py b/setup.py
index 3b42b91..ea8a611 100644
--- a/setup.py
+++ b/setup.py
@@ -21,7 +21,7 @@ here = path.abspath(path.dirname(__file__))
 # Get the long description from the relevant file and strip any pre-amble (i.e. badges) from it.
 with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
     long_description = f.read().split("\n")
-while long_description[0] != "ASCIIMATICS":
+while len(long_description) > 0 and long_description[0] != "ASCIIMATICS":
     long_description = long_description[1:]
 long_description = "\n".join(long_description)
```
That's not really fixing the real problem, but it will get it building if necessary, like @Michal-Gagala will potentially be needing.

**Comment by peterbrittain** [comment]
@Eeems I don't see those issues for either command when I run them on my machine...  What environment are you using - e.g. versions of pip, python, OS, etc.?

**Comment by Eeems** [comment]
@peterbrittain Windows 10 pro, Python 2.7, latest version of pip. I was running the build from cygwin, which may make
 a difference.

**Comment by peterbrittain** [comment]
OK...  That would be it - looks like the stuff to clean up the README doesn't work on Windows.

**Comment by Eeems** [comment]
@peterbrittain Just confirmed that it works

**Comment by peterbrittain** [comment]
v1.9.0 is now public.
