### ISSUE TITLE
Dependencies on past.translation causes PendingDeprecationWarning

### ISSUE THREAD

**Issue by jabdoa2** [peterbrittain/asciimatics#107]
We are using asciimatics in the Mission Pinball Framework (https://github.com/missionpinball/mpf/) and get a PendingDeprecationWarning on every run:

`PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses`

This is caused by asciimatics including `from past.builtins import basestring` in https://github.com/peterbrittain/asciimatics/blob/master/asciimatics/screen.py#L10.

Is is possible to remove that dependency since it clutters all our test output and confuses users?

**Comment by peterbrittain** [comment]
MPF looks really cool!  I'm glad asciimatics could help you along the way.

I'd like to help here, but this line is imported to support string detection for python 2 and python 3.  If you have a suggestion for another way to handle that, I'd be happy to try it out.  Or maybe there's something goin on in future that we could fix?  Do yo have a full stack trace for the problem?

**Comment by jabdoa2** [comment]
This is not an actual error. It just shows the warning. I added an raise AssertionError in the translation module:

```
  File "/home/jan/src/mpf/mpf/core/text_ui.py", line 7, in <module>
    from asciimatics.screen import Screen
  File "/usr/local/lib/python3.5/dist-packages/asciimatics/screen.py", line 6, in <module>
    from past.builtins import basestring
  File "/usr/local/lib/python3.5/dist-packages/past/__init__.py", line 88, in <module>
    from past.translation import install_hooks as autotranslate
  File "/usr/local/lib/python3.5/dist-packages/past/translation/__init__.py", line 2, in <module>
    raise AssertionError("")
```

Would it be possible to change this line https://github.com/peterbrittain/asciimatics/blob/master/asciimatics/screen.py#L1264:

```
        # Convert string to int if needed.
        if isinstance(char, basestring):
            char = ord(char.upper())
```
to something like this:


```
        # Convert string to int if needed.
        if not isinstance(char, int):
            char = ord(char.upper())
```

That might help to remove the dependency.

**Comment by peterbrittain** [comment]
It's a little bit permissive for my liking, but probably safe enough.  I could always do a bit of duck typing too if needed.  OK, I'll give that a try.

**Comment by peterbrittain** [comment]
Done - see https://github.com/peterbrittain/asciimatics/commit/a2e74ac727184d757d7dca5399b6da32e4eeb2ea

Still passes all the tests, so I've just left a TODO marker in there to remind me to be more rigorous when I have more time.

**Comment by jabdoa2** [comment]
Thanks!
