### ISSUE TITLE
Data is empty?

### ISSUE THREAD

**Issue by Michal-Gagala** [peterbrittain/asciimatics#108]
class NewUser(Frame):
        def __init__(self, screen, scenes, db, c):
            super().__init__(screen,
                             screen.height-2,
                             screen.width-2, 
                             has_border = True,
                             reduce_cpu=True)
            self.scenes=scenes
            self.db=db
            self.c=c
            layout=Layout([1])
            self.add_layout(layout)
            layout.add_widget( Text(label='Name:',name='name', validator='[a-zA-Z]+') )
            layout.add_widget(Text(label='Form:',name='form', validator='[0-9]+[a-zA-Z]') )
            layout.add_widget(Text(label='Password:', name='passwd1', validator=lambda x: True if len(x)>5 else False ) )
            layout.add_widget(Text(label='Confirm Password:', name='passwd2', validator=lambda x: True if len(x)>5 else False))
            layout.add_widget(Divider(draw_line=False, height=(screen.height//4)*3))
            layout.add_widget(Button('Register', self.register(self.db, self.c)))
            layout.add_widget(Label(''))
             
            self.fix()

    
        def register(self, db, c):
            print(self.data)
            self.save()
            print(self.data)
            if self.data['passwd1'] != self.data['passwd2']:
                print('why isnt this working')
                self._scene.add_effect(
                    PopUpDialog(self._screen,
                                "Are you sure?",
                                ["Yes", "No"]))
This is my class, but when the button gets pressed, even if all the widgets are filled in, the values for all the keys in the dictionary are 'None'

**Comment by peterbrittain** [comment]
Sorry, but your sample code is bugged.  You can't call self.register when constructing the Button widget.

When I fix that, it just works as expected for me.

**Comment by Michal-Gagala** [comment]
Wait so what's the proper syntax for adding the function to the button?

**Comment by Michal-Gagala** [comment]
Ok I've got it, just have to remove the brackets and arguments since dataaccess is part of self anyway it's fine.
   `layout.add_widget(Button('Register', self.register(self.db, self.c)))`
becomes
   `layout.add_widget(Button('Register', self.register))`

**Comment by peterbrittain** [comment]
Yup.  I'm assuming this is now fixed as it works for me.
