### ISSUE TITLE
What to contribute?

### ISSUE THREAD

**Issue by Michal-Gagala** [peterbrittain/asciimatics#109]
Hi, I wanted to contribute to the project but I don't know where to start, could someone recommend some easier stuff for me to work on and add to the project?

**Comment by peterbrittain** [comment]
Good question.  I've tried to stay on top of simple requests, so there's not much that's easy in the backlog of open issues.  Maybe some of the stuff in https://github.com/peterbrittain/asciimatics/issues/103

I'm sure there are also inconsistencies in which callbacks each widget provides.  Maybe there's some extra logic to be added there?  

Or maybe there's a feature you hoped would be present?  I'd be happy to help you figure out how to add that.

Failing that you could try adding a new Widget or Effect (as per the outstanding enhancements).

**Comment by Michal-Gagala** [comment]
Great! When I have some time, I'll try to add something simple like divider character selection. Thanks for the quick responses and the great module!

**Comment by peterbrittain** [comment]
You're welcome!  I'll try to maintain the list of possible work labels going forwards and so close this issue now
