### ISSUE TITLE
Prerequisites are not mentioned anywhere that I could find.

### ISSUE THREAD

**Issue by nielsene54** [peterbrittain/asciimatics#11]
Just giving you a heads up that it would be nice to know that you also need to install future, pillow and pyfiglet to get the demonstration working.

**Comment by peterbrittain** [comment]
Thanks for letting me know.

These are all explicitly listed as dependencies in setup.py (and requirements.txt).  My expectation was that people would install the package from PYPI before trying to run the samples and so pip would automatically resolve the dependencies for you.

Can you tell me what you did instead and so what would have helped you find this out more easily?

**Comment by peterbrittain** [comment]
Assuming that it was a failed pip install, I've updated the main README to make it clear that the full dependencies are.
