### ISSUE TITLE
Wait until PopUpDialog is confirmed?

### ISSUE THREAD

**Issue by Michal-Gagala** [peterbrittain/asciimatics#110]
I have a function that runs when a button is pressed, and this is the last part of it:
```
                self._scene.add_effect(
                    PopUpDialog(self._screen,
                           "Your username is: {}".format(username),
                           ['ok'], 
                           self.nextscene))
                raise` NextScene('MENU2')
```

The problem I'm having is that the NextScene is raised instantly, which means the PopUp is skipped. What's the best way to get around this?

**Comment by peterbrittain** [comment]
Look at what the forms sample does for the quit dialog.  In short you need to use an `on_close` callback to raise the `NextScene`  instead of doing it as soon as you add the Effect.

**Comment by peterbrittain** [comment]
I'm assuming that this was enough help.  Now closing.
