### ISSUE TITLE
Install failed at pypiwin32-220 but I already have pywin32-221

### ISSUE THREAD

**Issue by hcchengithub** [peterbrittain/asciimatics#111]
According to 
http://www.lfd.uci.edu/~gohlke/pythonlibs/#pywin32 , I think pywin32-221, which is already installed on my computer, is newer version of pypiwin32-220. If this is correct then why 

    pip install asciimatics

still try to install the older pypiwin32-220 on my computer? (and failed)

**Comment by peterbrittain** [comment]
My guess is that you've installed `pywin` but asciimatics declares its dependency on `pypiwin`.  The rest is then down to `pip` and the package you're trying to install.  

You could try installing the pypiwin version from your list instead.  Or you could try declaring a drpendency on `pywin` by cloning and building your own asciimatics distribution.  If none of that works, then you'll need to debug the failed installation... However these aren't asciimatics issues and so I'm closing this issue.
