### ISSUE TITLE
layouts have to be added to widgets before child widgets are added to layout

### ISSUE THREAD

**Issue by garfieldnate** [peterbrittain/asciimatics#118]
If you change the example script in [forms.py on lines 86-88](https://github.com/peterbrittain/asciimatics/blob/master/samples/forms.py#L86) like so:

        layout2.add_widget(Button("View Data", self._view), 1)
        layout2.add_widget(Button("Quit", self._quit), 2)
        layout2.add_widget(self._reset_button, 0)

then you get a very puzzling error:

    File "test.py", line 180, in <module>
      Screen.wrapper(demo, catch_interrupt=True, arguments=[last_scene])
    File "/usr/local/lib/python3.6/site-packages/asciimatics/screen.py", line 1021, in wrapper
      func(screen, *arguments)
    File "test.py", line 171, in demo
      Scene([ContactView(screen, contacts)], -1, name="Edit Contact")
    File "test.py", line 148, in __init__
      layout2.add_widget(Button("OK", self._ok), 0)
    File "/usr/local/lib/python3.6/site-packages/asciimatics/widgets.py", line 759, in add_widget
      if widget.name in self._frame.data:
  AttributeError: 'NoneType' object has no attribute 'data'

The requirement that layouts be added to the parent before further children are added to the layout was surprising to me, and the exception did not help me find the solution to the problem. It would be better if layouts could be added to their parents at any time, but if this is not possible then a more descriptive error would be helpful.

**Comment by peterbrittain** [comment]
Breaking that ordering will have all sorts of knock-on problems with object initialisation.  It would be necessary to defer everything to the last minute, which means this is likely to be hard.  I'll have a think about this and see what's possible.

**Comment by peterbrittain** [comment]
Yeah - it proved messy.  I've added a more informative Error.

**Comment by garfieldnate** [comment]
Thanks!
