### ISSUE TITLE
Request: text wrapping option for TextBox

### ISSUE THREAD

**Issue by garfieldnate** [peterbrittain/asciimatics#119]
Inside of TextBox fields, if a line is too long to be shown then the user must always scroll to the right to see the end of it. It would be very useful if TextBoxes could be made to wrap words automatically.

**Comment by peterbrittain** [comment]
Nearly there!  The textbox_flow branch now has a working version.  Just need to add some tests before I merge...

**Comment by garfieldnate** [comment]
Yay! 🎉

**Comment by peterbrittain** [comment]
Now merged as of https://github.com/peterbrittain/asciimatics/commit/2095292f89137df0378f192c31e185ed6cab6d43

**Comment by garfieldnate** [comment]
Thank you! This will be great.

**Comment by peterbrittain** [comment]
You're welcome!
