### ISSUE TITLE
Request: Support passing on global events to effects

### ISSUE THREAD

**Issue by garfieldnate** [peterbrittain/asciimatics#120]
I am able to do this now, but with all of these underscore variables I'm not sure if it will always be supported:

        def global_shortcuts(event):
            current_scene = screen._scenes[screen._scene_index]
            current_scene._effects[0].handle_event(event)
        scenes = [Scene([MyView(screen, entries, view_state)], -1, name="MyView")]
        screen.play(scenes, stop_on_resize=True, start_scene=start_scene, unhandled_input=global_shortcuts)

**Comment by peterbrittain** [comment]
That's somewhat confusing...  By definition, these events are the ones that aren't handled by any Effect.  You can achieve the same result by processing the event in either your Scene or your Effect.

**Comment by peterbrittain** [comment]
This will always be supported, so I think this issue can be closed.  Let me know if there's something you want to do that's not possible this way.

**Comment by garfieldnate** [comment]
Yeah, we can close this. I saw the documentation for global key handling but not the documentation for `process_event()`
