### ISSUE TITLE
Request: Support immutable text fields

### ISSUE THREAD

**Issue by garfieldnate** [peterbrittain/asciimatics#121]
Currently you can set TextBox.disabled and Text.disabled to disable input on these fields. However, this changes the styling so that the text is harder to read. It would be much nicer if I could create a non-editable text box with normal styling. This would also allow me to capture key strokes so I could use letters for commands (f=forward, etc.).

**Comment by peterbrittain** [comment]
You can already do this with a disabled TextBox and a [custom colour](http://asciimatics.readthedocs.io/en/stable/widgets.html#custom-colours-ref).

**Comment by garfieldnate** [comment]
I just tried your suggestion, but since setting Text and TextBox to disabled makes the boxes unselectable, so there is no way for the user to scroll and see longer texts that flow off the edge of the widget. Is there any way to make them disabled but selectable?

**Comment by peterbrittain** [comment]
Not at the moment.  Being disabled, they cannot get the input focus and so cannot be scrolled.

**Comment by Eeems** [comment]
This is a feature I would also appreciate. I may open a PR for it if I get the chance this weekend.

**Comment by peterbrittain** [comment]
@Eeems Any help is always appreciated!  

In this case, if we need to process events when disabled, I think it would be good to break this out into a separate method on Widget.  This should prevent all widgets from needing to check state on event input and so prevent bugs in the long run.  The Layout could also call both this method and the existing one when a widget is enabled in order to prevent code duplication if needed.

**Comment by garfieldnate** [comment]
@Eeems I've found that handling and ignoring all keyboard input except the arrow keys does exactly what I need (for now), so I don't have an immediate need for this type of widget anymore.

**Comment by Eeems** [comment]
@garieldnate: could you post some example code? I still have need of this, I've just been too busy to work on it the last couple weeks.

**Comment by garfieldnate** [comment]
So if you look at the `process_event` code for the Text widget, you can see that it inserts characters by listening for any incoming ascii (not sure how that works on, say, a Korean keyboard, but it works for me so far). https://github.com/peterbrittain/asciimatics/blob/master/asciimatics/widgets.py#L1644. It also allows deletion by listening for the backspace and delete keys.

Just catch those events and ignore them in your process_event method like so:

    def process_event(self, event):
        if isinstance(event, KeyboardEvent):
            ...
            # disallow all editing
            elif event.key_code == Screen.KEY_BACK:
                return event
            elif event.key_code == Screen.KEY_DELETE:
                return event
            elif event.key_code >= 32:
                return event

This has the advantage that the user can still move the cursor around with the arrow keys to scroll the text if it's too long to fit in the space provided.

**Comment by peterbrittain** [comment]
Asciimatics will send non-ascii characters as separate events using the unicode glyph code, so the logic for >= 32 should still work.

However, I don't think that this the complete solution as it could break if I added more special editing keys in the future - e.g. control codes to cut and paste.  The sort of thing I have in mind is 2 entry points - one for all widgets (which handles navigation - i.e. the events you're allowing through) and one for read-write (i.e. `disabled=False`) widgets (which would contain the event logic that you've disabled in your snippet).  Mainline widget logic simply calls both while there is a valid event.

**Comment by peterbrittain** [comment]
Hmmm...  Looks like this still hasn't been resolved with current function and we really do need a better way to allow people to have readonly fields that allow you to view and scroll content.

**Comment by peterbrittain** [comment]
On reflection, I think the 2 entry points for this stuff is overkill.  The only widgets that actually need to distinguish readonly from diabled are the ones that allow you enter a free-form value - i.e. Text and TextBox.  May as well just have some simple white-listing of events in that case.

**Comment by garfieldnate** [comment]
Yay! 🎉

**Comment by peterbrittain** [comment]
Sorry it took so long...

**Comment by garfieldnate** [comment]
It's not like I'm paying you to do it 😆 Thanks for getting around to it!
