### ISSUE TITLE
How or Where to change a Frame background colour? (question)

### ISSUE THREAD

**Issue by mental32** [peterbrittain/asciimatics#122]
I can not find in the documentation where it says how i could change the Frames background colour if stated at all,

**Comment by peterbrittain** [comment]
In order to change colours, you need to [redefine the palette for the Frame](http://asciimatics.readthedocs.io/en/stable/widgets.html#colour-schemes).  Note that just changing the background won't be enough, you'll also need to check the background attribute for each entry.

**Comment by mental32** [comment]
My frame is empty here is my source code for context:
```python
class Mainframe(Frame):
    def __init__(self, screen, **kwargs):
        fargs = {
            'height': kwargs.get('height', screen.height), 
            'width': kwargs.get('width', screen.width),
            'title': kwargs.get('title', 'A rad CLI'),
            'data': kwargs.get('data', {}),
            'x': kwargs.get('x', 0),
            'y': kwargs.get('y', 0)
        }

        super(Mainframe, self).__init__(screen, **fargs)
        p = self.palette
        p['background'] = (Screen.COLOUR_BLACK, Screen.A_NORMAL, Screen.COLOUR_BLUE)
        self.palette = p
        self._clear()```
I am still confused as to why this doesn't work. Apologies for any disruptions

**Comment by peterbrittain** [comment]
What are you trying to achieve?  That will just change the foreground colour of the default palette from white to black.  If you really want to see a different colour, you want to change it to something like:

    p['background'] = (Screen.COLOUR_WHITE, Screen.A_NORMAL, Screen.COLOUR_BLACK)

**Comment by mental32** [comment]
Ah i see i was changing the wrong attribute, my bad! cheers that cleared it up the issue
