### ISSUE TITLE
Attempted to run demo code on Windows with Python 3.6.2

### ISSUE THREAD

**Issue by Magikarple** [peterbrittain/asciimatics#123]
Started without admin permission
`    Screen.wrapper(demo)
  File "C:\Program Files\Python36\lib\site-packages\asciimatics\screen.py", line 1016, in wrapper
    unicode_aware=unicode_aware)
  File "C:\Program Files\Python36\lib\site-packages\asciimatics\screen.py", line 925, in open
    None))
pywintypes.error: (6, 'CreateFile', 'The handle is invalid.')`
Started with admin permission
`    Screen.wrapper(demo)
  File "C:\Program Files\Python36\lib\site-packages\asciimatics\screen.py", line 1016, in wrapper
    unicode_aware=unicode_aware)
  File "C:\Program Files\Python36\lib\site-packages\asciimatics\screen.py", line 925, in open
    None))
pywintypes.error: (6, 'CreateFile', 'The handle is invalid.')`
I haven't changed this from the demo code, but it does seem to import the modules fine.

Earlier I was getting an error that point to line 1399 (even though the code that I ran was identical iirc):
`1398: if sys.platform == "win32":
1399:     import win32console`

Is this an error regarding installation or this just improper software?

**Comment by peterbrittain** [comment]
That error is because asciimatics cannot open the console stdout or stdin handles, which is usually a sign that you are not running it from the command line shell.

Can you please tell me exactly what version of Windows and asciimatics you are using and how you are starting the process?

**Comment by Magikarple** [comment]
I was running it from IDLE, I assumed it run like tkinter and just open my console automagically.
I launched it with regular python and it works perfectly now, thanks for the pointer, Peter!

**Comment by peterbrittain** [comment]
You're welcome.  Have a look at http://asciimatics.readthedocs.io/en/latest/troubleshooting.html#i-can-t-run-it-inside-pycharm-or-other-ides.  If you can configure IDLE to start python using the command shell, please let me know so I can update the docs.

**Comment by Magikarple** [comment]
I do not believe it's possible to configure the program that executes code in IDLE, although for pretty much any other IDE, it is more than likely that it can be configured as it's simply a matter of using the right .exe (in a standard windows installation, it is simply python.exe in the top level of the python folder).

**Comment by peterbrittain** [comment]
Oh well.  Thanks for checking.

**Comment by Magikarple** [comment]
I personally wouldn't want to change it either, to be quite honest, but the alternative of just alt-tabbing to whatever folder has the file and running it (with the default program set to python.exe) is a fair compromise for laziness of not wanting to set up a decent IDE.
