### ISSUE TITLE
how to get the widget with the current focus

### ISSUE THREAD

**Issue by garfieldnate** [peterbrittain/asciimatics#124]
How do you find which widget currently has the focus?

Use case: I have a whole bunch of Text and TextBox widgets in a view. I would like to write a single`process_event` method with some conditional logic that depends on which of the text boxes currently has the focus.

My workaround for now will be to pass in an `on_focus` callback to the Text/TextBox widgets. The callback will store the name of the focused widget in the view state.

**Comment by peterbrittain** [comment]
There is no public API to get the focus.  

I'm not totally convinced I want to expose it yet as I'd expect custom logic for your widgets to be handled _in_ the widgets. For example, depending on what you really need to do, you could:

1. Subclass Text and Textbox to augment `process_event` for each class.
2. Extend option 1 by providing a function as a  parameter on your init method.  You could then call function this for every event.  This allows you to provide custom logic beyond the Text/TextBox split.

On the other hand, I'm not _against_ creating a new property on the Frame to expose the widget with the focus.  Should be a small change if you want to make it...

**Comment by garfieldnate** [comment]
Thanks! This will be great to have.
