### ISSUE TITLE
Cursor starts in wrong position in reset forms

### ISSUE THREAD

**Issue by garfieldnate** [peterbrittain/asciimatics#125]
I'm trying to change the ContactForm sample to have an initial value for a name, "foo". I'm not sure how to do this correctly, and my attempt leads to a problem rendering text boxes.

My naive try to set the default data was to change the call to `super` for ContactView:

        super(ContactView, self).__init__(screen,
                                          screen.height * 2 // 3,
                                          screen.width * 2 // 3,
                                          hover_focus=True,
                                          title="Contact Details",
                                          reduce_cpu=True,
                                          data={"name": "foo"})

I don't think that's correct, though, given that this constructor is called every time the screen is resized and it seems like this might reset the data to the starting value.

If you actually run this you will see that the cursor appears in the middle of the text box but there is no text.

**Comment by garfieldnate** [comment]
I realized shortly after posting this that the proper way to set a default value would be to store a default value in the model object and then use this to fill in the default data object returned in `get_current_contact`.

The bug with the cursor remains, though. If you set the value of a Text widget to a string that is shorter than the current value, the cursor location is not updated and is "stranded".

**Comment by peterbrittain** [comment]
OK - I see the issue.

**Comment by peterbrittain** [comment]
Fixed by https://github.com/peterbrittain/asciimatics/commit/2fc0ca02413e5f622a9c077bb28ddc82f46ecd9e

**Comment by garfieldnate** [comment]
Thanks, this fixes some other buggy behavior I've been encountering, too. I've cherry-picked this into master in my own copy.

**Comment by peterbrittain** [comment]
Doh!  I meant to check that into master...  Sigh.
