### ISSUE TITLE
Allow Screen.wrapper to return data

### ISSUE THREAD

**Issue by brycepg** [peterbrittain/asciimatics#127]
Currently `Screen.wrapper` will not allow data to be returned. Since my program does other things after asciimatics ends, I end up using one of the wrapper arguments as a out parameter (yuck).

Could/should Screen.wrapper allow a return value from the wrapped function?

**Comment by peterbrittain** [comment]
Good question...  I thought I had copied the logic of the curses module, but after looking at the module, I see it passes on any  return codes from the wrapped function.

Absolutely no objection  to adding this.  Assuming you've already tweaked your own copy, feel free to submit a PR.

**Comment by peterbrittain** [comment]
I had a few spare minutes.  See https://github.com/peterbrittain/asciimatics/commit/a2eb56e5a69a0295e0b0d00d7172976bf0f39dda

**Comment by brycepg** [comment]
Thanks!
