### ISSUE TITLE
text box with support for raw ansii input

### ISSUE THREAD

**Issue by garfieldnate** [peterbrittain/asciimatics#131]
For my app, I really needed to be able to support getting verbatim output from other terminal apps and showing it to the user. These other commands might print color text, and I wanted the color to be preserved and shown to the user as-is. I've basically been approaching my asciimatics app as if it were a web app in the terminal; if I were doing a web app, I would be able to use any HTML along with the framework widgets, and I had not considered that a similar way of working with asciimatics and raw ansii codes would be difficult.

I dug around in the asciimatics code for a while and decided that implementing this as a widget would be... pretty difficult, at least for me. My workaround below might be useful for the library documentation.

First we create a new exception to hold the external command to be run and scene to resume once it's finished:

    class ExternalCallException(Exception):
        def __init__(self, last_scene, command):
            self.last_scene = last_scene
            self.command = command

When the external command should be run, we raise the exception like so (self is the widget object):

    raise ExternalCallException(self._scene, 'my command here')

Then we add an extra `except` clause under the one handling screen resizes:

        except ResizeScreenError as e:
            last_scene = e.scene
        # new code below
        except ExternalCallException as e:
            last_scene = e.last_scene
            try:
                # -K means quit on ^C; -R means print ansii codes as-is
                process = Popen(e.command + " | less -K -R", shell=True)
                process.wait()
            except KeyboardInterrupt:
                # let less handle this, -K will exit cleanly
                pass

With this, the external command is piped to `less`, which temporarily controls the whole screen and shows the command's output in color. When the user quits `less`, the app reappears using the same mechanism as when the screen is resized.

**Comment by peterbrittain** [comment]
Hmmm...  This will be problematic for any terminal that doesn't support ansi codes - i.e. Windows and old terminal types.

Breaking out of the play loop to allow other programs to run is one option.  I wonder if there's a case for a terminal to asciimatics codec, though?  In theory this could translate terminal control codes to colour maps so you can just use `paint()` to display the output.  Of course you'd still need a widget to display it.

Will think on this some more...

**Comment by garfieldnate** [comment]
Yeah, a codec is in line with what I was thinking after looking for a quick fix. I don't know what that would entail for other platforms. This would be a fantastic feature, though. We could then make a "less box" widget and use it to develop tools like a better version of multitail (which is already a great tool).

**Comment by garfieldnate** [comment]
One other related feature I would love to have is related to the ability to print raw ansi. I would love to be able to use [iTerm's image display capability](https://www.iterm2.com/documentation-images.html). It uses an extension of the ansi escape codes. Even if it's not the best to have in core asciimatics because it isn't portable, it would be nice to have a mechanism where I could do this myself (by printing the raw ansi code at some location).

**Comment by peterbrittain** [comment]
OK - that latter request is a completely new idea, so I've spun it off into #132

**Comment by peterbrittain** [comment]
Back to this thread...  I had a look at getting some output from other applications and then feeding them into a file that I could then try to process for a widget...  But that doesn't work because all the apps I tried are well-behaved and so switch off their terminal control codes when they have no access to a TTY.

I guess I'd also have to look at controlling a pty for anything here, which definitely puts it beyond anything I can finance right now.  Sorry.  I'll leave this issue on the backlog for now...

**Comment by garfieldnate** [comment]
Don't' worry about leaving it in the backlog. I understand it's a large feature and you have a day job ;)

So my use case for it happens to be a "less box" for showing output from another program, but I think the more general piece of functionality is just to have a text box that allows ansi or other styling inside of it.

If you still want some output to test with, I happen to be using a colorful dictionary tool called myougiden, which is well behaved but allows you to override the defaults. Do `pip install myougiden` and then try `myougiden --human -c hello > hello.txt`.

Actually, I'll just attach that here:
[hello.txt](https://github.com/peterbrittain/asciimatics/files/1598993/hello.txt)

**Comment by peterbrittain** [comment]
Just came across https://github.com/selectel/pyte.  probably will be of use for this Issue.

**Comment by peterbrittain** [comment]
OK - I've started to pull together a prototype for this sort of function.  All the latest code is in https://github.com/peterbrittain/asciimatics/tree/colour_parsing.

It's not ready for general consumption yet, but I can now embed a Xmas tree into a TextBox - as you can see in the forms demo.  Still plenty to do, but I thought it might be good to get this checked in at this stage.

**Comment by garfieldnate** [comment]
Very cool!

**Comment by peterbrittain** [comment]
The `more_colours` branch looks like it might be getting close to being a suitable framework.  A bit more tidy up to do, then I need to check what happens when I need pass state between parsers.  Once I have that working, we can go live.

**Comment by peterbrittain** [comment]
OK - so I've now had a bash at a basic Ansi Terminal colour code parser.  Latest code checked in to `more_colours` should allow you to put basic terminal output with colour codes into the TextBox.  

There are a load of other codes that we might need to worry about, but I suspect I don't have time to address.  Can you have a look at how this works for your use case and let me know if there are any obvious errors in the output that still need addressing?

**Comment by garfieldnate** [comment]
Yep, I'll try to get to it this weekend.

**Comment by peterbrittain** [comment]
Great!  Check out the updated forms demo, which uses the new parser to handle this logic.

**Comment by garfieldnate** [comment]
When I scrolled up in the forms box I thought forms.py was parsing out my bash history 😂

The forms.py demo looks pretty good! I'll try to find time soon to integrate this into my own project. But since you're already parsing out and displaying the file I sent you, I think it should all work great. Thank you so much for working on this!

**Comment by peterbrittain** [comment]
Nice!  :-)

There's still some loose ends to tie up on the function, so I'd suggest holding off using this until I've checked in the associated tests and merged to master.

**Comment by garfieldnate** [comment]
Will do, thanks!

**Comment by peterbrittain** [comment]
Implemented in #221
