### ISSUE TITLE
Color map for images in Static Renderer

### ISSUE THREAD

**Issue by Morasiu** [peterbrittain/asciimatics#133]
I didn't find any information in documentation about how color map for images in Static Renderer should work. I had to dig in code and found this regex `r"^\$\{((\d+),(\d+),(\d+)|(\d+),(\d+)|(\d+))\}(.*)`. I need it to make a multicolored fish.

**Comment by peterbrittain** [comment]
Yeah - you're right - that's not obvious...  It's only documented in the API docs right now - see http://asciimatics.readthedocs.io/en/stable/asciimatics.html#asciimatics.renderers.StaticRenderer

I'll add something to the rest of the docs to make that clear.

**Comment by Morasiu** [comment]
I guess that end line and spaces are forbidden?

**Comment by peterbrittain** [comment]
If you mean inside the `${c,a, b}` escape sequence, then yes - coz it won't match the regex right now.  If you need it to be more flexible, I'd happily merge a pull request that expands the regexp and tests it works as desired.

**Comment by Morasiu** [comment]
I'm not sure how your code works, but this is regex which match spaces:
`^\$\{(([\s\d]+),([\s\d]+),([\s\d]+)|([\s\d]+),([\s\d]+)|([\d\s]+))\}(.*)`

**Comment by peterbrittain** [comment]
I've updated the docs in https://github.com/peterbrittain/asciimatics/commit/c0a8ac59067aeba9a12b92a8d5b4889bb19d8854

Please submit a PR (as per above) if you'd like to get white space support added.
