### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by disconsis** [peterbrittain/asciimatics#134]
Not sure if this is the right place to raise this issue, but here goes.

I recently came across your excellent package. While consulting the documenation on readthedocs, I repeatedly came across the issue that none of the code snippets mentioned the _imports_. 

For example, the quick start guide has the code
```python
def demo(screen):
    effects = [
        Cycle(
            screen,
            FigletText("ASCIIMATICS", font='big'),
            screen.height // 2 - 8),
        Cycle(
            screen,
            FigletText("ROCKS!", font='big'),
            screen.height // 2 + 3),
        Stars(screen, (screen.width + screen.height) // 2)
    ]
    screen.play([Scene(effects, 500)])

Screen.wrapper(demo)
```
This is impossible for anyone to run without knowing where each of the classes `Cycle`, `FigletText`, `Stars`, `Scene`, and `Screen` are located, and I had to spend quite some time grepping through the docs for figuring it out.

It _did_ make me go through the entire documentation once, but I'm guessing that's not a design decision. :stuck_out_tongue:

Apologies if I'm missing something.

**Comment by peterbrittain** [comment]
You're right - that was not a deliberate decision.  :-)  I'm surprised no one has commented on it before now...  

I guess the samples help solve that issue.  Still it would be nice for the docs to give some initial pointers here.  I'll add something to the docs.

**Comment by disconsis** [comment]
The samples do help, but it's not the first place I (and possibly others) typically look when consulting documentation.

**Comment by peterbrittain** [comment]
Totally agree.  Will review and try to fix when I get a few minutes.

**Comment by peterbrittain** [comment]
I've reviewed and most of the docs provide a healthy selection of links to the class definition, which implicitly show where to import from.  I don't think it makes sense to put import statements on obviously incomplete programs, but the stuff that should be a standalone program have been updated.
