### ISSUE TITLE
Cannot install on Termux due to Pillow

### ISSUE THREAD

**Issue by MatCorgi** [peterbrittain/asciimatics#136]
Everytime i try to install Pillow by itself or as a requirement to this lib it gives me the following error:
The headers or library files could not be found for zlib, a required dependency when compiling Pillow from source.

**Comment by peterbrittain** [comment]
Did you try the instructions in here?

http://asciimatics.readthedocs.io/en/stable/troubleshooting.html#installation-issues

**Comment by MatCorgi** [comment]
Just did and got this error:
Unable to locate package libjpeg-dev

**Comment by peterbrittain** [comment]
Hmmm...  Either I put the wrong instructions in the docs or they've changed the name.  Try this instead

    apt-get install clang python-dev libjpeg-dev

**Comment by MatCorgi** [comment]
Thank you! Finally something that worked.
