### ISSUE TITLE
MultiColumnListBox updating suggestions?

### ISSUE THREAD

**Issue by lillyjsm** [peterbrittain/asciimatics#138]
Hi, I was wondering if you could make a suggestion on the best way to update the items MultiColumnListBox is displaying?

In short, I am using this widget to display chat messages coming from a socket. When the message arrives, I have a function that appends to MultiColumnListBox.options . For some reason, the new appended line will only display if I press a key (I assume trigger an event?) after I have appended the new line. Do you have any suggestions for this? 

Thanks

**Comment by peterbrittain** [comment]
See http://asciimatics.readthedocs.io/en/stable/animation.html#cpu-considerations

In particular, you want the `force_update()` method.

**Comment by lillyjsm** [comment]
Sorry, not sure how I overlooked this. That is what I was looking for!

Thanks

**Comment by peterbrittain** [comment]
No problem. I think we can close this now!
