### ISSUE TITLE
Vertical Divider for layout

### ISSUE THREAD

**Issue by lillyjsm** [peterbrittain/asciimatics#139]
Hi again,

I was searching for a way to create a vertical divider within my layouts. I didn't see anything on this in the documentation, so I created a new class in widgets.py for this. I didn't know if this is something you'd be willing to take a pull request for? I can provide screenshots/code as well

**Comment by lillyjsm** [comment]
So, in the main area of my layout, I was using a scheme similar to:
`self.mainBody = Layout([12, 2, 72, 2, 12], fill_frame=True)`

I was only adding widgets to indexes 0, 2, 4 in the Layout array, to give the text in the widgets some buffer between each other. I made the VertDivider widget to insert into indexes 1 and 3, and it draws a vertical line between my text boxes:

![screenshot](https://user-images.githubusercontent.com/23708128/36872201-72847db2-1d72-11e8-8e33-fe1bc138a04a.png)

The code for the VertDivider is below. It strongly mirrors the Divider widget. I also wasn't sure if there way a better way to set the height in regards to the for loop? I used Widget.FILL_FRAME.

`class VertDivider(Widget):
    """
    Testing a vertical divider for the layout
    """

    def __init__(self, draw_line=True, height=Widget.FILL_FRAME):
        super(VertDivider, self).__init__(None, tab_stop=False)
        self._draw_line = draw_line
        self._required_height = height

    def process_event(self, event):
        return event

    def update(self, frame_no):
        (color, attr, bg) = self._frame.palette["borders"]
        if self._draw_line:
            vert = u"│" if self._frame.canvas.unicode_aware else "|"
            for i in range(self._h):
                self._frame.canvas.print_at(vert, self._x, self._y + i, color, attr, bg)

    def reset(self):
        pass

    def required_height(self, offset, width):
        return self._required_height

    @property
    def value(self):
        return self._value`

**Comment by peterbrittain** [comment]
Yeah - the use of `FILL_FRAME` isn't quite right as it will extend the Layout to fill the Frame in all cases.  I think what we really need is a new setting that tells the Layout to set the height to the maximum of all other columns.  This would require a tweak to `Layout.fix()`.  If you're up for that, please submit the PR.

**Comment by peterbrittain** [comment]
OK - I've managed to refactor the Layout logic to handle that and added a simmilar looking VerticalDivider widget now.  See https://github.com/peterbrittain/asciimatics/commit/13480406ac652abfbbd9772c8d5304857b2b2c66
