### ISSUE TITLE
MultiColumnListBox Hiding column data that fits the column exactlty

### ISSUE THREAD

**Issue by jakethemc** [peterbrittain/asciimatics#141]
The widget slices the row string and adds in a '...' even if the data exactly fits the column. This truncation is also inconsistent with standard ListBox widgets

**Comment by peterbrittain** [comment]
Good spot!  Now fixed in https://github.com/peterbrittain/asciimatics/commit/1cfabf93b51b49185ff7b07980de7d08a17bfa0f
