### ISSUE TITLE
Support running in background thread

### ISSUE THREAD

**Issue by jacobq** [peterbrittain/asciimatics#142]
Is there a way to run this as a background thread? I tried something like this:
```python
def runUI():
    from asciimatics.screen import Screen
    Screen.wrapper(statusUI)    

def statusUI(screen):
    screen.clear()
    (height, width) = screen.dimensions
    while True:
        # ...
        screen.refresh()
        sleep(1)

from threading import Thread
thread = Thread(target=runUI)
thread.start()
```

but encounter an error when running:
`ValueError: signal only works in main thread`

(sorry if this is abusing the GH issue channel -- It is partially a support question and partially a feature request)

**Comment by Eeems** [comment]
It looks like [screen.py](https://github.com/peterbrittain/asciimatics/blob/f3408ca297c7222d4af12fbb3630de83b3bad993/asciimatics/screen.py#L2277-L2304) is where signal is used. This seems non-trivial to remove. Is there a reason you'd want to run this in a separate thread instead of the main thread?

**Comment by jacobq** [comment]
To be honest, I only want one thread, but it seems lots of libraries still haven't updated to use `asyncio` / event loops, and I'm not a Python expert, so it seems non-trivial to dothis. Since I'm just using `asciimatics` to display some status information (on RPi LCD) it seemed a good candidate for a background thread, if I have to use threads.

**Comment by Eeems** [comment]
I would suggest having the UI (this) in the main thread and adding any other work you need to a background thread instead. This library is meant for console applications, which typically are all single threaded or have the UI in the main thread.

**Comment by jacobq** [comment]
OK, I'll find a way to deal with it :/

**Comment by peterbrittain** [comment]
Am I missing something, but can't you just construct the Screen on your main thread using the open() method and then run it from your background thread?

**Comment by jacobq** [comment]
@peterbrittain You are right, this can work. I just did something like this:

```python
from time import sleep

stop_ui = False

def on_screen_ready(screen):
    from threading import Thread
    ui_thread = Thread(target=screen_loop, args=(screen,))
    ui_thread.start()


def screen_loop(screen):
    global stop_ui

    screen.clear()
    # ... setup screen ...
    while not stop_ui:
        # ... update screen ...
        screen.refresh()
        sleep(1)

    screen.clear()
    print("UI loop terminating")


if __name__ == "__main__":
    from asciimatics.screen import Screen
    Screen.wrapper(on_screen_ready)
    print("Set up UI")
    sleep(2)
    print("Time to quit")
    stop_ui = True
```

**Comment by peterbrittain** [comment]
Good!  I assume that's all you need now...  Feel free to follow up if you need more.
