### ISSUE TITLE
Question: QR code

### ISSUE THREAD

**Issue by jlstanus** [peterbrittain/asciimatics#143]
Is there a library to generate QR compatible and detected with mobiles with asciimatics?

**Comment by peterbrittain** [comment]
There is nothing I know that's already generating QR codes for asciimatics.  That said, you could look at creating something with https://github.com/lincolnloop/python-qrcode.  It should be possible to use one of the print_xxx methods to create a QR code to feed into asciimatics.

**Comment by peterbrittain** [comment]
Note that you can't just take the output from print_xxx directly as this will contain ansi escape codes, which will be no good to you until something like #131 is implemented.  Your best bet would be to create your own rendered text for the QR code object using the same logic as the print_ascii (in qrcode).
