### ISSUE TITLE
Question: Supporting screen resizes whilst running Asciimatics in own asynchronous framework using draw_next_frame

### ISSUE THREAD

**Issue by ianadeem** [peterbrittain/asciimatics#144]
First of all, a massive Kudos to @peterbrittain for this marvellous project! I came across it only recently after having searched for something like this for a long time, and it's been working very well so far!

I am using asciimatics with my own asynchronous framework (essentially calling draw_next_frame() every 0.05 seconds as suggested in the docs). I would like to be able to handle screen resizes like the play() method does. The code there does two things -- exit() the current scene and raise the ResizeScreenError with the current scene. Unfortunately, there is no way of get hold of the current scene from outside the screen object (apart from accessing private members), so my code has no elegant way of performing these two tasks.

The fix might be as simple as having a getter on the screen object for the current scene -- but I might be overlooking something?

**Comment by peterbrittain** [comment]
Thanks!  :)

Yeah - if you don't use `play` you don't get access to the current scene on the Exception it would throw, do you?

Looks like you have a case for exposing a simple readonly property for the current scene.  I'd happily accept that as a PR.

**Comment by ianadeem** [comment]
Great, thanks for the confirmation -- I'll try to submit a PR asap!
