### ISSUE TITLE
Listbox for display only - no user select

### ISSUE THREAD

**Issue by cyclostationary** [peterbrittain/asciimatics#146]
Hi, just wondering is it possible to have a listbox that only displays data and doesn't allow any user selection.. e.g. I have multiple listboxes and only want 1 to be highlighted when the user tabs through them (the others should be ignored) - is this possible?

**Comment by peterbrittain** [comment]
Have you tried disabling the Listbox?  See http://asciimatics.readthedocs.io/en/stable/widgets.html#disabling-widgets for details.

**Comment by cyclostationary** [comment]
Perfect thanks, I made a bad assumption that disabling it would hide it altogether :)
