### ISSUE TITLE
Documentation skips key steps/info

### ISSUE THREAD

**Issue by kfsone** [peterbrittain/asciimatics#148]
The quickstart guide and all subsequent documentation does not reference module paths. The quick start says:

"Once you have installed asciimatics as per the instructions above, simply create a Screen, put together a Scene using some Effect objects and then get the Screen to play it".

The provided sample does not give any imports. So, how does one create a Screen? Where is it located? The modules docstrings aren't much help.

Solution:

In the quick-start example provide the requisite import statements etc to produce a pastable, actual example, rather than a code approximation.

**Comment by peterbrittain** [comment]
Were you looking at the stable docs?  I've just made some changes in master to cover this...

See https://github.com/peterbrittain/asciimatics/commit/27e210e066bb3096bf6f112f5e792b95c6b7dc4d

**Comment by peterbrittain** [comment]
I'm assuming that was the case...  Please let me know if there was something else.
