### ISSUE TITLE
Wider community support?

### ISSUE THREAD

**Issue by peterbrittain** [peterbrittain/asciimatics#154]
Anyone interested in joining this project and helping to support it?  

I'm happy to keep running it, but the question load is beginning to tick up and some help answering the general questions and redirecting genuine bugs to the ticket system would be appreciated...  I'm happy to look into some free IRC type options, but it's only worthwhile if other people out there want to join in.

Please let me know if you're interested by replying to this issue.  Oh and if you have a recommendation for a free team chat solution, I'm very happy to take suggestions.

**Comment by franklintimoteo** [comment]
Maybe also a Telegram group.

**Comment by Eeems** [comment]
As a heavy IRC user I'd much prefer that or [Matrix](http://matrix.org). Or bridging a number of them.

I've been keeping an eye on issues as they come in and I've replied on one or two. I wouldn't want to officially help support it though as I'm too busy with all my other projects and my day job. I'm always happy to have another channel to idle in and provide help when I can though.

**Comment by lwm** [comment]
Hey there, I'm really enjoying using this library at the moment. Just picked it up.

I've used https://gitter.im/ quite a lot and people *do tend to turn* up due to the convenience of it.

While I'm working on my project, I could lend a hand ... :)

**Comment by peterbrittain** [comment]
OK - so I've had a play and gitter makes life so easy to start a chat room.  Thanks for the recommendation.

I've tried inviting people, but if that fails, feel free to join me at:
https://gitter.im/asciimatics/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by Eeems** [comment]
> OK - so I've had a play and gitter makes life so easy to start a chat room. Thanks for the recommendation.

:( I guess I'll have to add gitter to my workflow along with IRC, matrix, slack, teams, and discord.

**Comment by peterbrittain** [comment]
Sorry, but the barrier for entry was so low, especially if you're already on github.

**Comment by peterbrittain** [comment]
That said, I'm not saying this is set in stone...  I'm happy to try something else if this isn't working after a while.

**Comment by lwm** [comment]
> Sorry, but the barrier for entry was so low, especially if you're already on github.

Exactly.

**Comment by lwm** [comment]
You could close this by adding a section to the README.md as well (for one of my projects, I did [this](https://git.coop/lwm/tasty-discover#maintenance)). I believe https://github.com/peterbrittain/asciimatics/pull/165 should also bring people in too.

**Comment by peterbrittain** [comment]
Yeah - I just need to tweak where it put the badge.  Hopefully will be able to sort this today.

**Comment by peterbrittain** [comment]
OK - that's in.  I'll close this for now.  Looks like we know where we're going now and so no need to block anything on this issue.
