### ISSUE TITLE
Curses crash under linux (Debian)

### ISSUE THREAD

**Issue by UplinkPhobia** [peterbrittain/asciimatics#157]
I've been trying to use asciimatics under Python 3.6 lately and on differents OS. While I had no trouble with the Windows version, under Debian (Debian GNU/Linux 8 (jessie) 64 bits) the code crashes, leaving me with a buggy terminal. I've tried under both the default terminal and Terminator, to no avail. 
I've tested this under my usual environment as well as a pipenv, and got the exact same result.

Here is the traceback (that I fixed as much as I could, the bug breaking terminal output and destroying formatting):
```
Traceback (most recent call last):
    File "demo.py", line 18, in <module>
       Screen.wrapper(demo)
    File "/home/user/.local/share/virtualenvs/virtenv-QgrnXPxJ/lib/python3.6/site-packages/asciimatics/screen.py", line 1162, in wrapper
       unicode_aware=unicode_aware)
    File "/home/user/.local/share/virtualenvs/virtenv-QgrnXPxJ/lib/python3.6/site-packages/asciimatics/screen.py", line 1131, in open
        unicode_aware=unicode_aware)
    File "/home/user/.local/share/virtualenvs/virtenv-QgrnXPxJ/lib/python3.6/site-packages/asciimatics/screen.py", line 2001, in __init__
        curses.curs_set(0)
_curses.error: curs_set() returned ERR
```

I couldn't find anything useful online to fix this, so I don't know whether I'm the only one with this problem or not.

**Comment by peterbrittain** [comment]
That curses call is trying to hide the cursor.  In theory it can fail because your terminal doesn't support the function.  Seems likely that your terminal definition is wrong.  Can you please confirm what terminal you are using and the definition that curses is using?  Specifically, can you please run the following and post to this issue:

    echo $TERM
    infocmp

**Comment by UplinkPhobia** [comment]
During my online search I found people mentioning the cursor hiding feature failing, however the terminal is able to handle the mouse (since other applications/python modules manage to use it).
I pushed my tests a bit further: I was able to reproduce the bug on another Debian computer (a more recent version, but the problem is exactly the same), but not on a Debian-based OS (Parrotsec), so it would seem it is Debian-specific.

`echo $TERM` returns:
```
xterm-color
``` 

and `infocmp` returns:
```
#	Reconstructed via infocmp from file: /lib/terminfo/x/xterm-color
xterm-color|generic "ANSI" color xterm (X Window System),
	am, km, mir, msgr, xenl,
	colors#8, cols#80, it#8, lines#24, ncv@, pairs#64,
	acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, bold=\E[1m, clear=\E[H\E[2J, cr=^M,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
	dch=\E[%p1%dP, dch1=\E[P, dl=\E[%p1%dM, dl1=\E[M, ed=\E[J,
	el=\E[K, enacs=\E)0, home=\E[H, ht=^I, hts=\EH, il=\E[%p1%dL,
	il1=\E[L, ind=^J,
	is2=\E[m\E[?7h\E[4l\E>\E7\E[r\E[?1;3;4;6l\E8,
	kbs=\177, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
	kdch1=\E[3~, kf1=\E[11~, kf10=\E[21~, kf11=\E[23~,
	kf12=\E[24~, kf13=\E[25~, kf14=\E[26~, kf15=\E[28~,
	kf16=\E[29~, kf17=\E[31~, kf18=\E[32~, kf19=\E[33~,
	kf2=\E[12~, kf20=\E[34~, kf3=\E[13~, kf4=\E[14~,
	kf5=\E[15~, kf6=\E[17~, kf7=\E[18~, kf8=\E[19~, kf9=\E[20~,
	kfnd=\E[1~, kich1=\E[2~, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
	kslt=\E[4~, meml=\El, memu=\Em, op=\E[m, rc=\E8, rev=\E[7m,
	ri=\EM, rmacs=^O, rmcup=\E[2J\E[?47l\E8, rmir=\E[4l,
	rmkx=\E[?1l\E>, rmso=\E[m, rmul=\E[m,
	rs2=\E[m\E[?7h\E[4l\E>\E7\E[r\E[?1;3;4;6l\E8, sc=\E7,
	setab=\E[4%p1%dm, setaf=\E[3%p1%dm, sgr0=\E[m, smacs=^N,
	smcup=\E7\E[?47h, smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m,
	smul=\E[4m, tbc=\E[3g, u6=\E[%i%d;%dR, u7=\E[6n,
	u8=\E[?1;2c, u9=\E[c,
```

(For info, here are the same result for the Parrotsec computer, on which the code is working:

echo $TERM:
```xterm```
infocmp:
```
#	Reconstructed via infocmp from file: /lib/terminfo/x/xterm
xterm|xterm-debian|X11 terminal emulator,
	am, bce, km, mc5i, mir, msgr, npc, xenl,
	colors#8, cols#80, it#8, lines#24, pairs#64,
	acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
	clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=\r,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
	cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
	dl=\E[%p1%dM, dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K,
	el1=\E[1K, flash=\E[?5h$<100/>\E[?5l, home=\E[H,
	hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
	il=\E[%p1%dL, il1=\E[L, ind=\n, indn=\E[%p1%dS,
	invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
	kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
	kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=^?,
	kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
	kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
	kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
	kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
	kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
	kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
	kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
	kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
	kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
	kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
	kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
	kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
	kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
	kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
	kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
	kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
	kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
	kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
	kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
	memu=\Em, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,
	rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B, rmam=\E[?7l,
	rmcup=\E[?1049l, rmir=\E[4l, rmkx=\E[?1l\E>, rmso=\E[27m,
	rmul=\E[24m, rs1=\Ec, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
	setab=\E[4%p1%dm, setaf=\E[3%p1%dm,
	setb=\E[4%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
	setf=\E[3%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
	sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
	smcup=\E[?1049h, smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m,
	smul=\E[4m, tbc=\E[3g, u6=\E[%i%d;%dR, u7=\E[6n,
	u8=\E[?1;2c, u9=\E[c, vpa=\E[%i%p1%dd,
```

I'm not sure this helps, but too much information cannot hurt I suppose)

**Comment by peterbrittain** [comment]
Well...  As expected, the problem is that the terminal definition on your broken system doesn't support cursor hiding (look for civis and cnorm entries).  

In addition, it would appear this is a somewhat out of date terminal type...  According to the ncurses FAQ (https://invisible-island.net/ncurses/ncurses.faq.html#xterm_color) xterm-color dates back to 1996, so I'm guessing this is a misconfiguration of your system (or a poor choice of default terminal type by the Debian distro).

Anyway, I think simply changing TERM to a more modern definition (either xterm or xterm-256color) should fix this for you.  Let me know and I'll see if there's something I can do to help others avoid this in the future.

**Comment by UplinkPhobia** [comment]
Thanks, your solution worked. Doing a simple `export TERM=xterm` or `export TERM=xterm-256color` before running the script fixed everything ^^
Not being so familiar with terminal configurations, I first thought that `xterm-color` was an "evolved" version of `xterm`, so I was quite far from the solution, even though it was relatively simple. Thanks again for your time and quick answers.
(As I don't remember any obvious way to change the terminal during the installation, I suppose that it is indeed a poor default terminal type.)
