### ISSUE TITLE
Simplified examples please

### ISSUE THREAD

**Issue by seanbayou** [peterbrittain/asciimatics#16]
Hi, I am in the process of teaching my daughter python, She loved your ascii demos and now I want to get her started on some basic ascii graphics, with a view to building up towards the more complex demos, once I understand them myself!

The problem is I am finding it quite difficult to extract basic functionality for her while hiding complexity. For example how to print out a character or string in 256 colours without invoking colour palettes etc, how to do basic key and mouse events. 

What would be ideal, is an ascii animation demo, that does not use all the built in classes you created, but more of the primitive functions, so she is learning the basics without having to go down as far as win32 calls!

I am on Windows.

I would greatly appreciate any ideas you have on this.

**Comment by peterbrittain** [comment]
Hi @seanbayou.

I'm glad your daughter liked the animations.  It was to help inspire younger programmers that I originally wrote this code!  The samples (and associated built in clases) are there to show you what is possible building up layers on top of a modest set of features provided by the Screen class.

When it comes down to it, all animations really just draw the image, wait then move it a little (maybe based on some input) and finally clear up any bits that were left behind.  All the basic drawing and input required for this is covered in the Screen class.  I would recommend that you start by reading the docs for this.  They are here: http://asciimatics.readthedocs.org/en/stable/io.html

Once you've got the basics of drawing to a given location on the Screen, the simplest thing to do is probably to animate a ball (which you could represent with the letter 'O'). To start, let's just move it along a line.  The program would be something like a call to Screen.wrapper() to get your Screen object and call your main loop.  This main loop would then:

1. Draw the ball at its current location - say (0, 0) to start.
2. Sleep for a short time - say 0.1s.
3. Clear the current location - by drawing a space character there instead.
4. Update the current location - e.g. add 1 to the x coordinate.
5. Return to the start of the loop until you hit the edge of the Screen.

Once you've got that working, you could enhance it by making it bounce back to the start by reversing the movement operation (step 4).

**Comment by seanbayou** [comment]
Thank you for this detailed reply - much appreciated. 

Is this the correct place to ask newbie questions or is there a forum or similar? In case it is ok to ask questions here are a few:

1. How do I get screen.print_at() to print a character in a specific colour out of of 256 colours? Right now only options are 0-7 and bold versions, as far as I know.

2. Can I use "screen.print_at()" to print out ASCII characters from extended ASCII table - for example box drawing characters? If not possible using "screen.print_at()" then how?

3. How do I print out unicode characters using "screen.print_at()" or other method?

**Comment by peterbrittain** [comment]
You're welcome.

Since i'm the only one on the project at the moment, this is the only forum for questions.  In answer to your latest one, you can just use the number directly.  The list of all colour indeces can be found here: https://en.m.wikipedia.org/wiki/File:Xterm_256color_chart.svg

**Comment by peterbrittain** [comment]
@seanbayou Just one final thought...  

Did you say you were running on Windows?  If so, you are limited to 16 colours (as covered here http://asciimatics.readthedocs.org/en/stable/troubleshooting.html#colours-not-working).  In this case, the best you can do is use the A_BOLD attribute to get the brighter versions of your standard 8.

**Comment by seanbayou** [comment]
Yes running on Windows. I saw the program 256colour.py and just assumed it was possible.

**Comment by peterbrittain** [comment]
Yeah - if you run that on Windows, you'll see that it does its best, but cuts down the colours to the palette available.  Is there anything else I can help with, or shall I close this issue down now?

**Comment by seanbayou** [comment]
Thanks, close this issue now. Appreciate all your help.

**Comment by peterbrittain** [comment]
Thanks.  Will do.  

BTW, I see that you are new to github...  If you like my project, please show your support by starring it.  See https://help.github.com/articles/about-stars/ for more details.
