### ISSUE TITLE
Usage questions: how to build frame with multiple layout and embedded effects

### ISSUE THREAD

**Issue by lwm** [peterbrittain/asciimatics#160]
I want to build this frame:

```
| --------------------- |
|   banner sprite       |
| --------------------- |
|   rainbow figlet      |
|   sprite              |
| --------------------  |
|  search bar widget    |
| --------------------  |
```

What I have so far:

  * One frame which takes the full size of the terminal
  * 3 layouts (one for for each section: banner, rainbow, search)

Now, I know I have access to `add_widget` for the search bar section.

But I need a 'add_effect` or something to add sprites to the two upper sections.

I saw that https://github.com/peterbrittain/asciimatics/issues/23 might be have some hints but appears to only allow an entire frame to have an embedded effect. I want to split my frame into layouts. 

I'm happy to take a stab at implementing what is needed but definitely need some guidance!

Thanks for the great library.

**Comment by lwm** [comment]
Perhaps also https://github.com/peterbrittain/asciimatics/issues/90 is related.

**Comment by peterbrittain** [comment]
Yeah - 90 would possibly be related.  Can I suggest that you just use the Effects directly and embed them in the Scene along with the Frame instead 9f putting them all inside  the Frame?

**Comment by lwm** [comment]
Aha, yes, that makes sense, I will go for that then. Closing, thanks! :+1:
