### ISSUE TITLE
Adding code quality stage to the CI

### ISSUE THREAD

**Issue by lwm** [peterbrittain/asciimatics#163]
I see you mention using pep8 in the source but don't see in the requirements?

We should add this to the Travis CI build. It helps everyone not bike shed on style :)

Personally, I use https://github.com/klen/pylama because it combines many tools.

If you're also game, I use isort too: https://github.com/timothycrosley/isort

Needs https://github.com/peterbrittain/asciimatics/pull/162 to be merged first.

**Comment by lwm** [comment]
Ah, it seems that https://stickler-ci.com/ has something to do with that!

**Comment by peterbrittain** [comment]
Sort of...  I've been using landscape.io (which runs prospector), but it's just constantly crashing now, so have been in the process of moving to a new platform.  Was hoping to keep the public facing results, so Stickler looked like a possible alternative.

**Comment by lwm** [comment]
Cool, OK, well, happy to help if can - otherwise, feel free to close here.

**Comment by peterbrittain** [comment]
I'll think about which way I want to jump.  Certainly it's no bad thing to have some clear code quality tools for developers to run themselves.

**Comment by peterbrittain** [comment]
Looks like codacy and stickler are doing the right sort of things.  Will probably retire landscape unless they start fixing their bugs soon.
