### ISSUE TITLE
PopUpDialoge() method's on_close parameter

### ISSUE THREAD

**Issue by 0p3r4t0r** [peterbrittain/asciimatics#167]
**Describe the bug**
When trying to build a menu and use the PopUpDialog() method the method's on_close parameter seems to run the function as soon as the dialog box appears rather than waiting until the user presses a button.

I've only just started using asciimatics recently so this could just be a misunderstanding on my part about the use of PopUpDialog(). I apologize in advance if this turns out to be the case. Thank you for your help and your time.

**To Reproduce**
Here is an example script that demonstrates the error.
```python3
# imports
from asciimatics.screen import Screen
from asciimatics.widgets import Frame, Layout, Label, Divider, Button, PopUpDialog
from asciimatics.scene import Scene
from asciimatics.exceptions import ResizeScreenError

from time import sleep
# END: imports

# Start Menu
class StartMenu(Frame):
    def __init__(self, screen):
        super(StartMenu, self).__init__(
        screen, screen.height//2, screen.width//2,
        has_border=True, name="Interact")

        # Create a layout.
        layout = Layout([1], fill_frame=True)
        self.add_layout(layout)

        # Populate the layout with widgets
        # Column 1
        layout.add_widget(Label('Start Menu'))
        layout.add_widget(Divider())
        layout.add_widget(Button('Play!', self._play))
        layout.add_widget(Button('Quit', self._quit))
        layout.add_widget(Button('Settings!', self._settings))

        # Need to run this to use the frame ...
        self.fix()

    # Button actions
    def _play(self):
        pass

    # Here is the quit option.
    def _quit(self):
        self._scene.add_effect(
            PopUpDialog(self._screen, "Goodbye", ['See ya!', 'Wait...'],on_close=self.test()))
   
    # Here is the function to run on close.
    def test(self):
        exit(0)

    def _settings(self):
        pass

def start_menu(screen, old_scene):
    screen.play([Scene([StartMenu(screen)], -1)], stop_on_resize=True, start_scene=old_scene)


while True:
    try:
        Screen.wrapper(start_menu, catch_interrupt=False, arguments=[None])
        sys.exit(0)
    except ResizeScreenError:
        pass
    except KeyboardInterrupt:
        exit(0)

```

What happens is that as soon as I try to open the popup dialog, the exit function is called and the program terminates.

**Expected behavior**
I was expecting the dialog box to open and then the program to terminate after the user had selected one of the options.

**System details (please complete the following information):**
 - macOS High Sierra 10.13.6 
 - Asciimatics version: 1.9.0

**Comment by peterbrittain** [comment]
You need to pass the method object rather than the result from that method. More specifically, remove the brackets from `on_close=self.test()` so that it says `on_close=self.test` instead.

**Comment by 0p3r4t0r** [comment]
Thank you for your reply and your helpful answer. Sorry to have bothered you with what turned out to be an error on my part.  ASCIIMATICS ROCKS!!

**Comment by peterbrittain** [comment]
Hey...  No problem and thanks!
