### ISSUE TITLE
FileBrowser UTF-8 issues on MacOs

### ISSUE THREAD

**Issue by mronkain** [peterbrittain/asciimatics#170]
**Describe the bug**
Some UTF-8 filenames cause either display or decoding errors in the FileBrowser widget. Certain names cause a crash on Python 2.7 with a UnicodeDecodeError. Python 3 doesn't trigger the exception but a few characters are consistently rendered incorrectly.

**To Reproduce**
Basically any filename with either any of öÖäÄ causes errors. Create a directory with files `oööÖäÄäÄ.txt,` `ØÆ.txt`, `øØæÆ.txt` and view it on the treeview sample. On Python3 the ø's and æ's are ok but the Öä's are not at all well.

On Python 2.7, the same directory causes the following exception:
```
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/asciimatics/widgets.py", line 2570, in _populate_list
    tree_files.append((["|-- {}".format(my_file),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 2: ordinal not in range(128)
```

**Expected behavior**
The filenames should be shown correctly.

**Screenshots**
On Python 3.7:
![Screenshot Python3](https://user-images.githubusercontent.com/2600875/43864819-6cfbeb62-9b69-11e8-8495-0e96b74a01e2.png)

**System details (please complete the following information):**
 - Mac Os Sierra / High Sierra
 - asciimatics 1.9.0

**Additional context**
This seems to be a known issue with the Mac HFS file system and Unicode Normalization. From the console you'll get the following:
```
Python 3.7:
>>> os.listdir('.')
['oööÖäÄäÄ.txt', 'ØÆ.txt', 'øØæÆ.txt']

Python 2.7:
>>> os.listdir('.')
['oo\xcc\x88o\xcc\x88O\xcc\x88a\xcc\x88A\xcc\x88a\xcc\x88A\xcc\x88.txt', '\xc3\x98\xc3\x86.txt', '\xc3\xb8\xc3\x98\xc3\xa6\xc3\x86.txt']`
```

**Comment by peterbrittain** [comment]
Oh the joys of OS independence...  As you say, it appears to be a common problem.

Arguably, this should be handled by the standard libraries...  Looks like this has been a can of worms, though.  See https://vstinner.github.io/python30-listdir-undecodable-filenames.html.

Oh well.  At this point I guess I'll see what I can do to detect and handle this case, then.  Will code up a patch, but don't have access to Mac, so will need your help to test.

**Comment by mronkain** [comment]
I definitely agree that this should be handled by Someone Else but it is what it is... 

Happy to help of course, just let me know.

**Comment by mronkain** [comment]
@peterbrittain The fix does wörk, the same files I've used before are now shown correctly on both p2.7 and p3.7.

**Comment by peterbrittain** [comment]
Great!  I've now merged to master.
