### ISSUE TITLE
Problem with screen.wrapper

### ISSUE THREAD

**Issue by warm-considering** [peterbrittain/asciimatics#171]
**Describe the bug**
Testing some things out and I came across an error that I couldn't figure out so I decided to run one of the example files to ensure it wasn't a problem with the library and the same exception occured. The traceback is shown below.

**To Reproduce**
I'm on arch running Python 3.7, all I did to produce the bug was run "python contact_list.py"

**Expected behavior**
I expected the program to run correctly as it is an example provided in the repo.

**Screenshots**
https://imgur.com/a/rxT62Id

**System details (please complete the following information):**
Arch Linux 4.17.14
Python 3.7.0-3
Asciimatics 1.9.0

If you need any further info please let me know.

**Comment by peterbrittain** [comment]
Looks like you're using the wrong version of asciimatics.  The `line_wrap` option is only availble in the version on github.

**Comment by warm-considering** [comment]
Thank you, that fixed my problem.
