### ISSUE TITLE
force refresh of ui

### ISSUE THREAD

**Issue by cbrown1** [peterbrittain/asciimatics#172]
I have a frame with a listbox. When the user hits a certain key on the keyboard, I update a certain item in the listbox. How do I force the UI to update to reflect the change? The code to update the listbox item is in _refresh I see `def update(self, frame_no):` in ListBox but I don't know what frame_no is. I thought it might be the index of the frame of interest in the scenes list that gets passed to screen.play, but using that doesn't seem to do anything. I have also tried setting it to 0 or some other number, but again nothing gets updated.

Any hints? Thanks, this is a very nice toolkit.

**Comment by peterbrittain** [comment]
Thanks!  I th8nk what you want is https://asciimatics.readthedocs.io/en/stable/asciimatics.html#asciimatics.screen.Screen.force_update

**Comment by cbrown1** [comment]
Thanks! How would I call it from within a frame? That is, how do I access the screen that owns a frame, from that frame?

**Comment by peterbrittain** [comment]
The `Screen` is saved off as `_screen` in all Effects, including `Frame`, so `self._screen.force_update()` should work.

**Comment by peterbrittain** [comment]
You're welcome.
