### ISSUE TITLE
SpeechBubble can't deal with asian characters.

### ISSUE THREAD

**Issue by wanicca** [peterbrittain/asciimatics#174]
Hi guys, I found a problem when I was trying to use a SpeechBubble to handle chinese characters. It was wrongly rendered. I don't know if it was because actually chinese characters are two-character-wide. Just like this: 

![image](https://user-images.githubusercontent.com/22728527/45048064-72673f80-b0ad-11e8-8d87-fb5806dbcf93.png)

If I display the text by Print (effect):
![image](https://user-images.githubusercontent.com/22728527/45050202-346d1a00-b0b3-11e8-96c8-acbebfc48b6b.png)

The first two characters were changed into 'x'. I don't know why.
Could you please help me?

**Comment by peterbrittain** [comment]
Yeah - you're right.  The double width glyphs will throw this out of alignment.  I'll have a look at this and see what I can do.

**Comment by peterbrittain** [comment]
Now working.
