### ISSUE TITLE
Use keypress to call a function without blocking?

### ISSUE THREAD

**Issue by cbrown1** [peterbrittain/asciimatics#177]
Is there a way to do this?

As is, I catch a keypress and call a function in response. The function takes a while to finish, so I want to give the user a chance to cancel by hitting another key. But if that key is pressed, it doesn't seem to be processed until the original function is finished.

**Comment by peterbrittain** [comment]
This is really a question of your application's scheduling model.  

Asciimatics will run in one thread.  It can either take control of that thread (if you use `Screen.play()`) or you can provide your own scheduling loop (using `Screen.draw_next_frame()`).  Either way, you need to use a separate thread to run your long-lived function or redesign it to be asychronous and run that within the appropriate asynchronous framework (along with asciimatics).

There are many options to help you do this sort of programming - e.g. asyncio, gevent, twisted - and asciimatics will run nicely in any of them using `draw_next_frame()` (just schedule a call to it every 0.05s).  I suggest you read some tutorials on asynchronous programming in Python and then try to rewrite your code for one of those frameworks.

**Comment by peterbrittain** [comment]
Am assuming that this answered the question.

**Comment by cbrown1** [comment]
Yes, this does answer the question. Thanks very much for the information.
