### ISSUE TITLE
New release on PyPi

### ISSUE THREAD

**Issue by vn-ki** [peterbrittain/asciimatics#178]
Please release a new version on PyPi. The last release was in Dec 2017.

There are a lot of features on master I would like to use (`line_wrap` for text, `set_theme`).

**Comment by peterbrittain** [comment]
Yeah - I've been meaning to build and test a new release for a while.  Hopefully won't be long now...

**Comment by peterbrittain** [comment]
Done!

**Comment by vn-ki** [comment]
Thank you very much for the very fast resolution of the issue.
