### ISSUE TITLE
Resize Textbox for the Text Widget

### ISSUE THREAD

**Issue by kirtansakariya** [peterbrittain/asciimatics#182]
I'm having some issues with the Text widget. I want the text box for the widget to be about 3-4 characters long but it'll default to the size of the screen. I've tried putting in empty Labels next to it to try and shrink it, but it doesn't work too well. Is there a way for me to adjust the size of the text box for the Text widget? Thanks!

**Comment by peterbrittain** [comment]
All Widgets are sized and positioned by the Layout.  If you want to reduce the width of one or more widgets, you need to place them in a column in the Layout with the desired width.  Note that this won't limit the amount of text you can enter into the box, though.

**Comment by peterbrittain** [comment]
See https://asciimatics.readthedocs.io/en/stable/widgets.html#layouts-in-more-detail for more details.

**Comment by kirtansakariya** [comment]
Alright, thanks for the help. I'll try this out!

**Comment by peterbrittain** [comment]
You're welcome.
