### ISSUE TITLE
Pasting into text widget

### ISSUE THREAD

**Issue by eykamp** [peterbrittain/asciimatics#183]
I am developing a small asciimatics app where users will need to enter a 20 character key code.  It would be far easier for them to paste this into a text box rather than manually transcribe it.  Pasting does not seem to be supported, at least on WIndows.  It would make my app much better if pasting worked.

Thanks!

**Comment by peterbrittain** [comment]
Have you tried pasting into the console window using the system menu option (or mouse context menu)?  That works for me...

For more details, see https://blogs.msdn.microsoft.com/zainnab/2010/07/21/copy-and-paste-with-the-command-prompt/

**Comment by peterbrittain** [comment]
I'm assuming that worked...  Let me know if it didn't.
