### ISSUE TITLE
Text widget - max length

### ISSUE THREAD

**Issue by kirtansakariya** [peterbrittain/asciimatics#184]
This issue is in reference with the closed issue #182.

I was able to get it to be smaller by using the layouts example that you gave me. However, the issue that I'm running into now is that while the text field is smaller, the actual label for the text field is small as well and is thus cut off. Is it possible to make the label such that all of it is shown and only make the text field smaller? I'll attach an image so it's easier to understand just what I mean. Sorry for bringing this up again, but I was just wondering if there was a work around. I've looked a bit and haven't found too much.

<img width="241" alt="screen shot 2018-11-12 at 2 04 40 pm" src="https://user-images.githubusercontent.com/9168349/48369308-2c69c180-e684-11e8-80ed-1f3f1107e21d.png">

**Comment by peterbrittain** [comment]
That's OK.  I try to keep the issue list clear, so close if there's no timely response to a possible resolution, but keep an eye on any follow up messages, so you can always reply to the old one if you're a little late.

I'm afraid that there's no control for the label size at the moment.

**Comment by kirtansakariya** [comment]
Alright, thanks.

**Comment by peterbrittain** [comment]
That doesn't mean we can't do anything...  If you can give me some more details of what you're trying to do and why it is better than what asciimatics can already do, I might be able to come up with something.

**Comment by kirtansakariya** [comment]
Alright. I'm trying to add a Text widget so that it ends up showing up like this: "Number of words: "___________. The _s are the input portion of the Text widget. However, the number of words is never going to be more than 1000. Having a bigger input field is sort of misleading for the user. In addition to that, I have another similar field where it requires the user to input a percentage. For this, I only need a field that is about 3-4 characters long. So basically, I'm trying to make it so the label for the Text field is fully visible while the input field is smaller.

I just thought of another idea but have yet to implement it. I was thinking of having a Label widget with a Text widget next to it. I just won't give the Text widget a label like "Number of words" and just have the input portion of it. Then after that I would just need to mess with the layout.

**Comment by peterbrittain** [comment]
OK...  But the vis8ble width of the field has nothing to do with what the user can enter...  Are you using a validator on these fields?

**Comment by kirtansakariya** [comment]
Yeah, I'm making sure that what the user enters is valid so them entering invalid characters isn't too big of an issue.

**Comment by peterbrittain** [comment]
OK - I'll have a think about what I can do to put a max length on test fields.

**Comment by kirtansakariya** [comment]
Thanks! That would be great.

**Comment by peterbrittain** [comment]
All done!  Now available in master...
