### ISSUE TITLE
FileBrowser filter files

### ISSUE THREAD

**Issue by kirtansakariya** [peterbrittain/asciimatics#186]
I'm trying to use the FileBrowser in order to display all `.txt` files in a directory. I was wondering if there is already a way to filter the file types. I was going to try to manually alter the list of files but it couldn't change the list. I'm wondering if it would be possible to add this feature in if it doesn't already exist?

**Comment by peterbrittain** [comment]
No - this feature is not currently available.  I'm not sure whether I'll have time for this in the near future, though.

If you're interested, it's a relatively small change to add an optional filter to `FileBrowser._populate_list` that uses a regex to determine if the file should be displayed.  I'd happily take a PR to add this.

**Comment by kirtansakariya** [comment]
I would happily work on this issue. I'll try and have a PR submitted by the end of this weekend.

**Comment by kirtansakariya** [comment]
Hi. I just started working on this and got everything installed. I was running tests to make sure I installed everything properly. However, one of the tests failed. The test for `FileBrowser` failed due to a date being off by one day. Not too sure why this happened, especially since I haven't touched anything. I will attach on image of the failed test. I'll also show which directory I'm in, if that matters.

<img width="1440" alt="screen shot 2018-11-17 at 6 54 24 pm" src="https://user-images.githubusercontent.com/9168349/48666986-41868c00-ea9a-11e8-9b3c-75770a2980fd.png">

**Comment by peterbrittain** [comment]
Possibly a difference in how macs handle the dates?  I run the tests on Linux and Windows, which all pass (as you can see from the badges)...  Or maybe it's a timezone thing and your TZ is pushing this to a different day?  Perhaps we need to set the timezone (using time.tzset) to a known location to make this work for you?

**Comment by kirtansakariya** [comment]
Yea I can try that. Thanks.

**Comment by peterbrittain** [comment]
No - some tests only run on certain platforms.

**Comment by kirtansakariya** [comment]
Hi. I just made the pull request. Please let me know if anything is unsatisfactory and I will fix it.

**Comment by peterbrittain** [comment]
#187 has implemented this.
