### ISSUE TITLE
Put a paragraph of text in a layout.

### ISSUE THREAD

**Issue by bgenchel** [peterbrittain/asciimatics#189]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example: "I'm always frustrated when [...]"

I feel that the ability to write text into one's own form is one of the most basic things someone would want to do with an interface. Just, describe what the purpose of this thing that people are looking at is. But, I don't see anything in the documentation or samples about how to do this very straightforward and simple thing.

**Describe the solution you'd like**

I would like there to be some clearly defined widget, or object, or whatever that just allows me to write un-editable text into a frame. I just want to write text. Into a frame.

**Describe alternatives you've considered**

**Additional context**

**Comment by peterbrittain** [comment]
Thanks for raising this.  Can you please be a little more specifc, though.  For example have you tried either of the following and, if so, what was wrong with that approach?

1) A multi-line Label - see https://asciimatics.readthedocs.io/en/stable/asciimatics.html#asciimatics.widgets.Label
2) A disabled Textbox - as explained here: https://asciimatics.readthedocs.io/en/stable/widgets.html#disabling-widgets

You can see an example of option 2 in https://github.com/peterbrittain/asciimatics/blob/master/samples/top.py.

**Comment by peterbrittain** [comment]
I've added some extra text to the latest docs to make this more explicit.  Will close if I hear nothing else from you, so please let me know if you need anything else.

**Comment by peterbrittain** [comment]
Assuming these worked.  Feel free to reply if it's still an issue.

**Comment by bgenchel** [comment]
hi @peterbrittain thanks for the tip! The multiline label did the trick! Couldn't figure out a way to vertically center the text, but that's not as big of a deal. Thanks for your great work!!!
