### ISSUE TITLE
Asciimatics pauses for a long time when time changes

### ISSUE THREAD

**Issue by storezhang** [peterbrittain/asciimatics#190]
1. use subprocess call timedatectl set-time "xxxx-xx-xx xx:xx:xx"
2. popup a PopUpDialog
3. press Enter key
4. PopUpDialog can not process the event

PS: press CTRL + C and then PopUpDialog will process the event correctly

**Comment by peterbrittain** [comment]
Sorry, but I can't reproduce this.  For example, if I use this patch to forms.py, the dialog pops up as expected when I press the "View Data" button and I can press Enter to dismiss the dialog.

```
--- forms.py	2018-11-26 12:31:46.117934674 +0000
+++ bug_test.py	2018-11-27 09:40:12.592189170 +0000
@@ -6,6 +6,7 @@
 from asciimatics.screen import Screen
 from asciimatics.exceptions import ResizeScreenError, NextScene, StopApplication, \
     InvalidFields
+import subprocess
 import sys
 import re
 import datetime
@@ -161,16 +162,7 @@
         raise NextScene()
 
     def _view(self):
-        # Build result of this form and display it.
-        try:
-            self.save(validate=True)
-            message = "Values entered are:\n\n"
-            for key, value in self.data.items():
-                message += "- {}: {}\n".format(key, value)
-        except InvalidFields as exc:
-            message = "The following fields are invalid:\n\n"
-            for field in exc.fields:
-                message += "- {}\n".format(field)
+        message = subprocess.check_output(["timedatectl"])
         self._scene.add_effect(
             PopUpDialog(self._screen, message, ["OK"]))
```

Can you please send me a more detailed bug report - e.g. using Bug Template (https://github.com/peterbrittain/asciimatics/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) to help me understand the problem better?  At a minimum, since it doesn't reproduce for me, you need to send me a simple standalone application that shows the error.

**Comment by storezhang** [comment]
replace `message = subprocess.check_output(["timedatectl"])` with `message = subprocess.check_output(["timedatectl", "set-time", "2018-11-11 00:00:00"])` and test it

thanks

**Comment by peterbrittain** [comment]
Sorry, but that all works for me and I've just done it 30 times in a row.  

I'm guessing that your sub-process simply hasn't ended and so when you press Ctrl-C, you're killing the sub-process.  You may want to check that.

**Comment by peterbrittain** [comment]
I assume that analysis was right given the sudden silence...  Will leave open for a little longer just in case.

**Comment by peterbrittain** [comment]
OK - I've got it.  The difference is that you're not using the new logic to allow keyboard interrupts, so when you change the time to something in the past, asciimatics tries to figure out how long it should wait for the next refresh and this is a long time.

Quick fifx for you today is to pass `allow_int=True` to `Screen.play()`.  I'll code up a patch to this issue later.

**Comment by storezhang** [comment]
The reason I didn't use the allow_int parameter is because of this output: TypeError: play() got an unexpected keyword argument 'allow_int', asscimatis version is 1.10.0

**Comment by peterbrittain** [comment]
That's because it's only available on master right now.  If you can't wait for the next public release, you can always build your own or install direct from guthub.  

See https://stackoverflow.com/questions/8247605/configuring-so-that-pip-install-can-work-from-github

**Comment by storezhang** [comment]
I can't install the latest code on the master branch, because the company's internal machines can't connect to the network, so can you update the version on pip as soon as possible, thanks.

**Comment by storezhang** [comment]
resolved, thanks!
