### ISSUE TITLE
the latest code can not display chinese string

### ISSUE THREAD

**Issue by storezhang** [peterbrittain/asciimatics#191]
**Describe the bug**
With any Chinese character, the string is displayed as blank on any control.

**To Reproduce**
modify form.py
replace 
`    def _quit(self):
        self._scene.add_effect(
            PopUpDialog(self._screen,
                        "Are your sure quit?",
                        ["Yes", "No"],
                        has_shadow=True,
                        on_close=self._quit_on_yes))`
with
`    def _quit(self):
        self._scene.add_effect(
            PopUpDialog(self._screen,
                        "确定退出吗？",
                        ["是的", "不退出"],
                        has_shadow=True,
                        on_close=self._quit_on_yes))`

**Expected behavior**
Chinese characters should be displayed in the popup

**Screenshots**
If applicable, add screenshots or cut and paste the erroneous text to help explain your problem.
![image](https://user-images.githubusercontent.com/4278758/49223364-8525b200-f419-11e8-909c-278bc17962c4.png)

**System details (please complete the following information):**
 - OS and version: Deepin Linux 15.8 Desktop x64
 - Asciimatics version: 1.10.1.dev38+g4bcd2cd

**Additional context**
None

**Comment by peterbrittain** [comment]
Yeah - looks like I broke this with some recent optimizations that are only in master...  just a min.
