### ISSUE TITLE
Label widget can not wrap when using chinese

### ISSUE THREAD

**Issue by storezhang** [peterbrittain/asciimatics#192]
**Describe the bug**
With the Label control, if Chinese characters are used, when the characters are too long, the Label cannot be displayed in a new line. However, if you use English characters, you can automatically wrap.

**To Reproduce**

1. create a new Label widget and set label is "这是一个很长的标签控件！这是一个很长的标签控件！这是一个很长的标签控件！这是一个很长的标签控件！这是一个很长的标签控件！这是一个很长的标签控件！这是一个很长的标签控件！这是一个很长的标签控件！这是一个很长的标签控件！这是一个很长的标签控件！这是一个很长的标签控件！这是一个很长的标签控件！这是一个很长的标签控件！这是一个很长的标签控件！"
2. startup app and watch display

**Expected behavior**
Any character (including Chinese characters, English characters) should be automatically wrapped when the string is too long.

**Screenshots**
Can't take screenshots, the current version of asciimatics can't display Chinese characters, it can be reproduced on the company's computer, but the company's computer can't connect to the Internet (I don't know the company is fucking delusion), so you need to repeat it yourself. Now it’s time.

**System details (please complete the following information):**
 - OS and version: CentOS 7
 - Asciimatics version: 1.10.0

**Additional context**
use this code to test: https://github.com/storezhang/asciimatics/blob/master/bug/app.py

**Comment by peterbrittain** [comment]
Yeah - The logic for wrapping at the moment relies on breaking on white space.  However, it looks (to my Western eyes) that there is no white space in that label.  

Is it sufficient if I just force the breaks on any arbitrary character when the line is too long to fit?

**Comment by storezhang** [comment]
I can use a mobile phone to take a picture that can't be changed on the phone tomorrow. You can see it again. I am at home now, because the company's computer can't connect to the external network (for company policy reasons, the project is top secret, and the source code is leaked), so now Unable to provide an image that cannot be wrapped.

**Comment by peterbrittain** [comment]
Don't worry about the screenshot.  My question is actually about how to handle Chinese writing...  Is there an equivalent to white space that I should also be looking to use to break up the string, or can asciimatics just decide that it needs to be N characters wide and so slice the string every N characters?

**Comment by storezhang** [comment]
Conceptually, a Chinese character needs two English characters to display, but I'm not sure. You can try it.

**Comment by Zireael07** [comment]
@peterbrittain: Han characters are known as "wide characters", in that they need more than 1 byte. I'm not sure, though, whether they are always 2 bytes. You should probably look into how Python handles Unicode.

**Comment by peterbrittain** [comment]
Yeah - I'm very familiar with the vagaries of the double-width characters.  That's all fine.  

What I need is for you (as a native Chinese speaker) to explain how I should divide up written words in Chinese.  Ignore all the terminal issues for a sec and just tell me how you'd like to see this string formatted (and the logic you used to get there).  For example, can I just make it look like this:

这是一个很长的标签控件！这是一个很长的标签控件！这是一个
很长的标签控件！这是一个很长的标签控件！这是一个很长的标
签控件！这是一个很长的标签控件！这是一个很长的标签控件！
这是一个很长的标签控件！这是一个很长的标签控件！这是一个
很长的标签控件！这是一个很长的标签控件！这是一个很长的标
签控件！这是一个很长的标签控件！这是一个很长的标签控件！

**Comment by storezhang** [comment]
@peterbrittain yes, Very right, just show it like that.
![image](https://user-images.githubusercontent.com/4278758/49227603-6842ac00-f424-11e8-875c-a929b68671f4.png)

**Comment by peterbrittain** [comment]
OK - I've just added some logic that simply splits on width if there is no white space.  

(I also found another bug in the new colour themes that I've fixed at the same time in case you're wondering about the extra changes).

**Comment by peterbrittain** [comment]
Yes - the other issue with master that you raised as #191 was also a bug, but that is also now fixed (by the other patch linked to that issue).  Just take master now and you should be fine.
