### ISSUE TITLE
Image rendering in documentation ?

### ISSUE THREAD

**Issue by buxx** [peterbrittain/asciimatics#195]
Hello !
In documentation introduction i can read the following:

> Image to ASCII conversion - including JPEG and GIF formats

But i can't find documentation about it. How use this feature ?
Thank's.

**Comment by peterbrittain** [comment]
Hmmm...  So I haven't created an explicit link.  Will fix that!  In the meantime, you want to look at:

https://asciimatics.readthedocs.io/en/stable/asciimatics.html#asciimatics.renderers.ColourImageFile
https://asciimatics.readthedocs.io/en/stable/asciimatics.html#asciimatics.renderers.ImageFile
https://github.com/peterbrittain/asciimatics/blob/master/samples/images.py

**Comment by buxx** [comment]
Big thank's !
