### ISSUE TITLE
Please push source distribution to Pypi

### ISSUE THREAD

**Issue by CMCDragonkai** [peterbrittain/asciimatics#198]
Please upload the source distribution to PyPi as well. It's improtant for distros that prefer source based distribution. https://github.com/NixOS/nixpkgs/pull/54404

**Comment by peterbrittain** [comment]
OK - I think I've done it...  The sdist is now listed here: https://pypi.org/project/asciimatics/#files

**Comment by CMCDragonkai** [comment]
Thanks, I've changed over.
