### ISSUE TITLE
add callback method when frame display

### ISSUE THREAD

**Issue by storezhang** [peterbrittain/asciimatics#201]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example: "I'm always frustrated when [...]"

**Describe the solution you'd like**
When the frame is displayed, add a callback method. In the callback method, I can display the latest interface (this interface may be generated by various logics, and the display may be different each time)

**Describe alternatives you've considered**

**Additional context**

**Comment by peterbrittain** [comment]
I'm sorry, but I don't quite understand this request yet...  Are you asking for a new `on_update` property to be added to the `Frame` class?  The idea being that this is a new callback which is called by the `Frame` whenever `Frame.update()` runs.

If so, why?  The Frame itself does very little in the way of drawing and relies on the `Layout` and `Widget` classes to actually draw any real content on the `Canvas`.  By using an `on_update` callback that draws to the `Canvas`, you will potentially clash with that existing logic in the other classes.

It seems to me that a better option is to create your own custom `Widget`.  This will be called by the `Frame` whenever it needs updating and (assuming you code it up to conform to the API), it will work well with the controlling `Layout`.  Can you please explain why this solution isn't appropriate?

**Comment by peterbrittain** [comment]
S8nce there has been no response, I assume that solution worked and so will update the docs to explain these sorts of options better.

**Comment by peterbrittain** [comment]
Now done.
