### ISSUE TITLE
Ability to use screen wrapper as decorator

### ISSUE THREAD

**Issue by GammaGames** [peterbrittain/asciimatics#203]
**Is your feature request related to a problem? Please describe.**
I think it would be handy to have methods to use the screen without manually creating one or using `Screen.wrapper(func)`. I designed my solution based on Pony's [`db_session`](https://docs.ponyorm.org/firststeps.html#db-session) decorator works, so you can also use it with the `with` statement.

**Describe the solution you'd like**
My solution is this class:
```python3
class screen_session():
    def __init__(self, func=lambda: None):
        self.func = func
    def __call__(self, *args, **kwargs):
        screen = Screen.open()
        kwargs["screen"] = screen
        output = self.func(*args, **kwargs)
        screen.close()
        return output
    def __enter__(self):
        self.screen = Screen.open()
        return self.screen
    def __exit__(self, type, value, traceback):
        self.screen.close()
```
You can use it a couple different ways, either as a decorator (`screen=None` is to prevent pylint errors):
```python3
@screen_session
def demo(screen=None):
    screen.print_at('Hello world!', 0, 0)
    screen.refresh()
    sleep(3)

demo()
```
Or the `with` statement:
```python3
def demo():
    with screen_session() as screen:
        screen.print_at('Hello world!', 0, 0)
        screen.refresh()
        sleep(3)

demo()
```

**Additional context**
I don't have a lot of experience with decorators, so I'm not sure if there's an easier way to inject variables into the method's scope without including it in the kwargs. I also tried using the regular `Screen.wrapper` as a decorator and couldn't get it to work.

**Comment by peterbrittain** [comment]
That looks  great!  

Would you like to submit a pull request for that (and maybe add a test that uses the decorator to prove that it works)?

**Comment by GammaGames** [comment]
I did have to play with it a little (with help from stackoverflow) to get the decorator to work with regular methods and class methods:

```python3
class screen_session():
    def __init__(self, func=lambda: None):
        update_wrapper(self, func)
        self.func = func
    def __get__(self, obj, objtype):
        return partial(self.__call__, obj)
    def __call__(self, *args, **kwargs):
        screen = Screen.open()
        kwargs["screen"] = screen
        output = self.func(*args, **kwargs)
        screen.close()
        return output
    def __enter__(self):
        self.screen = Screen.open()
        return self.screen
    def __exit__(self, type, value, traceback):
        self.screen.close()
```

With this change the original demos as well as the following work:

```python3
class MyScreen():
    @screen_session
    def demo1(self, screen=None):
        screen.print_at('Class Demo 1!', 0, 0)
        screen.refresh()
        sleep(3)

    def demo2(self, screen=None):
        with screen_session() as screen:
            screen.print_at('Class Demo 2!', 0, 0)
            screen.refresh()
            sleep(3)

m = MyScreen()
m.demo1()
m.demo2()
```

**Comment by GammaGames** [comment]
I also don't know how backwards compatible it is with python2, I personally don't ever use it (especially with support ending soon) ¯\\\_(ツ)_/¯

**Comment by GammaGames** [comment]
You can even use it like this:

```python3
@screen_session
class MyScreen():
    def __init__(self, screen=None):
        self.screen = screen
        self.demo()

    def demo(self):
        screen.print_at('Class Demo 1!', 0, 0)
        screen.refresh()
        sleep(3)

MyScreen()
```
But that seems to only work if you call the printing methods inside `__init__`, so you're probably just better off not using it as a decorator and using `with` or manually opening and closing the scene.  
It would be nice to automatically open the screen when the class is instantiated and close the screen when the object is destroyed, but destructors aren't nice in python so I can't figure out how to get that working.

**Comment by peterbrittain** [comment]
Yeah - I'm not so keen on that last option with the restrictions on what you can/can't do inside each method.

Testing is easy.  Just put your code to use the screen_session in test_screen.py and assert that the screen buffer contains the expected output.  You can use `test_cjk_glyphs_overwrite()` as a template for the basic idea.  Once you've got it working on your machine, push the branch to github and the Travis CI pipeline will test it on bother versions of Python for you.

**Comment by peterbrittain** [comment]
Now added - much thanks!
