### ISSUE TITLE
Get if key is down/pressed

### ISSUE THREAD

**Issue by matcool** [peterbrittain/asciimatics#205]
Currently `screen.get_event()` only returns a KeyboardEvent if the key has just been pressed or is repeating. Is there any way to get if an key is down / pressed?

**Comment by peterbrittain** [comment]
Unfortunately, Linux TTY sessions don't allow this.  They only notify applications once a key has been pressed (or repeated).  Trying to work around this is very complex (e.g. looking for the X subsystems or accessing the keyboard device directly) and only works when the session is running locally.

Even if I had the time to code that up, it would still fail the mainline case of running your application using a telnet or ssh service.  And, sadly, this is not possible to fix without a radical redesign of the OS.

There's a good write up of the issues in http://blog.robertelder.org/detect-keyup-event-linux-terminal/

**Comment by matcool** [comment]
Thanks for the help! I'll just end up using this external [keyboard](https://pypi.org/project/keyboard/) module.

**Comment by peterbrittain** [comment]
Yeah - that looks like a good package if you just want local keyboard access.
