### ISSUE TITLE
Allow adding themes

### ISSUE THREAD

**Issue by jabdoa2** [peterbrittain/asciimatics#207]
**Is your feature request related to a problem? Please describe.**
Currently there is no sane way to add themes. Please provide a way to add color themes.

**Describe the solution you'd like**
I would like some class to call like this:
```
Themes.add_theme("jans_theme", my_theme)
```

**Describe alternatives you've considered**
Currently I can only use this hack:
```
from asciimatics.widgets import Frame, Layout, Text, Label, _split_text, _THEMES
        _THEMES["jans_theme"] = defaultdict(
        lambda: (Screen.COLOUR_WHITE, Screen.A_NORMAL, Screen.COLOUR_BLACK),
        {
            "invalid": (Screen.COLOUR_BLACK, Screen.A_NORMAL, Screen.COLOUR_RED),
            "label": (Screen.COLOUR_WHITE, Screen.A_NORMAL, Screen.COLOUR_BLACK),
            "title": (Screen.COLOUR_WHITE, Screen.A_NORMAL, Screen.COLOUR_RED),
            "selected_focus_field": (Screen.COLOUR_WHITE, Screen.A_BOLD, Screen.COLOUR_BLACK),
            "focus_edit_text": (Screen.COLOUR_WHITE, Screen.A_BOLD, Screen.COLOUR_BLACK),
            "focus_button": (Screen.COLOUR_WHITE, Screen.A_BOLD, Screen.COLOUR_BLACK),
            "selected_focus_control": (Screen.COLOUR_WHITE, Screen.A_BOLD, Screen.COLOUR_BLACK),
            "disabled": (Screen.COLOUR_BLACK, Screen.A_BOLD, Screen.COLOUR_BLACK),
        })
```

**Additional context**
Please also raise an error when using ```set_theme``` on a Frame for a theme which does not exist.

**Comment by peterbrittain** [comment]
I'm not sure I need a separate class.  All we need is a dictionary of palettes that developers can update.  My gut reaction is therefore just to expose the existing dict as `THEMES` instead (and formally document it as a supported object).  

Is there anything else you need that would warrant the separate class instead?

**Comment by jabdoa2** [comment]
As long as it is an official API I'm fine with that.
