### ISSUE TITLE
Support Popups without buttons

### ISSUE THREAD

**Issue by jabdoa2** [peterbrittain/asciimatics#209]
**Is your feature request related to a problem? Please describe.**
PopupDialogs currently always add two layouts. One for the text and one for buttons. This does not look very nice when not using any buttons.

**Describe the solution you'd like**
Please omit the second layout when not providing buttons.

**Describe alternatives you've considered**
Passing an empty list of buttons works but add two empty lines to the end of the message.

**Comment by peterbrittain** [comment]
I'm not quite sure about this request...  Can you explain how you would use such a Dialog?  In particular, why allow a dialog that can't be dismissed (because there are no buttons to close it)?

**Comment by jabdoa2** [comment]
Our example is "Waiting for client to connect" or "Waiting to load assets". This are status messages mostly but the UI cannot be used until this is finished.

**Comment by peterbrittain** [comment]
Oh...  I see.  You deliberately don't want the user to be able to enter anything and will dismiss it yourself when the program is ready.  OK.  That makes sense.
