### ISSUE TITLE
Allow clearing or replaying of a Layout

### ISSUE THREAD

**Issue by jabdoa2** [peterbrittain/asciimatics#210]
**Is your feature request related to a problem? Please describe.**
We got one layout which shows a bunch of stats. However, stats may be added/removed during runtime. Unfortunately, we cannot currently update a layout besides added widgets to the end of a column.

**Describe the solution you'd like**
Allow clearing all/one columns in a layout. Workaround:

```
class MpfLayout(Layout):

    """Add clear function."""

    def clear_columns(self):
        """Clear all columns."""
        self._columns = [[] for _ in self._columns]
```

**Describe alternatives you've considered**
Alternatively, we would have to create a new Frame everytime this happens. Instead, we would like to just put all widgets into a list, clear the layout and add all the widgets from our list. Another option would be to allow replacing/removing layout from Frames.

**Comment by peterbrittain** [comment]
Sounds like you might want to use a ListBox or Multicolumn equivalent for these stats.  The top demo does something similar and might be a good template.

That said, some symmetry on the API for updating the widgets is no bad thing.  I'll have a think about that...

**Comment by jabdoa2** [comment]
That might work for one case. In the other case we color the labels based on the state which might be tricky with those widgets.

**Comment by peterbrittain** [comment]
Yeah - I've been working towards custom coloured text objects for any widget, but not got anything ready for general use there.  For now separate widgets are the only option.
