### ISSUE TITLE
Push 1.11.0 to Pypi

### ISSUE THREAD

**Issue by jabdoa2** [peterbrittain/asciimatics#212]
Would it be possible to push 1.11.0 to pypi? It seems to fix a few bugs and we would like to ship it to our users. Additionally, the docs recommend to use at least 1.11 ;-).

**Comment by peterbrittain** [comment]
Yeah - I wait until there are enough enhancements to warrant a new release.  Feels like we're there again.

I'd like to look at your recent issues first, though.  Probably looking ata couple of weeks right now.

**Comment by peterbrittain** [comment]
Done!

**Comment by jabdoa2** [comment]
Thanks! We will start shipping it soon.

**Comment by peterbrittain** [comment]
You're welcome!  It was about time I did it again, so the nudge was appreciated.
