### ISSUE TITLE
Tests fail on openSUSE Python 2 and 3

### ISSUE THREAD

**Issue by jayvdb** [peterbrittain/asciimatics#216]
**Describe the bug**
A large number of tests fail on Python 2.7 & 3.7 .  I have confirmed that Python 3.7 works on Travis.

**To Reproduce**
The OBS project at https://build.opensuse.org/package/show/home:jayvdb:py-wheels/python-asciimatics has a .spec which makes this very reproducible.

Build log for openSUSE tumbleweed amd64, which includes the Python 2.7 errors:

[_log.txt](https://github.com/peterbrittain/asciimatics/files/3153645/_log.txt)

I've run the same locally on my machine with pytest and it also fails.

**Expected behavior**
Tess pass.

**System details (please complete the following information):**
 - openSUSE (all versions)
 - Asciimatics 1.10.0

**Comment by peterbrittain** [comment]
OK - running through the log file, I see that you have 2 different errors:

1. `curses.cbreak()` is not working.  I've never seen that before and have run on multiple distros now...  If I had to guess it is either that you are using a bad terminal definition (as defined by your TERM env variable), or that this test isn't running with a TTY.
2. Image rendering is returning a slightly different result.  This happens if you don't pin Pillow to the required version listed in `dev.txt` (3.3.1).

**Comment by jayvdb** [comment]
Thanks.  I assumed it was something to do with the TERM env var, but was hoping for a magic remedy.  I'll debug a little and come back if I need more help.

We dont get to pin Pillow in openSUSE rpms -- that varies, and is updated constantly on the Tumbleweed rolling release.
Is that a bug in asciimatics, or is it simply the test results vary for each Pillow version?  If the later, it sounds like a good reason for that specific test to be disabled.  I can manually disable it, or the tests here could detect the wrong Pillow version and skip the test with a note.

**Comment by peterbrittain** [comment]
Pillow's dithering logic changed at various points.  This changes the output of the image rendering.  Asciimatics is fine, the test should be disabled.

For the other issue, picking a standard xterm terminal should work (even if you're not using that terminal) as long as it is just a bad TERM setting.

**Comment by jayvdb** [comment]
TERM is `vt220` on these CI workers.  I've tried explicitly adding terminfo - still red

**Comment by jayvdb** [comment]
I've tried TERM = linux, vt100 and vt102 - all failing with the `curses.cbreak()` problem. (I havent bothered disabling the Pillow test yet)

**Comment by peterbrittain** [comment]
Hmmmm...  Are you sure that build has a TTY?

**Comment by peterbrittain** [comment]
I've just checked the various terminal types you used on my system and most are so old and minimal that they don't support the full curses API.  However, the linux option worked fine on my CentOS box, so I suspect that it really is a lack of a TTY.

We hit this before in https://github.com/peterbrittain/asciimatics/issues/199, but when I just check for a true TTY, it stops a load of tests on Travis that I want to keep active for the master repo.  That said, I'd be happy to have some sort of environment flag instead to disable these failing tests for your builds.

**Comment by jayvdb** [comment]
Skipping them in the build environment is an option, but I am getting the same/similar errors also locally on my own machine, which is a real xterm.

I'll re-run more carefully on my machine and report back results.  And I'll use master, as it has sounds like it has fixes not in the latest release.

**Comment by jayvdb** [comment]
On my machine, using master, I was using pytest.  Unfortunately, the output fiddles with the tty, and I cant get the normal pytest error output - only one of the error backtraces is visible, and only partially.
```
> python2.7 -m pytest
========================================================================== test session starts ===========================================================================
platform linux2 -- Python 2.7.16, pytest-3.10.1, py-1.8.0, pluggy-0.9.0
rootdir: /home/jayvdb/projects/python/asciimatics, inifile:
collected 144 items

tests/test_effects.py ...............F.                                                                                                                            [ 11%]
tests/test_events.py ..                                                                                                                                            [ 13%]
tests/test_exceptions.py ..                                                                                                                                        [ 14%]
tests/test_particles.py ........                                                                                                                                   [ 20%]
tests/test_paths.py ....                                                                                                                                           [ 22%]
tests/test_renderers.py ...F....F...F..F.                                                                                                                          [ 34%]
tests/test_scene.py ....                                                                                                                                           [ 37%]
tests/test_screen.py FF.FFF.FFFFFFFFFFFFFFFFFF.FFFFFFFFF                                                                                                           [ 61%]
tests/test_sprites.py .                                                                                                                                            [ 62%]
tests/test_utilities.py ..                                                                                                                                         [ 63%]
tests/test_widgets.py ....................................................                                                                                         [100%]
```

Re-running on only test_renderers.py, I can get the following

```
            # Enable mouse input, disable quick-edit mode and disable ctrl-c
            # if needed.
            in_mode = win_in.GetConsoleMode()
            new_mode = (in_mode | win32console.ENABLE_MOUSE_INPUT |
                        ENABLE_EXTENDED_FLAGS)
            new_mode &= ~ENABLE_QUICK_EDIT_MODE
            if catch_interrupt:
                # Ignore ctrl-c handlers if specified.
                new_mode &= ~win32console.ENABLE_PROCESSED_INPUT
            win_in.SetConsoleMode(new_mode)

            screen = _WindowsScreen(win_out, win_in, height, old_out, in_mode,
                                    unicode_aware=unicode_aware)
        else:
            # Reproduce curses.wrapper()
            stdscr = curses.initscr()
            curses.noecho()
>           curses.cbreak()
E           error: cbreak() returned ERR

asciimatics/screen.py:1294: error
================================================================== 4 failed, 13 passed in 0.99 seconds ==========
```

On CI, I was using `python setup.py test`.

When I use `python -m nose`, those problems all become skips, except for the Pillow problem, which I can patch.

I shouldnt have expected that pytest would work, but I would expect `python setup.py test` would either fail completely, or have the same results as `python -m nose`.

**Comment by jayvdb** [comment]
I spoke too quickly.

On CI, the zSystems/s390x job is green, the problematic set of tests are skipping nicely, and only 'test_image_files' is explicitly skipped on the nose command line.
https://build.opensuse.org/package/live_build_log/home:jayvdb:py-wheels/python-asciimatics/openSUSE_Factory_zSystems/s390x

However other platforms and versions of openSUSE are all still failing, with nose.

On my machine, with master and with v1.10.0, test_colour_image_file, test_uni_image_files and test_image_files all fail, due to the Pillow output.

**Comment by peterbrittain** [comment]
Your test on your personal machine is exactly what I'd expect when running with a good TERM variable on a live terminal (i.e. with a TTY), but the wrong version of Pillow.  I think this shows that it's not an issue with openSUSE as such and just the specific environment for the CI systems.

I bet if you apply this PR (https://github.com/peterbrittain/asciimatics/pull/200), it will skip all of the offending failures apart from the Pillow related ones.  I guess I could pull that with an extra hoop in my CI settings to set a flag to ignore the TTY check in order to keep my coverage up.  Then you could just skip these tests in your builds by not setting that flag (assuming you have your own separate CI config).

**Comment by jayvdb** [comment]
Applied patch for pr 200, and everything is suddenly green, so I have submitted it https://build.opensuse.org/request/show/701665 .  We have a .spec, so we can do almost anything to skip these tests once you choose the method you want to use.

**Comment by peterbrittain** [comment]
OK - I think that I've updated the travis builds to force the use of TTY related tests, but will generally disable them for any dodgy looking TTY in any other case.  This was pushed as #200
