### ISSUE TITLE
Not working on repl.it

### ISSUE THREAD

**Issue by extremepayne** [peterbrittain/asciimatics#217]
**Describe the bug**
The example program doesn't run in a [repl](repl.it).

**To Reproduce**
1. Make a new [repl](repl.it)
2. Copy the example program into main.py
3. Add asciimatics to a file called requirements.txt
4. Press the button labeled "run"
5. Click on the terminal window to grab input to the terminal rather than the coding area
6. Press the q key

**Expected behavior**
I expected the example program to run (which it did) and then exit gracefully instead of crash upon hitting q to exit.

**Screenshots**
![image](https://user-images.githubusercontent.com/46696318/58187311-c33aba80-7c73-11e9-87c2-b449d6fcc4f8.png)

**System details**
 - Chrome OS version 74.0.3729.125
 - Asciimatics version 1.11.0

**Other**
I'm using repl because I'm on a chromebook that doesn't support linux apps.

**Comment by peterbrittain** [comment]
Interesting.  This is hitting an issue with resetting the signal handlers back to what they were before you ran the code.  I'm going to guess it has returned None and doesn't like that being set.

**Comment by peterbrittain** [comment]
Yeah - running in reply it looks like the SIGWINCH handler is None.  I'm not sure that you there is a good solution here.  Best we can do is reinstate the Python default, which is strictly speaking wrong.

**Comment by peterbrittain** [comment]
I can code up a workaround, but that probably means any resize handling in repl.it will stop working.

**Comment by peterbrittain** [comment]
I haven't been able to test on repl.it, but this change handles the relevant case.

**Comment by extremepayne** [comment]
Hmmm... I don't believe I can test it either, at least until the patch is included in a PyPI release, but it looks like that should help. Thanks!
In the meantime, I can try this out on a real terminal 🙂
