### ISSUE TITLE
Add vertical separators to multicolumnlistbox

### ISSUE THREAD

**Issue by tsgiannis** [peterbrittain/asciimatics#223]
Hello, great project
I was thinking, how about something like a listview ...i know that the treeview is pretty close (and great) but it would be great if we could have something like dos commander style

**Comment by peterbrittain** [comment]
Thanks.

Can you explain how you see dos commander is different from what you could do with the existing listbox (and other variants)?

**Comment by tsgiannis** [comment]
If you have an example with a listview alike please let me know...i just run most of the examples and maybe i missed it

**Comment by peterbrittain** [comment]
Once again, many thanks...  It's nice to be appreciated!

I'm afraid that I still don't understand your suggestion, though.  The treeview sample shows how you can use the `FileBrowser` widget to create a simple file selection program.  That widget is completely reusable and can be embedded in a `Frame` like any other widget.  It's therefoe just a matter of creating a `Frame` with 2 `FileBrowser` widgets in it side by side to get the same effect as your screenshot.

If you want a little more separation between the two, you could use a `VerticalDivider` between them.  To get a box around the whole lot, simply construct the `Frame` with a border.

What's missing from that design?

**Comment by tsgiannis** [comment]
Thanks for the prompt response.. i must confess i haven't delved much in your platform...lets say i come from other platforms and Python is a new ground for me.
Let me elaborate on this...
For now i am building an application that parses and manipulate .csv...this in the future probably it will expand in a much "wider" range of datasources...but for now lets assume that the main data source is .csvs.
Now the issue with these .csvs is that i need a first look at them...eg. list the first 50 rows to get an idea on they are about and then lets say they are "separated" in multiple columns...in these multiple columns i need to select which will be further processed and which are going to get skipped.
To get an idea of the control just take a look here (for something simple):https://gramha.net/media/2106277559049371362
Now i don't know in what degree it is possible to emulate its "appearance" (although your platforms really does wonders) but it would be just great for data operations.
Also a small addition...is it possible to have a menu like system like this : http://gnosis.cx/publish/programming/cp6s.gif
Thanks again

**Comment by peterbrittain** [comment]
If all you need to do is display data in columns, look at `MultiColumnListBox`.  The top.py demo uses this widget to display process data that would be similar to CSV files..

From the sounds of things, you could either put this next to the `FileBrowser` widget in the same Frame, or embed it in a new Frame that you display when a file is selected.  You can look at contact_list.py for an example of how to switch between views.

Menus like your screenshot don't exist yet.  They are on the back burner for now.  At the moment, all you can do is pop-up menus (which are a bit like context menus on right clicks in GUI environments).  See forms.py for an example.

**Comment by tsgiannis** [comment]
Thanks man.

**Comment by peterbrittain** [comment]
Nothing in the existing code... Could be added as an option for drawing a delimiter, though.

Should be arelativelyeasy change, if you'd like to make it, though.  Just make it force a space between each column when a delimiter is provided andprint that instead of the space character.

**Comment by tsgiannis** [comment]
Ok ...putting the pipe delimiter to act as line representation was my 1st thought....curious how real lines are drawn....anyway you got me covered.

**Comment by peterbrittain** [comment]
Line drawing (to create vertical and horizontal lines) is part of the extended unicode character set.  Check out the characters used to create the Frame border.

**Comment by tsgiannis** [comment]
Extended Unicode character set ...great...this should be all..thanks again..you are a lifesaver

**Comment by peterbrittain** [comment]
You're welcome!  If you do add the vertical lines, I'd be happy to review a PR to add that option...

**Comment by tsgiannis** [comment]
Probably you will beat as i move very slow..this is my pet project...but if i make any progress i will give you a message.

**Comment by peterbrittain** [comment]
OK - now that we've reached a conclusion, I've updated the issue.  I reckon this is a good one to get people started with the code, so will leave it for others for now...

**Comment by tsgiannis** [comment]
Hopefully someone will jump in... :)

**Comment by edoffagne** [comment]
I can have a look at this one. I assume the goal is to modify `MultiColumnListBox` to take an extra argument to allow adding vertical lines (ASCII 179 character).
Do we want to only add vertical line or let user choose what character to use for delimiting columns ?

**Comment by peterbrittain** [comment]
Your help is much appreciated!  

Yeah - I was thinking we just add a single extra optional parameter that specifies the separator character to use, which defaults to the current logic when omitted.

In theory, this is just a question of reworking the existing logic to add extra space between certain columns so that it always adds the separator character instead.

**Comment by edoffagne** [comment]
Ok that makes sense for the additional parameter.
I plan to change the logic in `_print_cell` so that `buffer_1` or `buffer_2` will have the character to delimitate the column.

**Comment by peterbrittain** [comment]
That's the logic for aligning the content, not the logic that adds the extra space.  Take a look at the code that uses the `space` parameter instead.

**Comment by edoffagne** [comment]
OK thanks for pointer - I will check that.
