### ISSUE TITLE
Escape key delay one second

### ISSUE THREAD

**Issue by pawamoy** [peterbrittain/asciimatics#232]
Hi, I'm just opening this issue to add the knowledge here. Thank you again @peterbrittain for answering so fast on Gitter :slightly_smiling_face: 

So, by default, the escape key takes about one second to be received on some systems.

The solution to reduce the delay was found here: https://stackoverflow.com/questions/27372068/why-does-the-escape-key-have-a-delay-in-python-curses

Basically you have to set the environment variable `ESCDELAY`, that curses uses, to something like 25 ms.

```python
os.environ.setdefault("ESCDELAY", "25")
```

As some comments say, you apparently have to set it **before** initializing the screen. I tried it myself and it works just fine!

**Comment by peterbrittain** [comment]
Thanks @pawamoy.  Should be in the troubleshooting docs...
