### ISSUE TITLE
More than 8 background colours

### ISSUE THREAD

**Issue by dobin** [peterbrittain/asciimatics#234]
**Is your feature request related to a problem? Please describe.**
Can't make background colour grey.

```
    screen.print_at(
        text='Text grey background black', 
        x=0, 
        y=1, 
        colour=Screen.COLOUR_BLACK, 
        attr=Screen.A_BOLD,
        bg=Screen.COLOUR_BLACK)
```
The `A_BOLD` makes the text grey, but there is no corresponding attribute for `bg`?

**Describe the solution you'd like**
Maybe an attribute for `bg`, similar to `attr` for `text`?

**Describe alternatives you've considered**
I looked at the samples, but they are hard to understand, and it seems they all use default black background. The documentation for colours is lacking, but it seems there is some kind of 256 colour support. But how does it work? I looked at `class Fire()`, but just see magic values with no context. Can I use that for `bg`?

**Additional context**
Managing two values to get a colour (colour and attr) is troublesome. In curses i am able to generate colours by OR'ing them, e.g. `curses.COLOR_BLACK | curses.A_BOLD = grey`. This would be easier.

**Comment by dobin** [comment]
Err, curses also only has 8 background colors. my fault. Not a bug.

**Comment by peterbrittain** [comment]
Yeah - it's not common to all systems and so I didn't create constants for the 256 colour palette.  You can find a eefinition of it here: https://en.m.wikipedia.org/wiki/ANSI_escape_code

**Comment by peterbrittain** [comment]
Feels like the docs could do a better job of explainig this, thouh.

**Comment by dobin** [comment]
I'd welcome a short overview of how to use colors in asciimatics as part of the documentation.
