### ISSUE TITLE
Record to a GIF ?

### ISSUE THREAD

**Issue by bradparks** [peterbrittain/asciimatics#239]
I'd like to record an asciimatics animation to a gif, at the command line.

Any suggestions on how to do this?  Thanks!

**Comment by peterbrittain** [comment]
I've not needed that as I use asciinema.  However, a quick google online shows a couple of candidates

https://github.com/chjj/ttystudio
https://github.com/icholy/ttygif

Take your pick!

**Comment by peterbrittain** [comment]
I'll leave this open for a bit in case the community has a better suggestion....

**Comment by bradparks** [comment]
Hey... thanks for the suggestions.. I'd tried ttygif but didnt get it to work, but ttystudio led me to a fork of it, [toughtty](https://github.com/zyrolasting/toughtty) that allows you to control when the recording starts, which works great for staring the recording manually.

### So in summary:
- get your animation ready to record
- start the recorder, toughtty by running `$ toughtty record frames.json`
- start your animation. Note that recording hasn't started yet.
- once your animation is running, press Ctrl+T to start recording
- when you think it's good, press Ctr+C to stop the recording
- generate your gif by running `toughtty encode --delay 100 out.json test.gif`
- open the test.gif in your browser to view the animation!

I found toughtty by browsing the active forks of ttystudio
https://techgaun.github.io/active-forks/index.html#chjj/ttystudio

and then installed it under node v8

Example: https://imgur.com/a/0Su6pI6

**Comment by peterbrittain** [comment]
Nice.
