### ISSUE TITLE
pip install -U asciimatics omits parsers module

### ISSUE THREAD

**Issue by jvickroy** [peterbrittain/asciimatics#244]
**Describe the bug**
Entering the shell command: `pip install -U asciimatics` produced the following output:
`
Collecting asciimatics
  Downloading asciimatics-1.11.0-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 748 kB/s
Collecting pypiwin32; sys_platform == "win32"
  Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
Collecting pyfiglet>=0.7.2
  Downloading pyfiglet-0.8.post1-py2.py3-none-any.whl (865 kB)
     |████████████████████████████████| 865 kB 1.1 MB/s
Collecting Pillow>=2.7.0
  Downloading Pillow-7.0.0-cp38-cp38-win_amd64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 2.2 MB/s
Requirement already satisfied, skipping upgrade: future in c:\users\jgv\appdata\local\programs\python\python38\lib\site-packages (from asciimatics) (0.18.2)
Requirement already satisfied, skipping upgrade: wcwidth in c:\users\jgv\appdata\local\programs\python\python38\lib\site-packages (from asciimatics) (0.1.7)
Requirement already satisfied, skipping upgrade: pywin32>=223 in c:\users\jgv\appdata\local\programs\python\python38\lib\site-packages (from pypiwin32; sys_platform == "win32"->asciimatics) (225)
Installing collected packages: pypiwin32, pyfiglet, Pillow, asciimatics
Successfully installed Pillow-7.0.0 asciimatics-1.11.0 pyfiglet-0.8.post1 pypiwin32-223
`
which seems to indicate no issues.

However, `C:\Users\jgv\AppData\Local\Programs\Python\Python38\Lib\site-packages\asciimatics` contains no `parsers.py` module.  This directory does contain the following:
`
    Directory: C:\Users\jgv\AppData\Local\Programs\Python\Python38\Lib\site-packages\asciimatics

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         3/7/2020   8:15 AM                __pycache__
-a----         3/7/2020   8:15 AM          38109 effects.py
-a----         3/7/2020   8:15 AM           1822 event.py
-a----         3/7/2020   8:15 AM           3069 exceptions.py
-a----         3/7/2020   8:15 AM          31264 particles.py
-a----         3/7/2020   8:15 AM           7288 paths.py
-a----         3/7/2020   8:15 AM          40019 renderers.py
-a----         3/7/2020   8:15 AM           4596 scene.py
-a----         3/7/2020   8:15 AM          95278 screen.py
-a----         3/7/2020   8:15 AM           3901 sprites.py
-a----         3/7/2020   8:15 AM           1293 utilities.py
-a----         3/7/2020   8:15 AM            117 version.py
-a----         3/7/2020   8:15 AM         150839 widgets.py
-a----         3/7/2020   8:15 AM            414 __init__.py
`
I'm using Microsoft Windows 10 (all current updates) and Python 3.8.1.  My `pip` app is also current.
I have use `pip` to install many packages on this computer and do not recall ever having experienced a failure.

FWIW, `pip uninstall asciimatics` followed by `pip install asciimatics` did not alter the outcome.

I would appreciate guidance on how to proceed.

Thanks for your time,
/jim

**Comment by peterbrittain** [comment]
That's because I haven't released the parser code yet.  If you look in CHANGES.rst you'll see that the code for parsers is in LATEST, which means it is only available on github.  If you clone the repo and build your install from that, you will be able to pick up the new module.

**Comment by peterbrittain** [comment]
I'm assuming that fixed it...  Please shout if you still have a problem.

**Comment by jvickroy** [comment]
> 
> 
> I'm assuming that fixed it... Please shout if you still have a problem.

Thanks for your quick response to this! /jim

**Comment by lYlantis** [comment]
Just FYI, this was still an issue when I tried to install this today.

**Describe the bug**
Pip installing asciimatics and running samples results in an error on Ubuntu, while installing from the Github repo is successful. 

**To Reproduce**
```
python -m pip install asciimatics
python ~/asciimatics/samples/terminal.py 
```
```
Traceback (most recent call last):
  File "/home/jashmore6/asciimatics/samples/terminal.py", line 5, in <module>
    from asciimatics.parsers import AnsiTerminalParser
ImportError: No module named parsers
```

**Expected behavior**
Expected the example to run.

**Screenshots**
When I downloaded the tar from pypi here are the contents:
![asciimatics-issue](https://user-images.githubusercontent.com/11239651/78916854-166c5600-7a5c-11ea-9d0d-3fa7134d83a9.png)


**System details (please complete the following information):**
 - OS and version: Ubuntu 18.04.4
 - Asciimatics version asciimatics-1.11.0

**Additional context**
Cloning the repo and installing with:
```
sudo python setup.py install
```
Installs successfully and I can run the demos.

**Comment by peterbrittain** [comment]
That's expected.  Until I publish the latest version on master, only the samples on the associated release tag will work with a published release.
