### ISSUE TITLE
Color theme reset on resize

### ISSUE THREAD

**Issue by pawamoy** [peterbrittain/asciimatics#245]
**Describe the bug**
Upon resizing the terminal, the color is reset to the system's or user's (or else).

**To Reproduce**
I'm using [pywal](https://github.com/dylanaraps/pywal) to dynamically set the terminal color theme based on the wallpaper. It generates a `~/.cache/wal/sequences` file that you can `cat` to apply the color themes. Without interpreting escape sequences, it looks like this:

```console
$ cat -v ~/.cache/wal/sequences
^[]4;0;#090808^[\^[]4;1;#f35300^[\^[]4;2;#ff9323^[\^[]4;3;#0043c1^[\^[]4;4;#0048f9^[\^[]4;5;#195fff^[\^[]4;6;#b13cff^[\^[]4;7;#d6d3cf^[\^[]4;8;#959390^[\^[]4;9;#f35300^[\^[]4;10;#ff9323^[\^[]4;11;#0043c1^[\^[]4;12;#0048f9^[\^[]4;13;#195fff^[\^[]4;14;#b13cff^[\^[]4;15;#d6d3cf^[\^[]10;#d6d3cf^[\^[]11;#090808^[\^[]12;#d6d3cf^[\^[]13;#d6d3cf^[\^[]17;#d6d3cf^[\^[]19;#090808^[\^[]4;232;#090808^[\^[]4;256;#d6d3cf^[\
```

When running an `asciimatics` application and resizing the terminal, the theme is "un-applied".

**Expected behavior**
I'm not actually expecting this to be "fixed", because following previous discussions I believe this is not fixable, due to cross-compatibility concerns or simply due to the underlying curses libraries. Instead, I'm opening the ticket for future reference, because I found a solution :slightly_smiling_face:

## Solution (to implement in user's code)

I'm using `asciimatics` at a somewhat low-level, not using widgets or scenes: I'm writing the text myself, managing rows and stuff. Here's my loop:

```python
while True:
    with ManagedScreen() as screen:
        while not screen.has_resized():
            # do stuff
        # screen was resized
        post_resize()
```

And my `post_resize` function:

```python
def post_resize():
    wal_sequences = Path.home() / ".cache" / "wal" / "sequences"
    try:
        with wal_sequences.open("rb") as fd:
            contents = fd.read()
            # buffer is needed to write bytes
            sys.stdout.buffer.write(contents)
    except Exception:
            pass  # we don't care about failures
```

@peterbrittain do you want me to open a PR to add this in the "Troubleshooting" section maybe?

**Comment by peterbrittain** [comment]
Hi @pawamoy .  Yeah - an extra section in the troubleshooting doc would be perfect for this.  I'll happily take a PR for that.
