### ISSUE TITLE
Hash-bang lines for shell scripts (and executable, if possible)

### ISSUE THREAD

**Issue by yam655** [peterbrittain/asciimatics#248]
**Is your feature request related to a problem? Please describe.**

The Python samples are not executable, and don't function properly after a `chmod +x`.

**Describe the solution you'd like**

Prepending the following hash-bang line will cause Python 3 (the current, supported version of Python) to be used when it is somewhere on the path:

`#!/usr/bin/env python3`

This will work when Python 3 is installed in /usr/bin, as well as when it is installed in /usr/local/bin, /opt/something--- or even somewhere in `$HOME`.

Git can store the executable status if you're not running in Windows, but even if you are running in Windows, `chmod +x *.py` is easy for folks to do after they've cloned the repo.

**Describe alternatives you've considered**

The alternative is to leave them alone and let consumers of the package make the change if they want the scripts to be executable.

**Comment by peterbrittain** [comment]
Seems like a pretty easy change and shouldn't affect windows, so I'd happily accept a PR for this.
