### ISSUE TITLE
Images which are "ANSI Art" files

### ISSUE THREAD

**Issue by yam655** [peterbrittain/asciimatics#249]
**Is your feature request related to a problem? Please describe.**

Using Asciimatics it is easy to render an AsciiArt of a graphic image for a background, and have a menu on top of it.

If we could use ANSI files, then we could hand-draw (and/or hand-color) an Ascii Art file, which would complement the existing features.

**Describe the solution you'd like**

Ideally, I'd like full support of ANSI animations and still files. BBS "ans" files, complete with optional SAUCE metadata and timing instructions, `ttyrec` files that also include timing data, as well as Asciinema's JSON files that can be played back in a browser or console.

**Describe alternatives you've considered**

Still images of ANSI files would help a lot. That could ignore timing and cursor movement and just decode xterm-color-256 codes in to a buffer that could be presented like any other color content.

**Additional context**

If you need examples of the ANS files, there is a selection available at: http://artscene.textfiles.com/ansi/

Loading of ANS files (and possibly others) will need an encoding option, as they're regularly the ancient "OEM US" encoding "CP437".

**Comment by peterbrittain** [comment]
Have you tried using the parsers in master along with a TextBox widget?  I expect any static content should pretty much work with that.  Not so sure about animations, though.  They will need a separate parser/loader.

**Comment by yam655** [comment]
I've not. That sounds great!

I've been sticking to the released product because it makes it easier for folks who want to use my own product. (A little menu tool, like `pdmenu`.)

**Comment by peterbrittain** [comment]
Yeah - makes sense.  I should probably push this release soon.  

Out of interest would you be more interested in a Renderer supporting this stuff (so that it could be used with the Print Effect), or a widget that does this?

**Comment by yam655** [comment]
For my purposes, definitely a Renderer. I want to be able to use it like any other image.

**Comment by peterbrittain** [comment]
Ok.  I'll have a think about that option....

**Comment by peterbrittain** [comment]
Ok...  I've had a look at this and it depends on the exact file.  Many just use codes to change colours; quite a few use full screen ansi codes to create some sort of animation as long as you consume the text at a regular (and slow) pace; some appear to have been recorded from applications that had custom timing.

Taking those categories in turn:

1. Simple static colour definitions will already work in a TextBox using the Ansi terminal parser.
2. The terminal demo will handle the animated files that just need regular consumption.
3. The last category would need to recreate the original application's timing, i.e. you would have to hard-code required stream offsets and timings on a case by case basis.

Not many fall into that last category, so I don't expect to do anything there.  Remaining work appears to be to create code to read the files (with the right code page decoding) then create some sequence of output for use.  It's possible that could be done as a re-working of the terminal demo as a renderer.

I don't think I'll do that for the current release, but you could start from that now if you needed something sooner.

**Comment by peterbrittain** [comment]
Check out https://github.com/peterbrittain/asciimatics/tree/ansi_art...

It's early days, but the new player.py demo in that branch can play asciinema and ansi art files using new dynamic renderers!

**Comment by peterbrittain** [comment]
This is now live on master.
