### ISSUE TITLE
ASCII control codes Ctrl-S and Ctrl-Q aren't picked up on input

### ISSUE THREAD

**Issue by Zektron42** [peterbrittain/asciimatics#25]
When I try and get input for different control codes it seems only some work. For example ctrl+z works fine but if I try to input ctrl+s my program acts as if nothing has happened. I'm not sure if I'm just using the tool incorrectly or if control codes aren't entirely supported as of yet, but, any help would be great.
example code I used for testing:
````
from asciimatics.screen import Screen
import asciimatics

def mTest(screen):
    while True:
        event = screen.get_event()
        if type(event) == asciimatics.event.KeyboardEvent:
            screen.print_at(' '*25, 0, 0)
            screen.print_at(str(event), 0, 0)
            if event.key_code == 26:
                screen.print_at('ctrl+z', 0, 1)
            if event.key_code == 19:
                screen.print_at('ctrl+s', 0, 2)
        screen.refresh()

Screen.wrapper(mTest)
````

**Comment by peterbrittain** [comment]
The keys detected depend on what your terminal intercepts and uses itself...  Can you please tell me what you are using - e.g. OS, terminal, python version?

**Comment by Zektron42** [comment]
OS: Windows 10
Terminal: standard command prompt (non-legacy console)
Python version: 3.4

If's there's any other way I can help just let me know. This looks like a great tool and so far has been pretty fun to use.

**Comment by peterbrittain** [comment]
Thanks for your support!  By all means, if you have new ideas, please feel free to contribute to the project...

Thanks for the info...  I've found some help for Linux terminals here (http://unix.stackexchange.com/questions/12107/how-to-unfreeze-after-accidentally-pressing-ctrl-s-in-a-terminal) but that doesn't help you...  I'll keep digging for Windows and update the trouble-shooting guide once I have something.

**Comment by peterbrittain** [comment]
Sigh.  Looks like this is a restriction in Windows itself.  See the detailed comment trail here: stackoverflow.com/questions/26436581/is-it-possible-to-disable-system-console-xoff-xon-flow-control-processing-in-my

My own quick experiments line up with what people say there.  I'll look around elsewhere to see if I've missed anything, but I think that this specific key code just cannot work on Windows.

**Comment by peterbrittain** [comment]
Based on my research, the title of this issue is too broad.  Fixed up to be more helpful to others if they hit it before I update the guidance...

**Comment by peterbrittain** [comment]
Looks like UNIX also has ctrl-z problems.  This is fixed in master code if you use `catch_interrupt`.  Patch is available in https://github.com/peterbrittain/asciimatics/commit/1863b44323985880bd77b3a05f0c80295a956a2b

**Comment by Zektron42** [comment]
So I tried it again and ctrl+q seems to work fine. I did notice that when ctrl+s was pressed the next keyboard input (and only the next input) was dropped. This may not help fix the problem but it might be something you would want to mention in the help docs.

**Comment by peterbrittain** [comment]
Thanks.  That's expected given what I've already found on the web...  Will update the docs and close (unless I can find a better solution for Windows).

**Comment by peterbrittain** [comment]
Documented workaround and Windows restriction in https://github.com/peterbrittain/asciimatics/commit/72f3127d623021540d117e3982f16b1cafe8a1a6
