### ISSUE TITLE
Widgets can't click by mouse in Windows Terminal

### ISSUE THREAD

**Issue by Peter-Duan** [peterbrittain/asciimatics#254]
**Describe the bug**
Button widgets can't click by mouse in Windows Terminal

**Screenshots**
This is original cmd
![cmd](https://user-images.githubusercontent.com/48420970/82134154-a8395280-97c2-11ea-8968-ef5fe7406d55.gif)

This is Windows Terminal
![wt](https://user-images.githubusercontent.com/48420970/82134155-a8d1e900-97c2-11ea-9e4f-3875822cc6bc.gif)

**System details (please complete the following information):**
 - OS and version: [Windows 10]
 - Asciimatics version [1.11.0]

**Comment by peterbrittain** [comment]
Have you looked at https://asciimatics.readthedocs.io/en/latest/troubleshooting.html#windows

**Comment by Peter-Duan** [comment]
No yet, but now I know. Thanks
