### ISSUE TITLE
Displaying simple string in effect/renderer

### ISSUE THREAD

**Issue by plu777** [peterbrittain/asciimatics#259]
Diagram: Barchart with TextBox (intended to display labels for bars)

![Asm_BC_TB](https://user-images.githubusercontent.com/60972743/83777329-48aec400-a657-11ea-89c4-1df8bdac1d39.JPG)

I'm getting stumped by the simplest of things.  I would like to print a string at a certain location while running a renderer in an effect.  In particular, I'd like to add labels to a bar graph (as in bar.py).

I know screen.print_at() can display a string, but this is not coordinated with the Barchart renderer.

Also, related questions:

I see a FigletText renderer, but don't see anything for just displaying a simple ASCII text string.

I see a TextBox widget, but there doesn't seem to be any way to specify what text/string can be displayed in the text box, or to be able to have a text box with no border (perhaps with color hack), which would display the associated text/string as a plain label.

Thanks for any/all help.

**Comment by plu777** [comment]
![Asm_BC](https://user-images.githubusercontent.com/60972743/83801959-f631cf80-a677-11ea-91de-beda057983bb.JPG)

Thank you so much.  Just what I wanted.  Would have never gotten it without your help.

Really neat package.

Onto the next tidbit...

**Comment by peterbrittain** [comment]
Thanks.
