### ISSUE TITLE
Background widget errors when added to layout in Frame class

### ISSUE THREAD

**Issue by MonAaraj** [peterbrittain/asciimatics#260]
**Describe the bug**
trying to add a `widgets.Background(..)` object to a layout using `layout.add_widget(background)` produces an error. I try to use the object to change the console's background color to red using `Screen.COLOR_RED`. It results in the error:
```python3-traceback
Traceback (most recent call last):
  File "DatInkTank2.py", line 55, in <module>
    screen.Screen.wrapper(main, catch_interrupt=True, arguments=[last_scene])
  File "/usr/local/lib/python3.8/site-packages/asciimatics/screen.py", line 1342, in wrapper
    return func(screen, *arguments)
  File "DatInkTank2.py", line 45, in main
    scene.Scene([MainMenu(scr)], -1, name="Main Menu")
  File "DatInkTank2.py", line 15, in __init__
    layout.add_widget(
  File "/usr/local/lib/python3.8/site-packages/asciimatics/widgets.py", line 983, in add_widget
    widget.register_frame(self._frame)
AttributeError: 'Background' object has no attribute 'register_frame'
```

**To Reproduce**
using this code:
```python3
#!/usr/bin/env python3.8
from asciimatics import screen, exceptions, widgets, scene
import sys

class MainMenu(widgets.Frame):
    def __init__(self, scr):
        super(MainMenu, self).__init__(scr,
                                       scr.height,
                                       scr.width,
                                       name="Main Menu")
        layout = widgets.Layout([65, 35], fill_frame=True)

        self.add_layout(layout)

        layout.add_widget(
            widgets.Background(scr, bg=screen.Screen.COLOUR_RED)
        )

        self.fix()

def main(scr, scn):
    scenes = [
       scene.Scene([MainMenu(scr)], -1, name="Main Menu")
    ]

    scr.play(scenes, start_scene=scn)


if __name__ == "__main__":
    while True:
        try:
            screen.Screen.wrapper(main, catch_interrupt=True, arguments=[None])
            sys.exit(0)
        except exceptions.StopApplication as e:
            pass
```

**Expected behavior**
expected to change the background color by applying the widget

**System details (please complete the following information):**
 - OS and version: Ubuntu 19.04
 - Asciimatics version 1.11.0

**Comment by peterbrittain** [comment]
If you look at the definition of Background, you'll see that it is an Effect (i.e. a peer of the Frame) and so shouldn't be used in this way.  Check out forms.py for an example of the correct usage.

To change the background of your Frame, you need to produce a new colour palette (the palette property on the Frame.  You can see an example of this in top.py.  Note that this uses a defaultdict to simplify the definition of all possible keys for the palette (as defined in https://asciimatics.readthedocs.io/en/stable/widgets.html#colour-schemes).  If you want a more colourful Frame, you'll probably need more.  Check out the definitions of the themes in the widgets sub-package for inspiration.

**Comment by peterbrittain** [comment]
Assuming that resolve it for you, I think I should revisit the docs to make it clearer that this isn't a widget (even though it is in that sub-package).  Probably something that should really be addressed by  moving it,  but that's got to be saved for a version change.

**Comment by MonAaraj** [comment]
Thank you :)

**Comment by peterbrittain** [comment]
Reopening until I've reviewed the docs...
