### ISSUE TITLE
Update docs with frame explanation

### ISSUE THREAD

**Issue by vinayak-mehta** [peterbrittain/asciimatics#267]
**Is your feature request related to a problem? Please describe.**

Opening this issue based on the Gitter conversation.

**Describe the solution you'd like**

I think the docs [here](https://asciimatics.readthedocs.io/en/stable/animation.html) could be updated with a better explanation of where frames lie in the Screen/Scene/Effect hierarchy, how they're different from the Frame object, along with an example of how we can use `start_frame` and `stop_frame` to time changes inside a Scene.

**Describe alternatives you've considered**

NA

**Additional context**

NA

---

Thanks again for asciimatics!

**Comment by peterbrittain** [comment]
Thanks.  I'll try to fix that this week.

In the meantime, please feel free to submit your current code for #263 and we can discuss tweaks in that PR.

**Comment by vinayak-mehta** [comment]
Thanks! I'll submit the current code on #263 today :+1:
