### ISSUE TITLE
Preserve/Detect/Set terminal text color

### ISSUE THREAD

**Issue by erose1337** [peterbrittain/asciimatics#27]
It may be a problem with my configuration or perhaps how I am using your package, but when I attempt to run an asciimatics program, the text color of my terminal is switched from green to white, and I have to manually switch it back after I'm done playing with asciimatics. 

It would be nice if this could be automated. If it is not convenient for asciimatics to reset the colors, could/does the package perhaps expose functions for detecting and setting the text color of the terminal? Or does it do so already and I just have some kind of configuration issue?

To clarify, I am referring to the text color of my shell when asciimatics is *not* running. Before running asciimatics, the text color is green; After running a my asciimatics program, it is white. I would like for it to remain green.

**Comment by erose1337** [comment]
I'm not sure if this classifies as a bug, enhancement, or just customer support, but thank you for any help.

**Comment by peterbrittain** [comment]
I can certainly try.  Generally speaking, I already use the standard interfaces supported by the underlying OS to do a reset...  I might be able to tweak that, but it will depend on the OS.

Can you please give me some more details of what your environment is and how you set up your default green text?

**Comment by erose1337** [comment]
I'm using powershell on Windows 8.1. 
To set the text color, I right click on the title bar, select properties, then select the colors tab.
Then I set the Screen Text value to the dark green color available in the palette.

**Comment by peterbrittain** [comment]
And which version of asciimatics are you running?

**Comment by erose1337** [comment]
Right, 1.6.0

**Comment by peterbrittain** [comment]
OK - I think I see what's needed...  Will see if I can patch it next week.

**Comment by erose1337** [comment]
Thanks, you rock!

**Comment by peterbrittain** [comment]
OK - this is now fixed by https://github.com/peterbrittain/asciimatics/commit/65156fcb9029ba2b7a159696b33a42ced584ea8e.  I'll roll it out in the next major build - which should be v1.7.
