### ISSUE TITLE
Left/Right Navigation

### ISSUE THREAD

**Issue by peterjschroeder** [peterbrittain/asciimatics#270]
It would be preferable for left and right to switch focus to the nearest widget rather than the bottom of the nearest widget's column.
I have an app that is a grid of equal size buttons, which this behavior makes it unusable.

Even if this is something you are not interested in doing. Can you point me in the right direction on getting this done per app?
I subclassed Layout->process_event, I see the code for KEY_LEFT and KEY_RIGHT, but I am not understanding how it works.
find_next_widget looks like where the magic happens. First value is the column difference. I would think start_at would be how far down the column to check for the next widget. That doesn't seem to be it tho. Even if it is, I'd need to get the row? somewhere.

**Comment by peterbrittain** [comment]
Yeah - you've found the place that handles the logic.

It fundamentally looks for the first/last widget in the next/previous column when you press the key.  This is an internal function, so you could rework it to be something that is more cunning.  

Some of the complexity in there comes from the fact that it also gets used for tabbing (requires full enumeration of all columns) and up/down keys (requires iteration up/down a single column) and then the need to handle multiple Layouts and wrapping around the UI.  Oh and also handling the case where a Layout contains no active widget.

I'd be very happy for you to create a new (internal) function to handle this new style of navigation (nearest widget in next column) and just use that instead for the left and right keys in widget navigation.  You'd probably need to use the `get_location()` method to do the distance calculation, which may have some negative numbers for off-screen widgets, but I think that's all fine for Euclidean distance.

Got what you need to have a go at a PR?

**Comment by peterjschroeder** [comment]
Thank you.

I think so. I'll take a stab at it later tonight.

**Comment by peterjschroeder** [comment]
I ended up using urwid for this app instead.

This is the code I ended up with before I gave up. It only works on a grid (equal size, equal position) and bombs out if there is an empty square.

`    def _find_nearest_widget(self, direction, stay_in_col=False, start_at=None, wrap=False):
        if stay_in_col:
            if self._live_widget + direction > len(self._columns[self._live_col]) - 1:
                self._live_widget = 0
            elif self._live_widget + direction < 0:
                self._live_widget = len(self._columns[self._live_col]) - 1
            else:
                self._live_widget = self._live_widget + direction
            return

        y = self._columns[self._live_col][self._live_widget]._y - 1

        if self._live_col + direction >= len(self._columns):
            self._live_col = 0
        elif self._live_col + direction < 0:
            self._live_col = len(self._columns) - 1
        else:
            self._live_col += direction

        self._live_widget = y`

**Comment by peterbrittain** [comment]
Sorry to hear that.  Thanks for having a go, though.

I think this can be simplified (it only needs to handle left/right and so shouldn't ever stay in column).  Then the new function just needs to find the next column in the required direction with any active widgets and pick the one in that column with the smallest distance from this one.  I'll see if I can get that working.

**Comment by peterjschroeder** [comment]
No problem. The app was very basic, so it came down to what took the least amount of time to implement it. urwid has a GridFlow widget which did exactly what I needed. I usually use your library for all my projects tho.

Originally, yes I thought it was only left and right. But than when it went to wrap, it ended up on a different column.

**Comment by peterbrittain** [comment]
Thanks.  Just so I haven't missed anything when I come along to the implementation...  Can you please explain the wrapping problem a little more?  

I'd expect left/right to always stay in the same layout and so the wrapping case is just moving back to the first column and then continuing to apply the same distance logic for active widgets.  If we iterate all the way through and get back where we started, there is no active widget and we stay where we are.

**Comment by peterjschroeder** [comment]
That is correct for Left/Right. For Up/Down it is currently wrapping to the first/last column no matter what column it is in.

**Comment by peterbrittain** [comment]
Ahhhh...  The light dawns.  Thanks.  I'll mull that over too.

**Comment by peterbrittain** [comment]
Turns out that there were a few wrinkles in here...  I think I've got it working for left/right and up down in a single layout, though.  Just need to sort out the transition across layouts, add some tests and we're done.

**Comment by peterjschroeder** [comment]
Excellent. Thank you for working on this. Turns out there was more in my que that needed this.

**Comment by peterbrittain** [comment]
OK - I think I've addressed this now.  I've not yet written the new tests, but the code in https://github.com/peterbrittain/asciimatics/tree/new_navigation should give you what you need.  Are you able to give it a test run and let me know if there's anything wrong with the logic?

**Comment by peterjschroeder** [comment]
Directions work correctly. Wraps left and right correctly.

Bombs on the following:
Wrapping up and down.
If there is a layout above it, hitting down.

Also tab goes to the next row of widgets, it should jump to the next layout.

Attached is what I'm working with.
![blah](https://user-images.githubusercontent.com/10292399/94626832-e9219780-0289-11eb-838f-f11bdcabeb7a.png)

**Comment by peterbrittain** [comment]
That was quick!  Thanks.  I think that's all fine.

1. Tab is working as designed.  It should run through every widget that can take input, not just between layouts.
2. The error is the one case I forgot to test last night.  Easy fix.  Good catch!

I should be able to code that up with tests in the next few days.

**Comment by peterjschroeder** [comment]
Excellent.

Understood on the tabbing. I'll just have to override it when need be as in this case tabbing through 150+ Checkboxes to get to the next layout would take forever :P

**Comment by peterbrittain** [comment]
Fair enough.  You can probably do that by simply overriding the Layout and forcing it to ignore TAB/BACKTAB keys - at which point the Frame will try to move the focus to the next/previous Layout.

**Comment by peterjschroeder** [comment]
I see up and down doesn't wrap in the same layout, instead it goes to the nearest widget in the previous/next widget. Was this intentional?

**Comment by peterbrittain** [comment]
Yes.  While I expect there are some cases where you might want to treat individual Layouts as some sort of closed system that needs to be tabbed into/out of, I think most users would expect to just move on to the next widget in the relative direction.  

Put another way, since they won't be aware of the separate Layouts, they would be surprised by the fact that something invisible is blocking their ability to move around the form.

**Comment by peterjschroeder** [comment]
Makes sense. Thank you.
