### ISSUE TITLE
Navigation via tabs

### ISSUE THREAD

**Issue by plu777** [peterbrittain/asciimatics#271]
I'm trying to create a "control panel" utility consisting of a tabbed set of pages aggregated together, much like tabbed pages on Web browsers.  I found the Contact List sample most similar to what I want to do, with the page selection tabs on the bottom, as attached.

![AsciimaticsTabs](https://user-images.githubusercontent.com/60972743/94434892-710f8080-0168-11eb-9db0-091eb3595e88.JPG)

Here, when I click on "SYS," I switch to the System page, and likewise for the other buttons to their corresponding "control panel" pages.

I know I can implement the tabs by creating a layout on the bottom of each page whose buttons would jump to new pages, similar to what "Add" does in the Contact List sample.  But this is cumbersome (bad programming) as I'd have to keeping updating _every_ page whenever I modified/added new pages.  What's I'd really want is a "page switching/selecting" widget that could be included/referenced by the various "control panels" pages.  The way layouts are structured doesn't seem to make it easy to do this.  If I were programming in C/C++, I may be tempted to use a macro-include to insert the page selection layout if the "graphics" package didn't have some primitive to "stack" layouts (I think this is usually accomplished with frames); ugly but pragmatic (in terms of code management).

Is there any nice way in Asciimatics to implement the tabbed pages I'm considering?  Is there a "tab" widget/class that would make my life easy?  Is there some Python tricks that would make inserting the page selection layout easy?  Any Asciimatics samples that are closer to what I want done?

Sorry if I'm not posting this issue in the right place.

Thanks  for all help in advance.

**Comment by peterbrittain** [comment]
Hi there.  I'm afraid that there's nothing in asciimatics that will do this for you "for free" today.  I've wondered about this sort of feature in the past.  Options are:

1. Create a new sort of Layout (TabbedLayout) that allows you to embed existing Layouts inside a tab structure.  This gives you full flexibility of your UI inside the TabbedLayout, but is going to be a little grungy to code as it is another layer in the UI hierarchy.
2. Created a simpler sort of Layout that is much the same as the current one, but treats each column as a tab.  Since this doesn't add a new hierarchy, I expect it would be easier to code up.  However, it limits you to just the one column in each tab.
3. Pretend you have tabs, by using a common Layout with buttons that link to separate Frames as per your suggestion.

I don't have the time to add 1 or 2 right now, but I'd happily help you (or someone else!) create a PR for this.  If you don't have the time either, then I suggest option 3 is a reasonable workaround as long as you use a common abstract base class to implement the button Layout.  

That would something a bit like this (code not actually tested, so a few "..." markers in there and probably some typos):

```
class EmptyPanel(Frame):
    def __init__(self, screen, name):
        super(EmptyPanel, self).__init__(...)

    def _add_buttons(self):
        layout = Layout([1, 1, 1, 1, 1])
        self.add_layout(layout)
        layout.add_widget(Button("One", self._one), 1)
        layout.add_widget(Button("Two", self._two), 2)
        ...

    def _one(self):
        self._save()
        raise NextScene("One")

    def _two(self):
        self._save()
        raise NextScene("Two")


class PanelOne(EmptyPanel):
    def __init__(self, screen):
        super(PanelOne, self).__init__(screen, name="One")
        layout = Layout([1, 18, 1])
        self.add_layout(layout)
        layout.add_widget(Text(label="Some field:", name="something"), 1)
        self._add_buttons()
        self.fix()

    def _save(self):
        '''Whatever you need to do to save state before moving to a new Frame.'''
```

This is slightly naughty in that it relies on Python duck-typing to find the right save() method in each Panel without making it clear (e.g. through an abstract base class), but I think it should all work and avoid any duplicated code.

**Comment by plu777** [comment]
Thank you so much for you oh-so-prompt response.  I didn't want to go down the wrong path unnecessarily.

I'll need to spend some time to experiment, to absorb what you suggests.

**Comment by plu777** [comment]
Sorry for bothering you.  I tried merging your code with the start-up code in the Contact List sample,
and haven't had success.  I need to swallow my pride and seek help as there are (implicit?)  interactions  
I don't understand.  I put in...


def demo(screen, scene):
    scenes = [

        # Scene([ListView(screen, context)], -1, name="Main"),
        # Scene([ContactView(screen, context)], -1, name="Edit Contact")
        # Scene([PanelOne(screen, context)], -1, name="PanelOne"),
        Scene([PanelOne(screen, context)], -1),
        Scene([PanelTwo(screen, context)], -1, name="PanelTwo")
    ]

    screen.play(scenes, stop_on_resize=True, start_scene=scene, allow_int=True)


context= ContactModel()
last_scene = None
while True:
    try:
        Screen.wrapper(demo, catch_interrupt=True, arguments=[last_scene])
        sys.exit(0)
    except ResizeScreenError as e:
        last_scene = e.scene




The error I get is...

Traceback (most recent call last):
  File "./martabs.py", line 250, in <module>
    Screen.wrapper(demo, catch_interrupt=True, arguments=[last_scene])
  File "/usr/lib/python3.4/site-packages/asciimatics/screen.py", line 1342, in wrapper
    return func(screen, *arguments)
  File "./martabs.py", line 239, in demo
    Scene([PanelOne(screen, context)], -1),
  File "./martabs.py", line 34, in __init__
    super(PanelOne, self).__init__(screen, screen.height, screen.width, name="One")
TypeError: __init__() got multiple values for argument 'name'


and I don't understand how the "name" is being passed around.   I tried both having
name="PanelOne" in the Scene[ ] line (with somewhat different errors on "name").

I hope I provided enough info.


Thank you for help.

**Comment by peterbrittain** [comment]
You haven't included the right code.  The bug is probably in your `__init__` method declaration.  

Can I suggest you post the full code in a paste bin or github repo, then we continue the discussion on gitter?

**Comment by plu777** [comment]
Hi, Peter,

Please let me know if we are able to communicate directly via email.  I don't know what github rules
are on this.  I don't have glitter and shy away from social media channels for privacy/security reasons.

I can post the code to filedropper for your downloading, so you can run it.  At this point, I'm just slapping
together code, so there's nothing "proprietary" but since the project is work related, I'm hesitant to have
anything posted in entirety to github (forum).  It's probably something simple, but my ignorance keeps
me from making progress.  I will post the bits of code that err and the fix on github issue #271 if you wish,
just to show the solution.

Thank you so much for your help.


________________________________

**Comment by peterbrittain** [comment]
Gitter just uses your github account to identify you, so you can already use it.  However, if you want to use email, feel free to contact me at peter.brittain.os@gmail.com.

**Comment by peterbrittain** [comment]
Just tidying up the trail so that this covers the enhancement idea.

**Comment by JPTIZ** [comment]
Maybe making a `.replace_widget(new_widget, column)` for layouts and/or `.replace_layout(layout, index)` for frames could be a simple first-time approach to implement the "fake tabbed layout".

I was making [my TUI version](https://github.com/jptiz/clickup-tui) of [Clickup](https://clickup.com/) and got stuck exactly on this issue. Thought about clearing the whole upper layout and readd the elements (but with one different), e.g. like this:

```python
    def _on_change_sidebar_item(self):
        def _switch_to_home():
            self.top_layout.clear_widgets()
            self.top_layout.add_widget(self.sidebar)
            self.top_layout.add_widget(VerticalDivider(), 1)
            # self.top_layout.add_widget(Text('Home!'), 2)

        def _switch_to_notifications():
            self.top_layout.clear_widgets()
            self.top_layout.add_widget(self.sidebar)
            self.top_layout.add_widget(VerticalDivider(), 1)
            self.top_layout.add_widget(Text('Notifications!'), 2)

        CALLBACKS = {
            MainScreen.SidebarItems.HOME: _switch_to_home,
            MainScreen.SidebarItems.TASKS: _switch_to_notifications,
            MainScreen.SidebarItems.NOTIFICATIONS: _switch_to_notifications,
        }

        CALLBACKS[self.sidebar.value]()
```

But those `Text` widgets would only cause an infinite loop inside the lib's code, so it was a little upsetting.

> I don't have the time to add 1 or 2 right now, but I'd happily help you (or someone else!) create a PR for this. If you don't have the time either, then I suggest option 3 is a reasonable workaround as long as you use a common abstract base class to implement the button Layout.

I can take a look at it. I'm heavily lost on how effects works, but...I did do my app stub, so I have a _slight_ idea of the library API.

**Comment by peterbrittain** [comment]
Thanks for the offer.  The Effects API is simple and basically explained here: https://asciimatics.readthedocs.io/en/stable/asciimatics.html#asciimatics.effects.Effect

The widgets are then a special implementation of the Effect API.  The Frame is the Effect and will do some basic housekeeping, but it delegates updates and event handling down to any Layouts.  These Layouts are responsible for setting the size and location of all the Widgets they contain and so call through to the Widgets when they need to update.  Similarly, it will pass on events to the right Widget when it receives them.

So, to do (1) you would need to create a new type of object (lets's call it the MetaLayout) that can be used by the Frame in exactly the same way as it would a current Layout, but this MetaLayout would then only contain Layouts, thus extending the chain of delegation to be Frame->MetaLayout->Layout->Widget.  The MetaLayout would then need to handle the logic for deciding how to arrange the contained Layouts (and reserving space for the tab labels).

Option (2) would be less involved as it would just need to pick apart the existing Layout class to create the existing one and a very similar one that uses the columns as tabs (and gives each tab full access to the space controlled by the Layout).

**Comment by dwhall** [comment]
I think the original problem could be solved through OO programming without having to modify asciimatics.  Create a Layout class for your tab buttons.  That "TabBtnLayout" class is instantiated within the Frame of each tab.

```
class TabBtnLayout(Layout):
    def __init__(self, frame):
        super().__init__([1, 1, 1])
        self._frame = frame
        self.add_widget(Button("Btn1", self._on_click_1), 0)
        self.add_widget(Button("Btn2", self._on_click_2), 1)
        self.add_widget(Button("BtnN", self._on_click_3), 2)
    def _on_click_1(self): raise NextScene("Tab1")
    def _on_click_2(self): raise NextScene("Tab2")
    def _on_click_3(self): raise StopApplication("User quit")


class Tab1Frame(Frame):
    def __init__(self, screen):
        super().__init__(screen,
                         screen.height,
                         screen.width,
                         can_scroll=False,
                         title="Tab 1")
        layout1 = Layout([1], fill_frame=True)
        self.add_layout(layout1)
        # add your widgets to this layout
        layout2 = TabBtnLayout(self)
        self.add_layout(layout2)
        self.fix()


class Tab2Frame(Frame):
    def __init__(self, screen):
        super().__init__(screen,
                         screen.height,
                         screen.width,
                         can_scroll=False,
                         title="Tab 2")
        layout1 = Layout([1], fill_frame=True)
        self.add_layout(layout1)
        # add your widgets to this layout
        layout2 = TabBtnLayout(self)
        self.add_layout(layout2)
        self.fix()
```

**Comment by peterbrittain** [comment]
Thanks.  If you want to submit as a working sample, I'd be happy to merge it...
