### ISSUE TITLE
change win32 dependence from pypiwin32 to pywin32

### ISSUE THREAD

**Issue by drewarnett** [peterbrittain/asciimatics#275]
Please consider changing the win32 dependency from pipywin32 to pywin32.

I was researching TUI libraries, especially asciimatics, after learning about it from local peer.  Part of that was looking at the dependencies.

The pypiwin32 dependency is declared here:  https://github.com/peterbrittain/asciimatics/blob/master/setup.py#L73.  This appears to date back to 2015.

Googling this dependency to learn about it, I think it may be preferable to change this to pywin32.  Googling showed:

- pypi.org has Feb 26, 2018 as latest for pypiwin32.  pypi.org has Jun 13, 2020 as latest for pywin32.

- Looks like circa 2016 pypiwin32 was an offered repackaging of pywin32 to use wheels.  [1]

- Looking at pypi today for pywin32, it appears to use only wheels.  [2]

[1] https://mail.python.org/pipermail/python-win32/2016-October/013786.html
[2] https://pypi.org/project/pywin32/#files

I suspect pypiwin32 was a workaround for a problem that no longer exists.  If that is so, then replace the pypiwin32 dependency in setup.py with pywin32.

One workaround may be to wrangle pip to install asciimatics without installing pypiwin32.  (99% sure this can be done, but need to look it up in the pip documentation.)

Related but similarly dated # 111.

Thanks!

**Comment by peterbrittain** [comment]
Seems like a reasonable change...  Want to do the honours?

**Comment by drewarnett** [comment]
Sure.  I can generate a pull request with the pypiwin32/pywin32 replacement in the 4 files it appears in:
- setup.py
- README.rst
- doc/source/intro.rst
- appveyor.yml

I'll try the pip wrangling workaround first per whatever the project has for test.

**Comment by drewarnett** [comment]
OK if I don't try appveyor first?  Seems safe to skip.

Also, looks like appveyor is pointing to a Dec 2014 version "python.exe -m pip install pypiwin32==219".  Latest is Feb 2018 per pypi.

Prefer to point to specific version of pywin32 in appveyor.yaml (228) or prefer to not specify (use latest)?

**Comment by peterbrittain** [comment]
Thanks.

The pinning was to fix a build issue with pywin32.  Happy to remove the pinning if it now works on the latest version.

**Comment by drewarnett** [comment]
Did a bit of pre-implementation testing.  Far from thorough, but enough to give confidence.

- Windows 10
- cloned asciimatics --> 62a7c89
- found that I couldn't selectively prevent installation of dependencies with pip
- installed some (but probably not all) of the base/dev dependencies with pip:  nose, mock, future, pyfiglet, pillow
- py -3 -m nose --> 132 tests skip 6 fail 1 --> "check that wait_for_input delays as requested when no input"
- ran a few of the samples which looked OK

**Comment by peterbrittain** [comment]
Looks good.  Thanks.
