### ISSUE TITLE
SIGWINCH is not captured by Screen

### ISSUE THREAD

**Issue by peperunas** [peterbrittain/asciimatics#279]
**Describe the bug**
It seems that the signal SIGWINCH is not catched by the handler.

**To Reproduce**
I have tried to resize the terminal on Gnome Terminal and Guake. Both times, `Screen` does not invoke the signal handler causing the screen not to be resized.

**Expected behavior**
`Screen` should raise an exception.

**Screenshots**

**System details (please complete the following information):**
 - OS and version: `Linux 5.9.9-arch1-1 #1 SMP PREEMPT Wed, 18 Nov 2020 19:52:04 +0000 x86_64 GNU/Linux`
 - Asciimatics version: `1.12.0`

**Comment by peterbrittain** [comment]
I've just tested and it works fine on my CentOS 8 Linux system...

Are you specifying `stop_on_resize=true` as per https://asciimatics.readthedocs.io/en/stable/io.html#screen-resizing?  If so, can you confirm that the terminal is creating the necessary signals?

**Comment by peperunas** [comment]
I have modified the code on the handler to print and/or sleep for a certain amount of time and it is not triggered at all. It seems that the terminals are not creating the signals.

How can I check if the terminal is emitting the signal?

Thanks for the prompt response!

**Comment by peterbrittain** [comment]
Well, if you're editing the asciimatics code, you can simply raise a RuntimeError inside `_resize_handler`.  That will kill your application with a stack trace if it gets run (I have just tested that on my system).

If that doesn't happen, then you should check what else is running and whether it is messing around with signal handlers.  If you can see that the right signal handler is in place and it is not being called, that sounds like an issue with either the python interpreter you are using or the Linux distro....  Neither of those sounds likely to me, so I suspect that something else you are running is overwriting the signal handler.

**Comment by peperunas** [comment]
Ok, the `RuntimeError` crashes the program so the signal is working.

I am using `asyncio`, may this be causing the issue?

**Comment by peterbrittain** [comment]
NP - glad I could help.
