### ISSUE TITLE
Frame: lazy creation or refresh

### ISSUE THREAD

**Issue by lykius** [peterbrittain/asciimatics#284]
Hi, asciimatics is really good, thanks for the great job!

I'm using it to create a simple form with two frames: in the first one, the user can fill/edit many values, while in the second one she/he can see a recap of her/his selection and decide whether to confirm or not.
So I'm using something like this:
```
def run(screen: Screen, scene: Scene) -> None:
    scenes: List[Scene] = []
    scenes.append(Scene([EditForm(...)], duration=-1, name="Edit"))
    scenes.append(Scene([RecapForm(...)], duration=-1, name="Recap"))
    screen.play(scenes, stop_on_resize=True, start_scene=scene)
```

The problem is that RecapForm is populated dynamically when it's created based on the selection made by the user in EditForm (the selection is saved somewhere else). With some debugging, I've found out that asciimatics creates all the Scenes at the very beginning and so, when my program switch from EditForm to RecapForm (raising `NextScene("Recap")`), RecapForm doesn't show the user selection because it was created before that the user had made the actual selection.

Which is the proper way to update/refresh RecapForm? It would be nice to select "lazy creation" for the Scenes, but probably this would introduce other problems.

Thanks in advance for any help!
Luca

**Comment by peterbrittain** [comment]
Thanks!  Always nice to hear from another happy user.

To trigger logic at the time the Frame is loaded (rather than initialisation), try using the `on_load` callback.  The contact_list demo has an example of what to do.

**Comment by lykius** [comment]
Thank a lot for the quick answer!

I just tried that and it doesn't seem to work properly for my goal. I think that the problem is that I'm trying to create widgets dynamically while asciimatics expects them to be created only in the __init__, is that right?
The point is that I cannot define widgets for RecapForm before that the user gets there, because widgets are created based on her/his selection in EditForm. Is there any way I can achieve this?

Thanks,
Luca

**Comment by peterbrittain** [comment]
OK - got it...  In that case, I think you can achieve what you want by using that same callback to call `clear_widgets` and then `add_widget` for each widget you want in the new style of layout, then finally call `fix` to sort our positioning.

But that's a very strange way to look at your forms as your logic to extract the fields will also be custom for each type of invocation...  Why not just have a separate Frames for each type of Layout and simply invoke the Frame that you want instead of the rebuilding from scratch each time?

**Comment by lykius** [comment]
I'll try to give you some context. Imagine that I have some file with a list of pairs key-default_value, something like:
```
p1: 1
p2: "hello"
p3: 2021-01-01
p4: /path/to/some/file
```
Now, I load that file in some dictionary and then I have a widget factory which creates a widget for each key-value pair to allow users to edit default values in the EditForm. Then, in the RecapForm I want to show users the result of their selection/editing so that they can confirm or go back to EditForm to change something . A very simple way for me to achieve that is to reuse the widget factory and just set each widget to disabled. The tricky part is that, while editing, one original key-value pair can be replaced with a whole dictionary in a nested way, which cannot be determined before the user makes her/his selection (I'm sparing you the details). This is why I'm creating widgets/layouts dynamically in the RecapForm.

I imagine that a workaround would be to use a single TextBox in the RecapForm to show some recap text instead of using disabled widgets, but the other way is nicer since I can reuse widget factory without any change.

**Comment by peterbrittain** [comment]
OK - I think I get it.  In which case, the use of clear_widgets/add_widget/fix in the on_load callback for the RecapForm should do what you need.

**Comment by lykius** [comment]
It works! :)
Thanks a lot for your  **super quick (!!!!)** help!

**Comment by peterbrittain** [comment]
Great!  I think we can now close this, then...
