### ISSUE TITLE
Mouse-clicks on the right side of buttons sometimes fail to register

### ISSUE THREAD

**Issue by MaxBarraclough** [peterbrittain/asciimatics#285]
**Describe the bug**
Sometimes, mouse-click handling for buttons only works for part of a button's area. Clicking on the right half of a button's area sometimes fails to invoke the handler.

**To Reproduce**
The issue does not seem to impact any of asciimatic's *samples* scripts. I created a short script to illustrate the issue: https://gist.github.com/MaxBarraclough/1d2a17f5683b6449d29ba4ea464ff946 . Perhaps the issue only arises under certain layout conditions.

* Create a button with a short label text.

* Run the program in an environment+terminal where mouse-clicks are supported. Clicking on the left side of the button may work ok, but clicking on the right side of the button area isn't handled.

**Expected behavior**
Clicking anywhere in the screen-area occupied by a button should always result in the button's click-handler being invoked.

**Screenshots**
n/a

**System details**
 - OS and version: Ubuntu Server 20.10 / AArch64
 - Python3 version: 3.8.6
 - asciimatics version: 1.12.0

And also on:
 - OS and version: Windows 10 / AMD64
 - Python3 version: 3.9.1
 - asciimatics version: 1.12.0
 
**Additional context**
A short snippet from my script:

```python3
        layout = Layout([100], fill_frame=True) # single column occupying 100% of available width
        self.add_layout(layout)
        layout.add_widget(Button("Overwrite text in text box (1)", self._button1_clicked))
```

**Comment by MaxBarraclough** [comment]
Thanks, impressively quick response!

Related to this, I'm seeing that clicking just to the left of an affected button can result in the button-click handler being invoked.

**Comment by peterbrittain** [comment]
Yeah - that's the problem.  If you need a quick workaround, just move the Text widget into a separate layout, or remove its label.  I'll push a patch once I have properly tested the fix.
