### ISSUE TITLE
Full redraw on suspend+restore (support for ctrl-z and fg)

### ISSUE THREAD

**Issue by MaxBarraclough** [peterbrittain/asciimatics#286]
**Is your feature request related to a problem? Please describe.**
On GNU/Linux, if I suspend an asciimatics application by pressing *ctrl-z* and then run *fg* to restore it to the foreground, asciimatics doesn't properly redraw the screen. Instead I see a black screen, and partial drawing as I move focus between widgets.

This is easily recreated: run one of the sample applications, press *ctrl-z*, then run *fg*.

**Describe the solution you'd like**
The asciimatics library should automatically handle this, performing a full redraw when necessary. TUI applications like vim and htop seem to do this; they behave ok if suspended then restored.

**Describe alternatives you've considered**
I don't have any alternatives or more detailed suggestions.

I've not considered Windows. I'm not sure if it's even possible to suspend+restore on Windows.

**Additional context**
I use Ubuntu 20.10 and tmux but I imagine it's the same on any Unix.

**Comment by peterbrittain** [comment]
It's currently possible to disable that ctrl-z feature in Linux by using the `catch_interrupt` parameter when creating your `Screen`.  Is that any use for you?  

Failing that, I expect this is a matter of catching the right signal on resume and acting on it...

**Comment by MaxBarraclough** [comment]
`catch_interrupt=True` does indeed block me from suspending my application with *ctrl-z*. I'd usually consider that a bug in a TUI application, unless there's a good reason its execution can't be interrupted, but it's not a bad workaround.

I think you're right that it's a matter of responding to a signal with a full redraw. This isn't something I've dealt with before but from a glance at the source of the relatively simple `less` TUI application, the solution seems indeed to be to detect the relevant signal [0][1] and respond to it by flagging the screen as trashed (to used the `less` terminology), handling this state with a full redraw [2].

[0] https://github.com/gwsw/less/blob/d4faa92229f0cbc6a/output.c#L51

[1] https://github.com/gwsw/less/blob/d4faa92229f0cbc6a/less.h#L491

[2] https://github.com/gwsw/less/blob/d4faa92229f0cbc6a/command.c#L700

**Comment by peterbrittain** [comment]
Yeah there's a reason that I don't enable those handlers by default, but there are also cases where it is valid for the application to process them.  Down to the developer to chose what's right for their app.

Nonetheless, it should be possible to handle this case when normal OS logic is applied.  I'l check out the necessary signal and create a patch.
