### ISSUE TITLE
ListBox drawn outside of desired width

### ISSUE THREAD

**Issue by vlads87** [peterbrittain/asciimatics#287]
**Describe the bug**
The width of a ListBox is overflowing the desired boundary.

**To Reproduce**
Have a Layout with 4 objects: 1 ListBox and 3 Buttons.
Column widths are 70, 10, 10, 10.
The ListBox overflows over the expected width. When selecting the ListBox with the mouse I can see that is larger than expected. 
Issue not seen when using Text instead of ListBox.

**Expected behavior**
ListBox should follow width restriction.

**Screenshots**
[ListBox Overflow](https://pasteboard.co/JIHyarG.png)

**System details (please complete the following information):**
Seen on: Windows 10 + Python 3.7 + Asciimatics 1.12.0
Also happens on: RHEL 8.3 + Python 3.6 + Asciimatic 1.12.0

**Additional context**
This used to work correctly in Asciimatics 1.8.0.
I suspect there is an issue with the width calculation in the update method from the ListBox class since it changed from 1.8.0 to 1.12.0. Subtracting self._offset from width as was done in 1.8.0 seems to fix the issue::

        self._draw_label()

        # Prepare to calculate new visible limits if needed.
        height = self._h
        width = self._w - self._offset

        # Clear out the existing box content

**Comment by peterbrittain** [comment]
Yup - looks like a regression from when I added support for scroll bars in the listbox.  You can submit that fix as a PR if you like.
