### ISSUE TITLE
ESC key response is slower than other keys.

### ISSUE THREAD

**Issue by uthline** [peterbrittain/asciimatics#289]
**Describe the bug**
ESC key response is slower than other keys like a,b,c, BACKSPACE, SPACE, ... .

**To Reproduce**
add print to `process_event` function
run application
type a,b,c, and ESC

**Expected behavior**
print log right after type the keyboard.
but when press the ESC key, log was printed after about 1 second.

**System details (please complete the following information):**
 - ubuntu 16.04
 - python==3.5.2
 - asciimatics==1.12.0

**Comment by peterbrittain** [comment]
https://asciimatics.readthedocs.io/en/latest/troubleshooting.html#there-s-a-big-delay-when-i-press-escape

**Comment by uthline** [comment]
@peterbrittain 
Thank you for quick response.
