### ISSUE TITLE
Text widget should fully reset its state when a value changed

### ISSUE THREAD

**Issue by zencd** [peterbrittain/asciimatics#294]
**To Reproduce**
Run the example attached.
The example changes text in a text field in a cycle.
The both text samples are longer then the screen's width, they has different length.
Press any key 3+ times.

**Expected behavior**
No right padding expected to be seen in the text field.

**Describe the bug**
Instead, a right padding appears after 3 key strokes.

**System details:**
 - OS: macos 10.15.2
 - Asciimatics 1.12.0
 - Python 3.8.6
 - Terminal: iterm2, pycharm

**Proposed fix**
In Text::reset() add:
self._start_column = 0
It gets fixed when this patch applied.

[text_bug.txt](https://github.com/peterbrittain/asciimatics/files/5976281/text_bug.txt)

**Comment by peterbrittain** [comment]
OK.  I see the problem and agree that's the fix.  Will push something soon.
