### ISSUE TITLE
running a ray-tracing maze after an animation

### ISSUE THREAD

**Issue by ajhcodes** [peterbrittain/asciimatics#297]
I am trying to run a ray-tracing maze (the same code as your demo, but with a different maze) after an animation. All that it does is play the maze at the start. How could this be fixed?

**Comment by peterbrittain** [comment]
Hard to say without any code...  My guess is that you haven't created the right Scene sequence.  You would want to have 2 Scenes - one for the animation (which stops after a fixed time or moves on when you press a certain key) and then the other to run the ray casting game.

**Comment by ajhcodes** [comment]
Thankyou! I have fixed it, so it works now. One last question though- how would I get the maze to close and go to the next scene when you get to the end of the maze?

**Comment by peterbrittain** [comment]
You'd need to put some logic into the program somewhere to detect that you have got to the end of the maze (e.g. in the Gamecontroller) and raise a suitable Exception (https://asciimatics.readthedocs.io/en/stable/widgets.html#exceptions)

**Comment by peterbrittain** [comment]
I'm assum8ng that answered the question....

**Comment by ajhcodes** [comment]
yes, it did thankyou :)
sorry for not answering, i have been busy.

**Comment by peterbrittain** [comment]
No problem.
