### ISSUE TITLE
Give Button a .text attribute

### ISSUE THREAD

**Issue by dwhall** [peterbrittain/asciimatics#300]
I would like to be able to dynamically update the text a Button displays during run-time.

The alternative is to create a new Button instance with the new text and somehow replace the old button with the new one in the Frame object.  I believe it is preferable to make Button behave more like other widgets with a .text attribute.

I have a working prototype based on your previous feedback along with a happy-case-only unit test.

**Comment by peterbrittain** [comment]
All looked good to me.  Thanks!
