### ISSUE TITLE
Restore widgets docs

### ISSUE THREAD

**Issue by dwhall** [peterbrittain/asciimatics#305]
**Describe the bug**
The Widgets have disappeared from documentation

**To Reproduce**
Cannot find widgets at https://asciimatics.readthedocs.io/en/v1.13/asciimatics.html

I don't know sphinx that well and can't see an obvious problem in the recent 1.13 commits to see why Widget docs disappeared.

**Comment by peterbrittain** [comment]
Looks like we missed that when we broke out the separate subpackage.  I think the change I've just pushed should fix that.

**Comment by peterbrittain** [comment]
I've just merged to v1.13 and checked it is live...
