### ISSUE TITLE
Effect class is imported wrong in samples/maps.py

### ISSUE THREAD

**Issue by billyeatcookies** [peterbrittain/asciimatics#306]
**Describe the bug**
Effect class is imported wrong in samples/maps.py
> ```py
> Traceback (most recent call last):
>   File "maps.py", line 16, in <module>
>     from asciimatics.widgets import Effect, Button, Text, Layout, Frame, Divider, PopUpDialog
> ImportError: cannot import name 'Effect' from 'asciimatics.widgets' (C:\path\to\python\test\lib\site-> > packages\asciimatics\widgets\__init__.py)
> ```

**To Reproduce**
- Install asciimatics package.
- clone the repository
- navigate to the samples directory
- run `maps.py`

**Expected behavior**
Maps should be fetched and displayed as ASCII.

**Screenshots**

![image](https://user-images.githubusercontent.com/70792552/115988430-00272e80-a5ba-11eb-9201-8f6eb1eb1bb1.png)

**System details:**
 - OS and version: Windows 10
 - Asciimatics version 1.13.0 (latest)

**Comment by peterbrittain** [comment]
Been a while since I've run this sample....  Can't believe I was importing Effect from widgets!  :-)

Yeah - that needs fixing.

**Comment by peterbrittain** [comment]
No fixed.  Thanks
