### ISSUE TITLE
Error while creating/reading created cache files (samples)

### ISSUE THREAD

**Issue by billyeatcookies** [peterbrittain/asciimatics#307]
**Describe the bug**
Fails to create cache files inside a new `mapscache` directory.
> ```py
> Traceback (most recent call last):
>   File "test.py", line 561, in <module>
>     Screen.wrapper(demo, catch_interrupt=False, arguments=[last_scene])
>   File "C:\path\to\python\test\lib\site-packages\asciimatics\screen.py", line 1393, in wrapper
>     return func(screen, *arguments)
>   File "test.py", line 554, in demo
>     screen.play([Scene([Map(screen)], -1)], stop_on_resize=True, start_scene=scene)
>   File "C:\path\to\python\test\lib\site-packages\asciimatics\screen.py", line 1566, in play
>     self.draw_next_frame(repeat=repeat)
>   File "C:\path\to\python\test\lib\site-packages\asciimatics\screen.py", line 1669, in draw_next_frame
>     effect.update(self._frame)
>   File "C:\path\to\python\test\lib\site-packages\asciimatics\effects.py", line 71, in update
>     self._update(frame_no)
>   File "test.py", line 452, in _update
>     raise RuntimeError(self._oops)
> RuntimeError: Traceback (most recent call last):
>   File "test.py", line 241, in _get_tiles
>     self._get_vector_tile(x_tile, y_tile, z_tile)
>   File "test.py", line 189, in _get_vector_tile
>     with open(cache_file, mode='w') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'mapscache/0.0.0.json'
>  - tile loc: 0 0 0
> ```

**To Reproduce**
- install asciimatics package
- clone the repository
- navigate to samples
- run `maps.py`

**Expected behavior**
Script should fetch maps and display ASCII version of maps.

**Screenshots**
![image](https://user-images.githubusercontent.com/70792552/115988719-43ce6800-a5bb-11eb-95c3-f395f97aee80.png)

**System details:**
 - OS and version: Windows 10
 - Asciimatics version: 1.13.0

**Comment by peterbrittain** [comment]
I'm guessing you're not running from the checked out code samples directory.  This is meant to use the mapscache sub-directory in there.

**Comment by peterbrittain** [comment]
Now fixed.
