### ISSUE TITLE
New widgets

### ISSUE THREAD

**Issue by peterbrittain** [peterbrittain/asciimatics#31]
Looks like the UI section of the project is quite popular...  Can I add some more useful widgets?  Looking around, some candidates are:
1. ~~Multi-column list~~
2. Tree view - ~~possibly including file dialog~~
3. ~~More specialized input fields - e.g. int, email, etc.~~
4. Embedded effects as widgets - see https://github.com/peterbrittain/asciimatics/issues/23 - could be used for progress indicator, general fill effects, etc.
5. Possibly some graphical effects - like https://github.com/yaronn/blessed-contrib
6. Menus
7. Dropdown lists
8. ~~Display only text widgets~~
9. ~~A map widget - see https://github.com/rastapasta/mapscii~~
10. ~~Date and time selection~~

**Comment by fimion** [comment]
Might I suggest a calendar picker maybe?

**Comment by brycepg** [comment]
How about widgets that do not take any user input, are not selectable, and only display data?

Like a read-only Text widget(or status) that doesn't rely on the Print Effect at a specific location.

**Comment by peterbrittain** [comment]
@brycepg Asciimatics already has the concept of readonly widgets.  You can just disable them.  For an example, see the `TextBox` used in the `PopUpDialog` class.

**Comment by Antekk27** [comment]
Hi there,

first thanx to Peter for this really nice piece of software!!!

Like brycepg says it would be really nice to have such a Widget as an standard component. I am quite new to ascimatics an it would be quite time consuming to create a new Widget.

Nice would be a Console like widget, where you just can add text (with attributes like bold, unterline, colour and so on) which is printed to a text panel, using line wrapping, linefeed an so on.

Kind Regards
Andreas

**Comment by peterbrittain** [comment]
Implementation for a multi-column list is now available in the master repo...  Just need to update tests and tweak docs.

**Comment by peterbrittain** [comment]
I've now documented use of readonly TextBoxes and provided a clearer example in top.py.

**Comment by peterbrittain** [comment]
Sourcing vector maps has some licensing issues, so I've implemented the Map as a sample Effect as part of https://github.com/peterbrittain/asciimatics/commit/46aac574877c9012c26277c3bdfef8dd2f61c7d1.

**Comment by zgoda** [comment]
A `Label`-like widget that allows setting text content in runtime.

**Comment by peterbrittain** [comment]
Rather than support a dynamic tree, I've created a simplified file browser as a variant of a multicolumn list.

**Comment by peterbrittain** [comment]
Now added date and time picking widgets in latest master build.

**Comment by peterbrittain** [comment]
This has been a dumping ground for too long - now closing and opening new issues for remaining widget ideas.

**Comment by peterjschroeder** [comment]
I apologize for posting on this closed issue, but I don't see the Dynamic Tree View widget issue opened elsewhere. I would be interested in this feature for a few of my projects.

**Comment by peterbrittain** [comment]
That's OK.  

I haven't created a standalone TreeView as such - which is why it didn't get crossed out on this list.  However, I did create the FileBrowser, which (obviously) has to traverse a tree-like structure.  The same logic could be used to traverse any tree with a little effort.

I don't have any plans to write a fully nested tree-view like this (https://docs.microsoft.com/en-us/windows/desktop/controls/tree-view-controls) as it is a lot of effort and I don't have the time for that investment (and I don't need it).  That said, I'd be happy to help someone else develop that widget...

**Comment by peterjschroeder** [comment]
Thank you for the response. I can probably hack something together using the FileBrowser as a base. I just wanted to make sure I wasn't duplicating any efforts.
