### ISSUE TITLE
Mouse events not working with Win XP and QuickEdit mode

### ISSUE THREAD

**Issue by norok2** [peterbrittain/asciimatics#33]
Hi,

As per title, the mouse events gets inhibited in Win XP when QuickEdit mode is active.
It should be possible to inihibit this behavior programmatically through [get/set]ConsoleMode and ENABLE_QUICK_EDIT_MODE. Possibly this needs to be done before entering the main loop and should set it back on exit. A big plus would be to enable/emulate clipboard events during the lack of quick edit mode.

BTW: thanks for sharing such an awesome project :-)

**Comment by peterbrittain** [comment]
Thanks for using it!  I really didn't expect it to get this level of interest when I started...

As for youe bug?  That also reproduces on Windows 7.  Looks like pywin32 is missing some constants, though, so I've had to code them in directly...  This patch looks to do the trick: https://github.com/peterbrittain/asciimatics/commit/88458fb882b321be30dc15318246f96c02793ce4

You can actually re-enable quickedit mode at any time by going into your command prompt settings, so it's not perfect and I should add a troubleshooting section to address this.  Doing more is going to require mouse drag facilities, which I've not added yet (but is on the queue for V2.0).

Can you please confirm that this patch works for you?  Then I'll update the docs and close...

**Comment by norok2** [comment]
Confirmed! ;-)

**Comment by peterbrittain** [comment]
Fab! Now documented and closed...
