### ISSUE TITLE
Drop python 2 support

### ISSUE THREAD

**Issue by pgajdos** [peterbrittain/asciimatics#347]
Please consider to drop mock from requirements.

**Comment by pgajdos** [comment]
E. g.
https://build.opensuse.org/package/view_file/home:pgajdos:python/python-asciimatics/python-asciimatics-no-mock.patch
or wrap with ImportException and fallback to old in case you want to support old pythons.

**Comment by peterbrittain** [comment]
Yeah - it's about time I dropped python 2...  should result in various tweaks to the code that make it a little cleaner.

I'll publish the current version on master and then remove python 2 on the next release.

**Comment by peterbrittain** [comment]
It's official... v1.14 is now released. I shall be dropping python 2 and generally tidyng up the code in master for te next release.

**Comment by peterbrittain** [comment]
Ok...  Just to keep the bot happy, I'll mark this as an enhancement.
