### ISSUE TITLE
Fatal Error when Multiple Frames in a scene with widgets

### ISSUE THREAD

**Issue by jameswhiteguitar** [peterbrittain/asciimatics#353]

**Comment by jameswhiteguitar** [comment]
If you run the StackBootstrap_TUI.py file and click on start configuration, it will bring you to our main page, which is where we are experiencing the inability to move the focus from frame to frame using the keyboard.  I am sure that our code is not the cleanest, we may not be configuring scenes in the most efficient way as well.  As for resolving the frame-switching issue, is that something that you would add or we would have to do on our end?
[BuggedTUI.zip](https://github.com/peterbrittain/asciimatics/files/8824966/BuggedTUI.zip)

Thank you for your help.

**Comment by peterbrittain** [comment]
It's a bug in asciimatics where it doesn't expect a Frame to have no current widget.  I'll sort a fix for this.
