### ISSUE TITLE
Custom subprocess integration

### ISSUE THREAD

**Issue by brd002** [peterbrittain/asciimatics#358]
Hi,
I have a library function that runs a shell command via `subprocess.Popen` and print dots if command is executed but ouputs nothing to stdout.
To run an interactive shell command, i use [terminal.py](https://github.com/peterbrittain/asciimatics/blob/master/samples/terminal.py). But this example also uses `subprocess`.
Is there a way to integrate the library function and example code using the built in ascimatics function, or maybe you can give me some advice if possible?

**Comment by peterbrittain** [comment]
Hmmm...  Libraries shouldn't really make assumptions about the environment like that.

My guess is that the easiest thing to do would be to run the shell command directly.  If you have to use the library, you need to explain better what is wrong.  Printing dots is putting stuff to stdout (in the parent process).  I assume that this is deliberate and the library is purposely doing it while swallowing any stdout from the child.

Sounds to me like you want the child stdout, but the library doesn't give you access to it.  If so, I'm afraid you have to change the library.

**Comment by brd002** [comment]
Thank you for your answer, i suppose the library should be changed.
