### ISSUE TITLE
Content isn't removed even upon update, once "drawn" on the screen

### ISSUE THREAD

**Issue by imdaveho** [peterbrittain/asciimatics#37]
If I run `screen.print_at('hello', 0, 0)` and then update the line to `screen.print_at('drop', 0, 0)`, the output would be `dropo` since the 'o' had already been printed.

What is the best way to clear the line or the content? Overwrite it with whitespace before rendering the new content, or is there a method I'm not aware of? (I tried calling `screen.clear()`), but if I wanted to do anything with key strokes--like backspace, for example--the response rate is janky.

**Comment by peterbrittain** [comment]
Yeah - I could believe that calling clear will be slow as it ensures that the screen and the double buffers are fully reset.  I would suggest overwriting the "o" with whitespace in V1.x.

I've been thinking about the niggles in cases like this for V2.x as part of https://github.com/peterbrittain/asciimatics/issues/24, but that's not going to happen in the short term

**Comment by peterbrittain** [comment]
I'm assuming this is now answered....
