### ISSUE TITLE
Mouse Events in Win11

### ISSUE THREAD

**Issue by djtorrey** [peterbrittain/asciimatics#370]
**Describe the bug**
I checked and double checked the documentation - it sounds like it should work with Windows pretty much out of the box - I can confirm that I am currently getting Mouse Events in Ubuntu and Fedora terminals, but I don't seem to be receiving any Mouse Events using the windows 11 command line, powershell, or bash terminal.  I'm not sure if something has changed between Win 10 and Win 11 in the console implementation

**To Reproduce**
Check get_events() in Win 11 Console

**Expected behavior**
Mouse events should be detected / received

**Screenshots**
![image](https://github.com/peterbrittain/asciimatics/assets/29438357/7e65d97b-0159-4ba8-9c30-a57fa7c9a6ad)

in the image, on the left-hand side you see the windows cmd instance running with no mouse event detected (should replace the text diag).  On the righthand side you can see the same code running on Fedora that clearly shows the mouse event on click

**System details (please complete the following information):**
 - OS and version: Win11
 - Python version: 3.11.3
 - Python distribution: Direct download from python.org
 - Asciimatics version 1.14

**Additional context**
Like I said, I'm not sure if I'm overlooking something simple, but the get_event() code is clearly working in Ubuntu and Fedora, but does not seem to react in the slightest against Win 11 console

**Comment by peterbrittain** [comment]
Have you tried the troubleshooting advice? 
See  https://asciimatics.readthedocs.io/en/latest/troubleshooting.html#mouse-support-not-working

**Comment by djtorrey** [comment]
hey thanks for responding back so quickly.  only thing I see there for windows is QuickEdit mode which I'll be honest, I'm not familiar enough with it to know where that is found and to verify it is disabled.  I haven't explicitly turned it on, so if it defaults to False I'm not sure for Windows what the next steps would be

**Comment by djtorrey** [comment]
looks like we're split between here and gitter so just to keep things tracking here i'll say I tried to disable QuickEdit so far to no avail - continuing to experiment with potential issues

**Comment by djtorrey** [comment]
for fucu
