### ISSUE TITLE
Can we donate to the project via Paypal?

### ISSUE THREAD

**Issue by GHExplorer** [peterbrittain/asciimatics#375]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example: "I'm always frustrated when [...]"

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by peterbrittain** [comment]
That's a very kind offer, but there really is no need.

**Comment by GHExplorer** [comment]
Just feeling grateful.  Been searching in vain for a tool that works naturally and right out of the box, within depending on things like ansi sequences.

Looking forward to playing with this more, over the weekend.

**Comment by peterbrittain** [comment]
Yeah - it's a bit of a minefield trying to handle cross-platform terminal input and output with unicode and colours...  Glad you like it.  

Fill your boots!! :-)
