### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [peterbrittain/asciimatics#377]
Now that the Python 3 pull request has been merged (thanks!), what is your plan for a new release?

**Comment by peterbrittain** [comment]
I usually wait until there is a critical mass of changes and then publish.  

In this case, I'd like to think about any other internal changes now that Py2 support is gone.  I think there are several new idioms that need fixing up IIRC.

**Comment by peterbrittain** [comment]
Getting there... Just thinking about the llast open PR.

**Comment by peterbrittain** [comment]
1.15.0 is now released!
