### ISSUE TITLE
Support multi-line text rolling in a rect

### ISSUE THREAD

**Issue by Daniel-Chin** [peterbrittain/asciimatics#382]
**Is your feature request related to a problem? Please describe.**
This feature would enhance UI capabilities. 

**Describe the solution you'd like**
An interface such as `Screen.print_rolled_text_at(text: str, x: int, y: int, w: int, h: int, do_clip: bool)`

**Describe alternatives you've considered**
I implemented [my own text rolling util](https://github.com/Daniel-Chin/Python_Lib/blob/main/graphic_terminal.py#L120). Feel free to copy. It even considers CJK char width...

**Additional context**
Text rolling is infamously non-trivial, so I'd like an in-library implementation. Pain points:
- CJK char width. 
- Right-to-left languages. 
- When to insert hyphen automatically. 
- A "greedy" approach results in ugly results. Sometimes, to aesthetically distribute multi-line text requires jointly optimizing the content of each line, inherently an O(n^n) problem. (I don't have reference for this but I remember seeing a YouTube video on this topic...)

**Comment by peterbrittain** [comment]
Thanks for getting in touch.  Can you explain your thinking a lttile more?

In particular, how are you trying to use this function and have you tried any of the options already available in asciimatics:

- Textbox with wrapped text
- The underlying code used for the wrapping (widgets.utilities._enforce_width)

I think that they cover your existing rollText implementation...

**Comment by Daniel-Chin** [comment]
Thank you for paying attention! 

With the help of your reference, I see that `widgets.utilities._split_text()` perfectly implements my request. Good work, and thanks greatly for making this library available!

**Comment by peterbrittain** [comment]
Great! And thanks!!
