### ISSUE TITLE
The effect of selecting the check box in version 1.15.0 is different from that in version 1.14.0

### ISSUE THREAD

**Issue by nitsort** [peterbrittain/asciimatics#383]
**Describe the bug**
After upgrading to version 1.15.0, I found that the checkbox style when selected is different from before. Is this a problem?

**To Reproduce**
https://github.com/peterbrittain/asciimatics/blob/master/samples/forms.py

**Expected behavior**
Same as version 1.14.0.

**Screenshots**
#### CheckBox [v1.15.0]
![image](https://github.com/peterbrittain/asciimatics/assets/23069540/0dcfe525-8481-4217-b4cd-bf97b71a9773)
#### CheckBox [v1.14.0]
![image](https://github.com/peterbrittain/asciimatics/assets/23069540/c5f2762d-9ef3-419f-939c-6bfb004cd608)

**System details (please complete the following information):**
 - OS and version: [Linux]
 - Python version: [docker-python:3.8.17-buster]
 - Python distribution: [CPython]
 - Asciimatics version [1.15.0]

**Additional context**

**Comment by peterbrittain** [comment]
Well spotted!  That was a bug in the new f strings as I  moved to Python 3.  It's just a minor visual bug and doesn't affect any function.
