### ISSUE TITLE
Screen resizing doesn't update screen.height/screen.width

### ISSUE THREAD

**Issue by imdaveho** [peterbrittain/asciimatics#39]
Currently, when resizing the terminal/console window, the Screen doesn't update its width/height.

```python
def demo(screen):
    while True:
        if screen.width < 80 or screen.height < 24:
            if screen.has_resized():
                # just checking:
                print('needs resizing') # doesn't get called if screen is already > 80 x 24
                print(screen.width)     # doesn't change
                print(screen.height)    # doesn't change
            message = 'Resize window to at least 80(w)x24(h)'
            screen.print_at(message, screen.width//2 - len(message)//2, screen.height //2 -3)
        
        else:
            if screen.has_resized():
                # just checking:
                print('size OK')        # doesn't get called if screen is < 80 x 24
                print(screen.width)     # doesn't change
                print(screen.height)    # doesn't change
            screen.print_at('Resized!', 0, 0)

        screen.refresh()

Screen.wrapper(demo)
```

**Comment by peterbrittain** [comment]
As you will see in all of the samples, you can handle resizing by creating a new Screen object.  The bars demo (https://github.com/peterbrittain/asciimatics/blob/master/samples/bars.py) in particular shows how to handle resizing for a desired size.

I get that this isn't ideal, but the knock-on impact on the other objects that need to be resized and re-positioned means that you effectively go through the whole initialization sequence again.  I have been thinking about changing this, but it will radically change the implementation and so will almost certainly not be back compatible.  See https://github.com/peterbrittain/asciimatics/issues/24.

**Comment by peterbrittain** [comment]
I've updated the docs (see https://github.com/peterbrittain/asciimatics/commit/bb6ce87f58b75ecaa44f568108ef55b90ea34dce) to try to address this confusion.  

Am assuming that this covers it.  Please let me know if there was anything else that could help clarify it further.

**Comment by lduczmal** [comment]
This way cannot be used with 
```
screen.print_at(...)
screen.refresh()
```
screen.refresh() does not have argument stop_on_resize

**Comment by peterbrittain** [comment]
@lduczmal If you are not using the `Screen.play()` method you have full control of when things happen in your application and you can just call `Screen.has_resized()` to see if things have changed whenever you like.

**Comment by lduczmal** [comment]
Thank you for you answer. 
Problem is that `Screen.has_resized()` seems to do not work... I create such simple script which open new terminal windows and shows current screen dimensions, some changing value and info whether screen dimensions was changed. Maybe I make something wrong, but printed dimensions will not change when I change terminal window size during script is running. One note: I run it on Windows 10 and on Python downloaded from www.python.org/downloads
```
from asciimatics.screen import Screen
from asciimatics.exceptions import ResizeScreenError
import time

screen_changes = []
screen_changes.append("start")

def demo(screen):
    x = 0
    while True:
        x += 1
        mytext = "[Screen height: {0}, width: {1}] changing value: {2}".format(screen.height,screen.width,x)
        mytext2 = "Screen was resized? {0}".format(Screen.has_resized(screen))
        screen_changes.append(Screen.has_resized(screen))
        screen.print_at(mytext, 1, 1, colour=7, bg=0)
        if Screen.has_resized(screen):
            screen.print_at(mytext2, 1, 2, colour=1, bg=0)
        else:
            screen.print_at(mytext2, 1, 2, colour=2, bg=0)
        ev = screen.get_key()
        if ev in (ord('Q'), ord('q')):
            return
        screen.refresh()
        time.sleep(0.5)

Screen.wrapper(demo)
print(screen_changes)
sys.exit(0)
```    
Best regards

**Comment by peterbrittain** [comment]
@lduczmal That's because has_resized is not a static method, you just need to call `screen.has_resized()`.  Note that this only guarantees to check if there has been a resize since the last time you checked.  For Windows, it will continue to tell you on each call, but that's not a cross-platform guarantee and so you should fix your code.  What should work is this:

        mytext2 = "Screen was resized? {0}".format(screen.has_resized())
        screen_changes.append(mytext2)

**Comment by lduczmal** [comment]
@peterbrittain Hi, thank you - now it works! almost... ;-) When I'm resizing terminal window during script run it sometimes returns to previous dimensions... 
My code:
```
from asciimatics.screen import Screen
from asciimatics.exceptions import ResizeScreenError
import time
import sys

screen_changes = []
screen_changes.append("start")
quit_script = False
x = 0
def demo(screen):
    global quit_script
    global x
    while True:
        x += 1
        mytext = "[Screen height: {0}, width: {1}] changing value: {2}".format(screen.height,screen.width,x)
        #screen_changes.append(screen.dimensions)
        screen.print_at(mytext, 1, 1, colour=7, bg=0)
        if screen.has_resized():
            return
        ev = screen.get_key()
        if ev in (ord('Q'), ord('q')):
            quit_script = True
            return
        screen.refresh()
        time.sleep(0.5)

k = 0
while not quit_script:
    Screen.wrapper(demo)
    time.sleep(0.5)
```
I have one more question: function `demo `in code above has the only one argument screen. What about situation if I would like to add others arguments to this function and how use wrapper to pass additional params to function `demo`

**Comment by peterbrittain** [comment]
Quick answers are that I think you're hitting a race condition in the Windows Console where you are delaying any processing for half a second.  Simply removing this delay prevents the issue.  And look at the samples for how to use the `arguments` parameter on wrapper to pass in other parameters to thde `demo` function.

Finally, could I ask that you please continue any questions in Gitter instead of in this closed issue?  For example, go to: https://gitter.im/asciimatics/Lobby
