### ISSUE TITLE
screen.get_event() getting an event when none is happening.

### ISSUE THREAD

**Issue by zhilothebest** [peterbrittain/asciimatics#40]
Explained on stack, but would love to get this fixed.

http://stackoverflow.com/questions/38966945/asciimatics-get-event-saying-a-keyboard-event-happened-when-none-did-python

**Comment by ohhorob** [comment]
Did you just delete this question?

At any rate, I suspect you're getting a timeout event while waiting for keyboard input.

**Comment by zhilothebest** [comment]
I did just delete it, because I just figured out my issue. Thank you!
