### ISSUE TITLE
Just installed asciimatics and i get error on all the examples i try.

### ISSUE THREAD

**Issue by xzenon12** [peterbrittain/asciimatics#41]
Just installed asciimatics on windows 10 and i get error on all the examples i try.
I did pip install asciimatics and Everything Went fine but when i tried the examples out i get lots of errors i dont know if i am missing something.

the error i get is. its almost the same in all the examples.

```
Traceback (most recent call last):
  File "C:\Users\xzenon\Desktop\asciimatics-master\asciimatics-master\samples\pacman.py", line 532, in <module>
    Screen.wrapper(demo)
  File "C:\Users\xzenon\AppData\Local\Programs\Python\Python35-32\lib\site-packages\asciimatics-1.6.0-py3.5.egg\asciimatics\screen.py", line 988, in wrapper
    unicode_aware=unicode_aware)
  File "C:\Users\xzenon\AppData\Local\Programs\Python\Python35-32\lib\site-packages\asciimatics-1.6.0-py3.5.egg\asciimatics\screen.py", line 897, in open
    None))
pywintypes.error: (6, 'CreateFile', 'Referensen (handle) är felaktig.')
```

**Comment by peterbrittain** [comment]
From the line numbers, you are running thae latest development version of the code...  That error indicates that Windows thinks there is an invalid handle, but you should be using a process with an active console and so the following applies...

> The CreateFile function can create a handle to console input (CONIN$). If the process has an open handle to it as a result of inheritance or duplication, it can also create a handle to the active screen buffer (CONOUT$). The calling process must be attached to an inherited console or one allocated by the AllocConsole function. For console handles, set the CreateFile parameters as follows.

Are you running inside a console window, or from some other program - e.g. an IDE or editor?

**Comment by xzenon12** [comment]
The errors appers in the python ide it seems to work fine in the console.

**Comment by peterbrittain** [comment]
Well, that's expected then.  Most IDEs don't actually provide a real  console session.

I've just updated the troubleshooting guide to cover more than PyCharm and so believe this issue is closed.  Please shout if you think there's more required here.
