### ISSUE TITLE
StopApplication

### ISSUE THREAD

**Issue by Soroboruo** [peterbrittain/asciimatics#42]
I can't manage to find a way to stop screen.play(scenes) to play the list indefinitely.
I dont want the user to have to press x or q  to exit the animation .
I think i have missed something in the doc .
Can you help me ?

**Comment by peterbrittain** [comment]
Can I just check what you're trying to do...

If I understand correctly, you have a set of Scenes that you want to play through once from start to finish and then exit Screen.play() without repeating them.  Is that right?  If so, all you need to do is raise StopApplication() at the required time (frame) in your last Scene.

Ah, but there is no easy way to do that...  Right now, you would have to do that from inside one of your Effects.

I could add a `repeat` parameter to play(), which would determine if it loops after the last Scene is over.  Or I could add an API to Scene to allow you to add custom logic to any frame update (and so allow you to raise StopApplication at any point you like as a Scene progreses).

Would either of those be helpful?

**Comment by Soroboruo** [comment]
In my case i think the repeat param would be awesome ^^)
Anyway  I use to append some "string" in the list at the end to catch an error and then continue with my script but thnks for the answer now i understand where to look at :)

Great work by the way !

**Comment by peterbrittain** [comment]
Thanks!  I've now added a simple repeat flag to play (see https://github.com/peterbrittain/asciimatics/commit/328d957b7d278efc827d41e6afb9af5bff34dd3a).  This will be available from V1.7.
