### ISSUE TITLE
KeyboardEvents Question

### ISSUE THREAD

**Issue by overk1ll** [peterbrittain/asciimatics#43]
Hello,

I'm a little new to python, and trying to figure something out. I was wondering if you could give more examples of the KeyboardEvent class. Specifically, I was looking to generate an animation on any type of key press, such as a firework. Thanks!

**Comment by peterbrittain** [comment]
Sure...  Which samples have you already had a look at?

**Comment by overk1ll** [comment]
fireworks.py, specifically the for loop on line 21.

**Comment by peterbrittain** [comment]
OK.  In which case, you might want to have a look at https://github.com/peterbrittain/asciimatics/blob/master/samples/interactive.py to see how to process KeyboardEvents.  You could then use something like the http://asciimatics.readthedocs.io/en/latest/widgets.html#global-key-handling to act on a specific key to add a new Effect to your active Scene.

**Comment by overk1ll** [comment]
I have tried that before, but my not very good python skills seem to be
hampering making it work. I'm basically trying to replicate code similar to
this:

http://pastebin.com/ix8W8NQw

And to then generate a random effect (or firework) for any keypress. How
could I do that with your sample using the keyboard event class? Or would
there be another way?

**Comment by peterbrittain** [comment]
Your pastebin code simply waits for enter and then prints a random character.

If you want to do something like that, just change the "hello world" sample from the readme.  For example:

    from asciimatics.screen import Screen

    def demo(screen):
        while True:
            ev = screen.get_key()
            if ev in (ord('Q'), ord('q')):
                # put your code here to play a random Effect

    Screen.wrapper(demo)

This will play a random effect every time you press 'q'.

**Comment by overk1ll** [comment]
So this code below does closer to what I am looking for, modifying the
hello world example.

http://pastebin.com/U7NMYHVJ

However, when I run the below code no animation plays at all:

http://pastebin.com/AKE7UGM0

Is there something else I need to do before the effect.insert to have it
play correctly?

**Comment by peterbrittain** [comment]
You're not playing the effects.  You need to call `play()` (making sure that `repeat=False` so that it exits) passing in a Scene which contains your chosen effect (and an end frame).

**Comment by overk1ll** [comment]
Thanks again so much for the guidance, again excuse my noobishness.

**Comment by peterbrittain** [comment]
No problem!  I assume that you've now got something running and so will close this issue.

BTW, if you like this project, don't forget to star it!
