### ISSUE TITLE
Linux install requiring pypiwin32

### ISSUE THREAD

**Issue by BillScherer** [peterbrittain/asciimatics#47]
# pip3.5 install setuptools_scm
Collecting setuptools_scm
/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
  Downloading setuptools_scm-1.11.1-py2.py3-none-any.whl
Installing collected packages: setuptools-scm
Successfully installed setuptools-scm-1.11.1
root@oblxrhcprd-ap0.odc.vzwcorp.com-/root/scherbi # pip3.5 install asciimatics
Collecting asciimatics
  Using cached asciimatics-1.7.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): future in /usr/local/lib/python3.5/site-packages (from asciimatics)
Requirement already satisfied (use --upgrade to upgrade): pyfiglet>=0.7.2 in /usr/local/lib/python3.5/site-packages (from asciimatics)
Requirement already satisfied (use --upgrade to upgrade): Pillow>=2.7.0 in /usr/local/lib/python3.5/site-packages (from asciimatics)
Collecting pypiwin32 (from asciimatics)
  Using cached pypiwin32-219.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3_afj4p1/pypiwin32/setup.py", line 121
        print "Building pywin32", pywin32_version
                               ^
    SyntaxError: Missing parentheses in call to 'print'

**Comment by peterbrittain** [comment]
Damnit!  Looks like building the package on Windows was a bad idea...  I'll try to fix that later today.

In the meantime, a temporary workaround is just to clone the repository, build the package (e.g. run `python setup.py bdist_wheel --universal`) and then install from that built package.

**Comment by peterbrittain** [comment]
Should now be fixed with v1.7.1 package uploaded to pypi a few minutes ago.
