### ISSUE TITLE
asciimatics works under PyPy2

### ISSUE THREAD

**Issue by TiberiumN** [peterbrittain/asciimatics#49]
Actually it doesn't work with the latest release of PyPy2 (PyPy2 v5.6.0) because of (now resolved) https://bitbucket.org/pypy/pypy/issues/2425/str-error-from-future-module-in-pypy2, but works with latest trunk release http://buildbot.pypy.org/nightly/trunk/ .
Just wanted to inform you :)

**Comment by peterbrittain** [comment]
Thanks for the update!  I'll wait for an official release and check it still works...

**Comment by TiberiumPY** [comment]
@peterbrittain I think it would be in January (But I'm not sure)

**Comment by TiberiumN** [comment]
@peterbrittain the release is here!

**Comment by peterbrittain** [comment]
Great!  I've just tried installing on CentOS and it worked fine...  

Sadly it looks like it's a bit of an issue on Windows, though.  Pywin32 does not yet support pypy: https://sourceforge.net/p/pywin32/feature-requests/83/

**Comment by peterbrittain** [comment]
Now documented!

**Comment by TiberiumN** [comment]
@peterbrittain also you may try it on PyPy3.5.
just use https://github.com/squeaky-pl/portable-pypy
for any linux distro x86_64

**Comment by peterbrittain** [comment]
Sadly it looks like Pillow is incompatible with pypy3.  Despite the fact that I know I have zlib installed and have successfully used it on pypy2 and cpython, I get an install failure running `pip install pillow` on pypy3.

**Comment by TiberiumN** [comment]
@peterbrittain it was for me to, it may be a pillow issue too...

**Comment by peterbrittain** [comment]
Looks like something very strange in pypy3.  I did a little debugging and got the following output:

```
Looking for zlib
Checking for include file zlib.h in /tmp/pip-build-wg4fbq36/pillow/libImaging
Checking for include file zlib.h in /tmp/pip-build-wg4fbq36/pillow
Checking for include file zlib.h in /usr/include/freetype2
Checking for include file zlib.h in /root/pypy3.5-5.7-beta-linux_x86_64-portable/include
Checking for include file zlib.h in /usr/local/include
Checking for include file zlib.h in /usr/include
Found zlib.h
Couldn't find library z in ['/tmp/pip-build-wg4fbq36/pillow', '/root/pypy3.5-5.7-beta-linux_x86_64-portable/lib', '/lib64', '/usr/lib64', '/usr/local/lib', '/usr/lib', '/lib']
```

So the problem is that it can't find libz.so in /usr/lib64, which is a shame.  Running the Pillow setup manually with some extra debug, I find that pypy is actually doing this:

```
Using <distutils.unixccompiler.UnixCCompiler object at 0x00007f16f9e47590>
Looking for libz.pypy3-57-x86_64-linux-gnu.so using lib%s%s .pypy3-57-x86_64-linux-gnu.so
```

Looks like someone is mucking around with the shared object extension somehow.

**Comment by peterbrittain** [comment]
And it looks like this is a known issue - see https://github.com/python-pillow/Pillow/issues/2378
