### ISSUE TITLE
Where to find the code of matrix example?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [peterbrittain/asciimatics#50]
I like that matrix effect: https://asciinema.org/a/19942

but where is the code for it?

**Comment by peterbrittain** [comment]
You want the `Matrix` effect.  This is documented here: http://asciimatics.readthedocs.io/en/stable/asciimatics.html#asciimatics.effects.Matrix

The sourcecode is here: https://github.com/peterbrittain/asciimatics/blob/master/asciimatics/effects.py

**Comment by Tset-Noitamotua** [comment]
Great! Thank you!

bwt. I assumed to find it in samples folder. It is kind of like hidden in the jungle ;-)
Why don't you put a link under your video (https://asciinema.org/a/19942).

**Comment by Tset-Noitamotua** [comment]
this link thows you directly to the Matrix effect: https://github.com/peterbrittain/asciimatics/blob/master/asciimatics/effects.py#L533
