### ISSUE TITLE
Docs update for Windows users

### ISSUE THREAD

**Issue by Tset-Noitamotua** [peterbrittain/asciimatics#51]
> Additionally, Windows users will need to install pypiwin32.

Seems that it is not needed to add pypiwin32 manually as it is installed automatically

```
Collecting pypiwin32; sys_platform == "win32" (from asciimatics)
  Downloading pypiwin32-219-cp35-none-win32.whl (7.9MB)
```

Windows 7

**Comment by peterbrittain** [comment]
Thanks for getting in touch.  Those instructions are explicitly for people who don't use `pip`.  I'll clarify...
