### ISSUE TITLE
Determining code for keyboard shortcut

### ISSUE THREAD

**Issue by rubik** [peterbrittain/asciimatics#52]
I couldn't find in the docs how one determines the code of a keyboard shortcut. There's one example where it is said that Ctrl+Q and Ctrl+X are 17 and 24. But how does one calculate these from the constants in Screen (`KEY_CONTROL`, etc.) and the ASCII code of the letters?

I want to detect Ctrl+u, which apparently is 21, but `Screen.KEY_CONTROL + ord('u')` and `Screen.KEY_CONTROL & ord('u')` give different results. I also realized that the latter cannot work because it will give the same code for different shortcuts.

**Comment by peterbrittain** [comment]
The control codes can be calculated from the position in the alphabet.  For example, `ctrl+a` is 1, `ctrl+b` is 2, etc.  This dates back to the early days of keyboards - see https://en.m.wikipedia.org/wiki/Control_key

In ASCII terms, you can take 96 off the value of the lower case letter (ignoring the ctrl key).  Using the same example, `ctrl+a` would be `ord('a') - 96` which is `97 - 96` which is `1`.

This is clearly not obvious, so I'll have a think about how best to represent this inthe API.

**Comment by peterbrittain** [comment]
Feels like something like https://docs.python.org/3/library/curses.ascii.html#curses.ascii.ctrl might be helpful.  Either that, or I can just put some constants in there...

**Comment by rubik** [comment]
I think having some helper functions is definitely good. It's also more readable in my opinion.

**Comment by peterbrittain** [comment]
OK - I've now added that helper function and documented how to use it as part of https://github.com/peterbrittain/asciimatics/commit/ef49721e97bab86c0a2ce64e908117f08468c658

Now closing.
