### ISSUE TITLE
Startup performance seems pretty bad

### ISSUE THREAD

**Issue by boxed** [peterbrittain/asciimatics#54]
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    169/1    0.018    0.000    6.608    6.608 {built-in method builtins.exec}
        1    0.000    0.000    6.608    6.608 downloader.py:1(<module>)
        1    0.000    0.000    6.346    6.346 downloader.py:137(gui)
        1    0.000    0.000    6.311    6.311 screen.py:974(wrapper)
        4    0.002    0.001    5.438    1.359 screen.py:343(reset)
1225606/806    2.366    0.000    5.433    0.007 copy.py:132(deepcopy)
 1604/804    0.192    0.000    5.426    0.007 copy.py:210(_deepcopy_list)
        1    0.000    0.000    4.942    4.942 downloader.py:219(demo)
   244800    0.963    0.000    4.380    0.000 copy.py:219(_deepcopy_tuple)
        1    0.000    0.000    3.393    3.393 screen.py:1108(play)
   244800    0.604    0.000    3.366    0.000 copy.py:220(<listcomp>)
        2    0.000    0.000    2.847    1.423 screen.py:313(__init__)
        4    0.002    0.000    2.821    0.705 screen.py:352(<listcomp>)
        1    0.000    0.000    2.591    2.591 screen.py:1154(set_scenes)
        1    0.000    0.000    1.549    1.549 downloader.py:177(__init__)
        1    0.000    0.000    1.482    1.482 widgets.py:108(__init__)
        1    0.000    0.000    1.482    1.482 screen.py:715(__init__)
        1    0.000    0.000    1.380    1.380 scene.py:33(reset)
        1    0.000    0.000    1.380    1.380 widgets.py:407(reset)
        1    0.000    0.000    1.368    1.368 screen.py:877(open)
```

There's something fishy going on I think. This is a profile of me starting my super simple app and hitting ctrl+c as soon as I see the GUI.

**Comment by peterbrittain** [comment]
Interesting...  I am already aware that the initial object creation is slow.  When I looked into it, Python was being very slow creating the array of tuples for the screen double buffers.  The larger your screen, the slower it gets.  Have you got a large screen by any chance?

As for fixing it?  I guess I could try optimizing the use of deepcopy to create the buffers, but I'm not sure how much I'll be able to improve it without falling back on optimized structures with Numpy or native code, which just feels like overkill for this package.

**Comment by peterbrittain** [comment]
Looks like some techniques in here might help improve things: http://stackoverflow.com/questions/24756712/deepcopy-is-extremely-slow.

**Comment by boxed** [comment]
Why do you use tuples and deepcopy for buffers? Seems like mutable data structures would be much faster and maybe even easier to work with?

**Comment by peterbrittain** [comment]
Purely historical reasons.  All the manipulation post start-up is trivial either way and much faster than the initialization.

**Comment by peterbrittain** [comment]
Looks like using the json trick increases performance by an order of magnitude, so I've formally checked that in as https://github.com/peterbrittain/asciimatics/commit/27e47a62a84c39030c54931d18c4a94875f006e7

I suspect that this is now fast enough, so now closing.

**Comment by boxed** [comment]
Cool. Super weird that that trick should work though!

**Comment by peterbrittain** [comment]
Yeah.  I guess when you repeat this all 244800 times, even pretty simple code as that used by deepcopy quickly adds up...

**Comment by boxed** [comment]
I just noticed that this little app I wrote is eating a constant 15% CPU when idling. Will this also be improved by this change?

**Comment by peterbrittain** [comment]
Nope.  I suspect what you're seeing there is this issue: https://github.com/peterbrittain/asciimatics/issues/35.  If so, the fix is to stop using animated cursors, which require a regular screen refresh and so use CPU even when idle.

This fix went in as https://github.com/peterbrittain/asciimatics/commit/b195ec1455a6ea87ea3179ec3e41e166aafc4dbf.  As you can see, you just specify `reduce_cpu=True` when constructing your Frames.

**Comment by peterbrittain** [comment]
Check out the discussion in the separate issue.  It's not well supported.
