### ISSUE TITLE
Background data updates

### ISSUE THREAD

**Issue by hectorvs** [peterbrittain/asciimatics#56]
Hello, I'm a new user of asciimatics and I'm struggling to find documentation on this particular use case. 

Maybe there's an enhancement opportunity or you can point me in the right direction.

#### Use Case:
I'm trying to display tabular data that gets updated in place. For example

Stack | Status
------------ | -------------
| stack1 | UPDATING |
| stack2 | ERROR |
| stack3 | FINISHED |

In this case, the STATUS column would be updated with the status corresponding to the stack.

The way the status are being checked is with a loop that's querying the stack and updating a data model (maybe this needs to be done on a separate thread?) with the status.

The ultimate goal is to display this data in a nice way, instead of printing a continuous list every time the service is queried.

**Comment by peterbrittain** [comment]
Hi.  Thanks for getting in touch.  I've had a quick think about this and have a couple of ideas...

First off, the sort of tabular display that you're hoping to create is exactly the sort of thing that I was expecting to be handled by the multi-column list widget in https://github.com/peterbrittain/asciimatics/issues/31.  Sadly that doesn't exist yet.  It shouldn't be too hard to create based on the existing ListBox, but I haven't done that yet and don't know when I'll get the time to do so.  In the meantime, you could try creating the new widget yourself (and I'd happily review any pull request), or approximating it by using the ListBox with some hacked formatting as you populate the data.

As for the updates in the background?  I think the issue that you're going to hit there is that my recent changes to reduce CPU usage mean that Frames don't redraw unless they think they need to do so.  You therefore have to force the refresh when your data changes.  Depending on how architectural you want to be, you could add a new method to Frame (e.g. force_update) that forces it to redraw next time asciimatics polls it for updates, or you could just hack frame_update_count to always return 1 - which will redraw the Frame on every refresh and so dynamically update as your model changes, but at the cost of a load of wasted CPU.  I've probably got time to put the forced refresh in sometime over the next week or so, if that helps...

**Comment by peterbrittain** [comment]
Just did a little more thinking on the background update...  I don't think my previous suggestion will work as it's actually the Screen that's idling until the time the Effects told it to redraw, so the hack will work, but the force_update needs to go on the Screen class.

**Comment by peterbrittain** [comment]
OK - I've added the force_update() API to Screen as https://github.com/peterbrittain/asciimatics/commit/46275ad793336c51c1066baf4b2c4aea38a6cfcb.  You should now be able to call this from anywhere in your application when you know your UI needs to be updated.  The only thing you need to do now is decide how you're going to represent your table.

**Comment by hectorvs** [comment]
Excellent, thanks for the response!

So, what I have so far to work with is a loop that calls an api every so often and monitors for changes (nothing too fancy yet). When it detects a change, it should run `force_update()`.

AFAIK, when you run the scene, it takes over the main thread of the program, correct?

This means that I will need to have a separate thread that will be running my monitoring loop and it should have access to the screen object in order to call the `force_update()` function.

**Comment by peterbrittain** [comment]
If you just use `play()` it will take over that thread and run a simple scheduling loop.  If you already have your own scheduling loop you can call `draw_next_frame()` instead every 1/20th of a second - as documented at the end of http://asciimatics.readthedocs.io/en/stable/animation.html#scenes-and-effects

**Comment by hectorvs** [comment]
I'm having a hard time using asciimatics, the documentation is not very clear on what the different attributes for the elements are and how they interact with each other.

here is my code so far

```
from asciimatics.screen import Screen
from asciimatics.scene  import Scene
from asciimatics.widgets import Frame, ListBox, Layout, Widget

import time

screen = Screen.open()

frame = Frame(screen,
              int(screen.height * 2 // 3),
              int(screen.width * 2 // 3),
              has_border=False)

layout = Layout([1])

frame.add_layout(layout)

layout.add_widget(ListBox(1,  [("foo", 1)],  label="test"))

scenes = [
    Scene([ frame ]),
]

screen.set_scenes(scenes)

while True:
    screen.draw_next_frame(repeat=True)
    time.sleep(0.05)
```

as you can see it's a very simple example that has a ListBox widget which is on a layout with 1 column set on a frame which is on a screen.

I'm using the `draw_next_frame` method you mentioned on a 1/20th of a second delay.

When running this sample code, I get a `list index out of range` error in the widgets.py file, and my mouse stops working on the terminal altogether (gibberish pops up when clicking, only solution is to close and reopen it) 

I'm not sure what I'm doing wrong.

When I remove the line to add the widget, a blue box appears on screen (the frame, I assume). When I press anything on the keyboard, it spits out a stack trace.

Could you give me some guidance?

**Comment by peterbrittain** [comment]
All looks pretty good so far...  There are 2 bugs I can see, though.

 1) You need to call frame.fix() before you start displaying it.  This is what allows triggers asciimatics to do the layout calculations.
 2) You should make sure you call Screen.close() to tidyup the terminal on exit.  I suggest you copythe logic in Screen.wrapper() here.

**Comment by peterbrittain** [comment]
Given that the enhancement is made, I'm going to close.  Please feel free to post a follow-up on the docs if needed...
