### ISSUE TITLE
threading with asciimatics

### ISSUE THREAD

**Issue by PeterMitrano** [peterbrittain/asciimatics#57]
First off, great library. Love it so far.

I'm trying to write a serial monitor program, and I need a way to update the text when new serial comes in. I have a function that I can check for available serial, and one that will read in data. Normally one would use something like this in a thread...

        while True:
            if ser.in_waiting > 0:
                waiting_data = ser.read(local_data.ser.in_waiting)
                print(waiting_data) # HERE I want to update asciimatics TextBox
            sleep(0)  # yield to thread scheduler

The problem is, asciimatics almost never sleeps, and so my thread only runs whenever I am Tabbing  around or typing. Any suggestions as to a better way to do this? Or how to make the asciimatics main loop yield?

**Comment by TiberiumPY** [comment]
Clearly https://github.com/peterbrittain/asciimatics/issues/56

**Comment by TiberiumPY** [comment]
https://github.com/peterbrittain/asciimatics/commit/46275ad793336c51c1066baf4b2c4aea38a6cfcb

**Comment by PeterMitrano** [comment]
Perfect. `force_update` it is.
