### ISSUE TITLE
Line-Wrap in textbox

### ISSUE THREAD

**Issue by PeterMitrano** [peterbrittain/asciimatics#58]
Does the textbox widget support line wrapping? I supposed I could subclass it and create it myself if it doesn't, but I though I'd ask first

**Comment by peterbrittain** [comment]
No.  The current implentation scrolls to the required location instead.  Sorry, but I don't expect to be able to add that soon.  Will happily take pull requests for this function, though.

**Comment by PeterMitrano** [comment]
OK cool. I'll do it and make a PR
