### ISSUE TITLE
Better support for up/down keys navigation

### ISSUE THREAD

**Issue by oldium** [peterbrittain/asciimatics#60]
It looks like the arrow keys navigation works, but not always - good example is forms.py. Navigating up with arrow key from the check-boxes goes through all elements and stops at the multi-line text edit. But when you go down, it does not go there, it stops on the last line of the multi-line text box. Also it is not possible to reach buttons on the bottom by using the down button from the last check-box. When being in the button layer, navigating left/right works, but not up arrow (to get the check-boxes).

Additional issue with up/down navigation is that the radio button selection is automatically changed when using the up/down key, but usual is that the state changes only when the SPACE bar is pressed on the active item.

Expected is that on up/down key moves the activation between elements in vertical-oriented elements group (with no automatic selection) and when horizontal-oriented elements group is reached, the last selected one is re-activated.

Please consider adding better support for up/down navigation.

I tested this on Windows 10 64bit (Anniversary Update), Python 3.6, asciimatics 1.7.2.

**Comment by peterbrittain** [comment]
I've been thinking abou this and am not sure what to do...  My inclination is to try to conform to accepted norms - i.e. see what existing native and web form inputs do and try to be as close to what they do.  This way there should be least surprise to users.  More detailed thinking follows...

At least some of this is deliberate.  Using arrows within a `Layout` is supported as it is easy to decide which `Widget` is desired.  However it is less obvious when moving between `Layouts`.  For example, which button should be selected when moving down out of the check-boxes?  The first?  Or the one closest to the current `Widget`?  Or the one that was last in use?  Neither is a clear winner to me, which is why I only allow Tabbing through these boundaries.

You could well be right that most radio buttons do require explicit selection, like check boxes.  I'll compare to standard examples out there for native and web UIs and try to conform to the norm.

Multi line edit was an interesting one...  Is it better to move out of the widget when you hit the boundary or not?  I could imagine people finding it irritating that they move out of the edit box as they try to navigate to the start/end of their text.  Again, I'll have a look at what other standard UIs do before changing this.

**Comment by oldium** [comment]
I checked Midnight Commander as a console-only application and it looks like up/down is simply moving focus like when using the tab, but it traverses all radio buttons (in the tab order) unlike the tab does. I would be happy with this behaviour.

**Comment by oldium** [comment]
Regarding multi-line edit - there could be an option to allow leaving the form by pressing the down button when being on the last line or not.

**Comment by peterbrittain** [comment]
OK, so I've had a look around too (more widely on native and web UIs) and:

1. Cursor keys on radio buttons don't just move the focus, they also change the selected option.  This is what asciimatics already does and so I don't propose to change this.
2. Tabbing into a radio button list just moves the focus to the current selected option in the list - which is what asciimatics already does.  Again no change.

I think that's what you said midnight commander also did, so I think we're clean here.  Please shout if I've missed something.

Looking at multi-line edit, all the examples I've found also limit you to the the text area once you move the focus into it.  The only way out is typically with a tab.  I'm not sure that this is expected navigation.  Do you have examples of other systems that allow you to drop straight out of a multi-line edit using the up and down keys?  I think it's possible to add this feature, but given how prevalent the existing function is, I wouldn't want to change the default for other users without a good precedent.

That leaves the navigation from Layout to Layout.  This is certainly the area I'm least satisfied with, but I've yet to find anything that does any better.  A quick play on bootstrap forms shows that use of grids pretty much disables any cursor key navigation.  More complex native forms quickly force you to tab round to get anywhere.  That said, if there's no great precedent for handling this, beyond using the TAB key, maybe I should just do what is easy and allow up/down keys to move between Layouts?

**Comment by oldium** [comment]
You are right regarding the radio buttons - the native applications move the selection with up/left/down/right arrows.

I checked MS Outlook configuration dialog and it behaves like the following:

  1. Keys up or left move focus to the previous item. Keys down or right move focus to the next item.
  2. When there is a special meaning for the key (i.e. the key event is eaten by the widget), the focus movement is disabled:
       a) Single-line text boxes - cannot be leaved with left/right, but could be with up/down.
       b) Multi-line text boxes - cannot be leaved at all.
       c) Radio buttons - cannot be leaved at all, cursor movement changes the selection immediately and does not allow you to leave the group.
       d) Combo boxes - cannot be leaved with up/down, because it operates the popup list. If combo box contain editable text, it cannot be leaved with left/right (because it changes cursor position inside the combo box).

Linux Qt4 (I checked examples in the qt4-demo application) shows very similar behaviour with one exception - single-line text box cannot be leaved with up/down keys (which do nothing).

Midnight Commander under Linux console is little bit different story here, it does not change the radio button selection at all, the movement is not limited, and for combo boxes there is a special key to open the popup list, which is different to cursor keys. Maybe I would just skip this as an irrelevant example.

So from the implementation point of view (not the user point of view) the behaviour of Windows and Qt4 looks logical to me - whenever the widget has a special meaning for the key (widget is also radio button group in this point of view!), let it eat the event. If the event is not consumed, do the focus change.

So I would do the same:

  1. Do not allow leaving the radio group, because you should change the selection inside the group with up/left and right/down keys, not jump out of the group.
  2. Between layers I would simply go to the first element (top left) in the forward-TAB direction, and to the last element (bottom right) in the reversed-TAB direction. This should be the easiest.

If somebody wants to jump to the closest-positioned column on the button down press between layers, he would need to tune the implementation in some derived class. This behaviour might be wanted only sometimes - for example in the movement between multiple different tables, but could not be wanted for movement to the last row of buttons with Save/Reset/Cancel actions - it always depends on the author's intention. From the API point of view it should be sufficient to have a method that allows the modification (with the possibility to get the currently focused element to know the positions).

**Comment by oldium** [comment]
One more note about the differences - in Windows and Qt4, the up/down keys in vertical layout move focus left/right actually (if not consumed).

**Comment by peterbrittain** [comment]
So, it's not one-size-fits-all...  But I guess I already knew that.

I think that the reproduction of the TAB logic is fine for moving between layers and could make radio buttons swallow all key up/down events to ensure that it's more consistent (no need for left/right as asciimatics enforces a vertical arrangement for radio buttons).  That's a simple set of changes.

However, I originally added the navigation out of radio buttons as it was irritating me in the demo that up/down worked for most other widgets.  I guess I could make it an option on the Frame to allow/disallow wider cursor key navigation for people who just don't care about the implementation and simply want to navigate the UI as fast as possible.  That might for slightly grungy code...  We'll see.

I don't think I want to provide a full-blown API for more esoteric navigation.  Once your into traversing Layouts, you could use a custom Frame implementation with its own event handler to replace the logic that currently handles up/down, etc.

**Comment by oldium** [comment]
Navigating out of radio buttons looks good at first sight, but it is good when you are just playing with the navigation. I wonder whether this will be really used (meant by the user, not by the tester/programmer) when actually _filling_ the form.

**Comment by peterbrittain** [comment]
Good point!  I've tweaked the navigation logic for Layout transitions and radio buttons as per the above discussion.  This patch (https://github.com/peterbrittain/asciimatics/commit/716fb48483f8cae98fb57ae867f8b56d680683b4) just provides the new logic.  

I'll have a think about providing an option for less restrictive cursor navigation, but given that this is now much more like standard form input out there, I'll probably just close at this point.

**Comment by oldium** [comment]
Looks good, thanks!

**Comment by peterbrittain** [comment]
Cool.  I've decided to stick with just the one way to navigate the forms, so am closing this issue.
