### ISSUE TITLE
Dropping in and out of standard console

### ISSUE THREAD

**Issue by ColinWaddell** [peterbrittain/asciimatics#62]
Hey,

Just wondering if there's a simple method of dropping out of a Frame back to the console, showing what ever's been printf-ed to there, and then returning back to the Frame.

The reason I ask is I've built an interface to some test software and what I'd like to happen is:

 - Use navigates to correct test
 - User presses test button
 - Asciimatic application drops back to console as test software runs
 - Any printf statements sent to stdout in the test software are seen in console
 - Software returns back to the Asciimatics application

Thanks for your time,
Colin

**Comment by peterbrittain** [comment]
In theory this is possible, but might be a little messy...  

The safest option is to stop asciimatics, close your Screen while the test is running and then open a new one after it has finished.  However, that means you need to reconstruct where you were before you closed the Screen.  You could re-use the resize infrastructure inside asciimatics to handle that - i.e. save your current Scene and use that as the start_scene when you re-open.

The other options get quite fragile after that...  Assuming you're running on Linux (or another curses system), you could just stop the Screen from playing temporarily - e.g. raise a StopApplication exception - and then use curses directly to switch between the normal and alternate screens, using the `smcup` and `rmcup` terminfo strings.  See http://invisible-island.net/xterm/xterm.faq.html#xterm_tite for some background on what they mean.

If you're in Windows, then you need to remember the current screen buffer and console input, restore the original screen buffer and console input that asciimatics stored away on start-up, and reset them as needed afterwards.  

These latter 2 options use varying amounts of the internals of asciimatics, though, which will likely break in the future.

The other option that springs to mind is to prevent the need for dropping out at all.  You could instead pipe stdout to your asciimatics app, save it off in a widget and then display that instead.

**Comment by ColinWaddell** [comment]
That was a quick reply, thanks!

I've got a mock-up for your latter suggestion, where everything gets thrown at a widget. The problem I'm having though is the version of asciimatics I've pipped is 1.7.2 and doesn't have the force_update signal I've seen you mention in other answers. When the test code was off running and generating data the TUI was sitting static. It was only after everything was complete the widgets updated with the relevant info.

I'm going to have a go of closing the screen and bringing everything back up once complete. I've completely abstracted my data from my view so at least that wont be too messy.

Cant I just double check something before I create too much of a mess:

My application is started as follows:

    def start_app():
        # Build the test runner app
        devices = DeviceModel()
        last_scene = None

        while True:
            try:
                Screen.wrapper(testrunner, 
                               catch_interrupt=True, 
                               arguments=[last_scene, devices])
                sys.exit(0)
            except ResizeScreenError as e:
                last_scene = e.scene

I'm closing my screen and getting to the console by using ````self._screen.close()````

Where self._screen is created during the instantiation of my Frame

Now, once I've executed my code at console and I want to return to the application running ````start_app()```` from anywhere works, but I'm worried this is leaving two copies of the Screen running somewhere. I hope this make sense. I unfortunately cannot post the full app here as it's for work.

**Comment by peterbrittain** [comment]
Yeah - that's a good concern.  You can't do this inside the widget as you will have conflicting Screen instances.  Instead you need to drop out to tat start_app main loop to handle it.

On the other hand, if you've already got working code that just needs the force_update patch, you could build a new distribution from the current code. Simply clone the current master branch and run `python setup.py sdist` from the respository root directory to get your own personal source distribution.

**Comment by ColinWaddell** [comment]
Magic. I'll have at both options tomorrow when I'm back behind the desk.

Although uglier I think dropping in and out of console will be the best
method as it means my test code with be agnostic to the platform running it.

Although having everything piped in and out of the TUI will look
significantly cooler.

Thanks again for your time, it was much appreciated.

On 31 Jan 2017 5:22 p.m., "peterbrittain" <notifications@github.com> wrote:

Yeah - that's a good concern. You can't do this inside the widget as you
will have conflicting Screen instances. Instead you need to drop out to tat
start_app main loop to handle it.

On the other hand, if you've already got working code that just needs the
force_update patch, you could build a new distribution from the current
code. Simply clone the current master branch and run python setup.py sdist
from the respository root directory to get your own personal source
distribution.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/peterbrittain/asciimatics/issues/62#issuecomment-276430427>,
or mute the thread

**Comment by peterbrittain** [comment]
Good stuff.  I'll close this issue now.  Feel free to re-post here, though...

**Comment by ColinWaddell** [comment]
Just a little update in case anyone else is looking for a similar answer.

My code to exit to console belongs in a Frame which looks like:

    class TestRunnerView(Frame):
        def __init__(self, screen, model):
            super(TestRunnerView, self).__init__(
                                            screen,
                                            screen.height * 4 // 5,
                                            screen.width * 4 // 5,
                                            hover_focus=True,
                                            has_shadow = True,
                                            title="Running Test Scheme")

            # Setup the screen
            self._model = model
            self._screen = screen
            self.fix()

        def reset(self):
            # Do standard reset to clear out form, then populate with new data.
            super(TestRunnerView, self).reset()
            self._start()

        def _start(self):
            dut = self._model.get_current_device();
            self._screen.close()
            print("Starting...")
            self.runTestSchemeFromPartNumber(dut["serial_number"])
            raise(RestartApp("Finished running tests... Restarting application"))
            
Where ```RestartApp``` is a custom exception:

    class RestartApp(Exception):
        pass


This is caught by the app runner which builds the application:

    def start_app():
        devices = DeviceModel()
        last_scene = None

        while True:
            try:
                Screen.wrapper(testrunner, 
                               catch_interrupt=True, 
                               arguments=[last_scene, devices])
                sys.exit(0)
            except ResizeScreenError as e:
                last_scene = e.scene
            except RestartApp as r:
                print(r)

I could make an exception like the ResizeScreenError which passes which Scene to jump into but for now I'm quite happy with the app returning to its starting point.

Cheers again for your help @peterbrittain :trophy:
