### ISSUE TITLE
Install fails unless you manually install libjpeg-dev or downgrade pillow to 2.9.0

### ISSUE THREAD

**Issue by randomInteger** [peterbrittain/asciimatics#64]
Clean Ubuntu 14.04LTS after sudo apt-get update/upgrade, python3.4-dev installed.

Attempting to install in a basic python3.4 virtualenv produces a pillow compilation error:

ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting

----------------------------------------
Cleaning up...
Command /home/cgleeson/src/asciimatics/.env/bin/python3 -c "import setuptools, tokenize;__file__='/home/cgleeson/src/asciimatics/.env/build/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1_7_ij_c-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/cgleeson/src/asciimatics/.env/include/site/python3.4 failed with error code 1 in /home/cgleeson/src/asciimatics/.env/build/Pillow
Storing debug log for failure in /home/cgleeson/.pip/pip.log

More info here:  http://stackoverflow.com/questions/24646305/error-for-pip-install-pillow-on-ubuntu-virtualenv

You should consider one of the following:

1.  Add a note that users will need to install libjpeg-dev manually, and list the version needed.

2.  Downgrade the Pillow version to 2.9.0.  This appears to cause no breakages that I was able to find on a quick check of the tool (i.e. hello world example is solid).  Starting with Pillow 3.X you need libjpeg on the host system.

This is my pip freeze from a working install with Pillow 2.9.0:
$ pip freeze
Pillow==2.9.0
asciimatics==1.7.2
future==0.16.0
mock==2.0.0
pyfiglet==0.7.5
setuptools-scm==1.15.0

**Comment by peterbrittain** [comment]
Thanks for taking the time to explain the trouble you had with the install.  I've now updated the troubleshooting guide to include the salient points.

**Comment by randomInteger** [comment]
No problem, this is a fun tool!

**Comment by peterbrittain** [comment]
Thanks!  The whole starting point of this project was for it to make terminals a bit more fun and less of a chore...  It's great to know that this is working.

**Comment by randomInteger** [comment]
It may amuse you to know that I have your tool running on a central server, with the text "LOCK YOUR WORKSTATION" and when a teammate walks away from their desk without locking their machine, I fire up a terminal window and run that process lol.

**Comment by peterbrittain** [comment]
Nice!  All you need now is a little animation of all their files burning while they're gone...  ;-)
