### ISSUE TITLE
rendering to console produces no color

### ISSUE THREAD

**Issue by devinnasar** [peterbrittain/asciimatics#66]
Hello,

When I run asciimatics/samples/renderers.py, the bar charts do not produce color, however when I run any other asciimatics samples they all produce color. bars.py for example does use effects.Print, but that seems to require a screen object. Is there any way to get color output when I just want to render to the console? I'm trying to create an asciimatics based layout that doesn't interrupt the normal console.

Thanks!

**Comment by peterbrittain** [comment]
Yeah - I'm afraid that's all that is currently supported.  Sounds like what you're looking for is https://github.com/peterbrittain/asciimatics/issues/46

**Comment by peterbrittain** [comment]
Closing as duplicate
