### ISSUE TITLE
Cannot display any Chinese characters on the Widgets

### ISSUE THREAD

**Issue by nilliu** [peterbrittain/asciimatics#67]
Chinese characters cannot display correctly,
no exceptions or errors, 
just display nothing for those characters.
code like this
```
    def _quit(self):
        self._scene.add_effect(
            PopUpDialog(self._screen,
                        u"你確定嗎？",
                        [u"是", u"否"],
                        on_close=self._quit_on_yes))
```
<img width="135" alt="jietu20170322-090227 2x" src="https://cloud.githubusercontent.com/assets/16020149/24177565/5645ba74-0ede-11e7-9da7-177cd5e45df5.png">

**Comment by TiberiumPY** [comment]
Maybe it's Python 2 only issue?

**Comment by peterbrittain** [comment]
Shouldn't be Python 2 issue.  Can you please clarify what system you're using, @nilliu?  Please include OS, Python version and what font you're using for your terminal.

**Comment by TiberiumPY** [comment]
@peterbrittain in Python 3 you don't need to specify 'u' prefix for strings, so this code is probably made for Python 2?

**Comment by peterbrittain** [comment]
Fair point.  My guess is that this is actually a font issue as I can quite happily display other unicode characters in my Python 2 setup.

**Comment by peterbrittain** [comment]
OK - I've had a play around on my Python 2, CentOS system and I can see the Chinese characters.  This is almost certainly an environment issue.

That said, it looks like there's still something hiding in here.  Some Asian character sets are not monospaced, even in monospace fonts!  See http://denisbider.blogspot.co.uk/2015/09/when-monospace-fonts-arent-unicode.html  This means the dual-width characters will render incorrectly- either causing wrong padding or partial printing of the text.

That's just going to be a complete pain to resolve.  I'll track that here for now until I know more about nilliu's system.

**Comment by nilliu** [comment]
Hi guys, sorry for late response, somehow I probably turn off the notification in accidentally. 
@TiberiumPY was correct! I use Python 2.
My env is 
```
Python 2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
macOS Sierra
Version 10.12.3 (16D32)
```
and I ran the code under the built-in `Terminal` program.
```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
TERM_PROGRAM=Apple_Terminal
TERM=xterm-256color
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.XEYyzEwLLG/Render
TERM_PROGRAM_VERSION=388
LC_CTYPE=UTF-8
```
locale setting should be correct since I can use same python env to output Chinese characters via some package like `colorama`.

Thank you.

**Comment by peterbrittain** [comment]
Unfortunately, I don't have access to a Mac, so this is going to be tricky...  As I've already flagged in the issue, it looks like we have some widget issues due to double width glyphs.  Let's try putting that to one side and use the basic I/O instead.

What happens when you try using `print_at` to print the Chinese text instead?  And what colorama code are you using that works?

**Comment by peterbrittain** [comment]
OK, so this looks like Terminal may be a little fussier on when it actually outputs double width glyphs.  Can you please confirm which version of asciimatics you're using?

**Comment by nilliu** [comment]
``` sh
$ pip show asciimatics
Name: asciimatics
Version: 1.7.2
Summary: A cross-platform package to replace curses (mouse/keyboard input & text colours/positioning) and create ASCII animations
Home-page: https://github.com/peterbrittain/asciimatics.git
Author: Peter Brittain
Author-email: peter.brittain.os@gmail.com
License: Apache 2.0
Location: /Library/Python/2.7/site-packages
Requires: future, pyfiglet, Pillow
```

**Comment by nilliu** [comment]
colorama test...
``` python
from colorama import Fore, Back, Style
print(Fore.RED + 'some red text 一些紅色字')
print(Back.GREEN + 'green text 綠字')
print(Style.DIM + 'and in dim text 測試'+Style.RESET_ALL)
print('back to normal now 辛苦了')
```

<img width="438" alt="chinese_test3" src="https://cloud.githubusercontent.com/assets/16020149/24216437/341d919e-0f77-11e7-8730-ca92c41dec4c.png">

**Comment by peterbrittain** [comment]
Thanks.  I think I have what I need now.  1.7.2 was always moving the cursor for every character and so overprints any double-width glyphs.  From what I've seen, I think `Terminal` deletes any half glyphs which is what will happen on all widgets because of the bug I'd already found.

It will take a while to fix this properly.  In the meantime, if you install the latest copy on `master` you should see the characters, but they will deform widgets and look horrible when entered into text fields.  Might be a little more helpful than 1.7.2 if you need to do something right now.

**Comment by peterbrittain** [comment]
I've had a little time to explore the bug and think I've resolved a fair chunk of the problems.  The resulting code is in this patch: https://github.com/peterbrittain/asciimatics/commit/2455ba31d201c5f9b7508fcd76889eea54c89e15.  Does this solve your issue?

This adds a new dependency on wcwidth - which I've yet to add to the package list, so you'll need to pip install it before trying it out.

**Comment by nilliu** [comment]
wow, so quick! I'll test it as soon as possible once I got chance 😃

**Comment by nilliu** [comment]
Works like a charm!!! 😍

THANK YOU!

![jietu20170326-092207](https://cloud.githubusercontent.com/assets/16020149/24327519/e43d7176-1205-11e7-836c-1dadc95a4a62.png)

**Comment by nilliu** [comment]
by the way,
I use following commands to apply your patch,
I'm not sure it the correct way or not, 
but seems work perfectly.

``` sh
$ git clone https://github.com/peterbrittain/asciimatics.git
$ cd asciimatics/
$ git fetch origin 2455ba31d201c5f9b7508fcd76889eea54c89e15:refs/remotes/origin/D-commit
$ sudo python setup.py install
```

FYI. ✌️

**Comment by peterbrittain** [comment]
Excellent!  I'll  just tidy up the last rough edges, write some tests and close this issue out.

**Comment by peterbrittain** [comment]
OK - I think the latest updates mean I've resolved the last of the functional issues.  Now closing.
