### ISSUE TITLE
Reset signals after Screen wrapper/close

### ISSUE THREAD

**Issue by brycepg** [peterbrittain/asciimatics#70]
Hi Peter,

I've been using asciimatics for a while now (thank you), and I've finally tracked down a bug involving terminal resize AFTER asciimatics is no longer being used. It looks like a signal handler for terminal resize is set, which disables and re-enables curses, however this signal handler continues to persist for the duration of the python process, causing curses to be enabled and scrambling text whenever the terminal is resized, even after asciimatics wrapper has closed and called `endwin` is called for curses.

The line in question is:

`asciimatics/screen.py:1861`:

            signal.signal(signal.SIGWINCH, self._resize_handler)

Perhaps something like `signal.signal(signal.SIGWINCH, signal.SIG_DFL)` could be in `_CursesScreen.close` for when restore is `True`.

I think I may be using asciimatics differently than everyone else (wrapper doesn't last for the entirety of the python process), but perhaps my use-case is valid.

Let me know what you think,

Bryce

**Comment by peterbrittain** [comment]
Sounds like a good plan to tidy that up properly to me!  Thanks for taking the time to fix up the code.  

I've had a quick look and have requested a couple of changes to try to catch all the ways the signal handling could go wrong.

**Comment by peterbrittain** [comment]
All done!  Thanks for the fix.
