### ISSUE TITLE
setting widget.value in Frame.__init__ gets overwritten by update_widget()

### ISSUE THREAD

**Issue by Jzege** [peterbrittain/asciimatics#72]
(I'm new to this so bear with me)

I want to set a default value for a Text widget without passing in a data dict.

So I do something like
```
self._widget = Text("", name="a_widget")
self._widget.value = "Default value" 
layout.add_widget(self._widget)
```
, which unfortunately does not work. Value is blank when I run the script.

Looking through widgets.py , I find this portion:

```
def update_widgets(self):
        """
        Reset the values for any Widgets in this Layout based on the current
        Frame data store.
        """
        for column in self._columns:
            for widget in column:
                if widget.name in self._frame.data:
                    widget.value = self._frame.data[widget.name]
                elif widget.is_tab_stop:
                    widget.value = None # changing this to widget.value = widget.value lets me set a default value
```

Is there a reason why widget.value is reset to None? What is the expected way to set a default value for widgets? Can value be added to widget.\_\_init\_\_?

**Comment by peterbrittain** [comment]
That logic in `update_widgets` is there to maintain state across screen resizing.  It might be that it's being overly cautious and we can remove that reset for widgets with no data, but it will need testing.  First check - does this break any of the existing tests?

**Comment by peterbrittain** [comment]
Ok.  I tried that and it broke a load of tests because all widget values need to be initialised.  I could fix the Exceptions, but that still leaves two issues:
1. There is no guarantee that all widgets are initialized on start-up.
2. The "default value" you set will overwrite any current values on screen resizing.
Net is that I don't think this is something that should go into the package.  I might be able to provide a better API if you can tell me why the data dict is unsuitable.  Closing for now until I have that use case.

**Comment by Jzege** [comment]
Actually I had changed my original comment of deleting that elif case to setting `widget.value = widget.value`, which does pass the unit tests.

1. Doing this (I think) uses a widget's respective @value.setter and ensures that it is properly initialized (though it is pretty unintuitive at first glance)
2. Yes, the onus is on me to update the "default value" before a resize.

I find it tedious to require labels for all widgets if I use the plain data dict. What I have is tabular, editable data stored as nested OrderedDict, which I then use to create rows of widgets during init. At the same time, I link the respective 'value' with widget.value.

For example:
```
config= OrderedDict([
        ('Label for the table', [
            OrderedDict([
                ('Column 1', {'value': 'row name', 'rw': 'r'}),
                ('Column 2', {'value': 0, 'rw': 'rw'}),
            ])
        ]),
		...
    ])

```

**Comment by peterbrittain** [comment]
OK - I'm convinced.  I've updated the code - as you can see above.
