### ISSUE TITLE
cant get screen.paint() to render something

### ISSUE THREAD

**Issue by kaosbeat** [peterbrittain/asciimatics#74]
Hi,

according to the docs http://asciimatics.readthedocs.io/en/stable/rendering.html#rendering
I should be able to render a figlet using

>  # Pre-render ASCIIMATICS using the big Figlet font
>  `renderer = FigletText("ASCIIMATICS", font='big')`

and then calling "paint"

like 

`screen.paint(renderer, 0, 0)`

this however does not work, I can not find this in the docs so I can only use a Scene to render a figlettext?

Thanks

**Comment by peterbrittain** [comment]
It's hard to tell the problem without a complete minimal program to show what's wrong, but my guess is that you're not calling `Screen.refresh()`.

**Comment by peterbrittain** [comment]
See https://asciimatics.readthedocs.io/en/stable/io.html

**Comment by kaosbeat** [comment]
That's the docs I'm following. I'll try to isolate the code down  to my problem so I can post it here...
Thanks!

**Comment by kaosbeat** [comment]
So I was hoping this would work, but I'm being naive I guess. I read more often you need to wrap it in an Effect, so currently exploring this.

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from asciimatics.screen import Screen
from asciimatics.renderers import FigletText

def demo(screen):
	renderer = FigletText("ASCIIMATICS", font='big')
	screen.paint(renderer, 10 , 10)
	screen.refresh()

Screen.wrapper(demo)
```

**Comment by peterbrittain** [comment]
Ok - I see the issue now.  You can't just pass the renderer straight in to paint.  You need something like this.

            image, colours = self._renderer.rendered_text
            for (i, line) in enumerate(image):
                self._screen.paint(line, self._x, self._y + i, self._colour,
                                   attr=self._attr,
                                   bg=self._bg,
                                   transparent=self._transparent,
                                   colour_map=colours[i])

This is taken from the Print class, so you'll need to fix up the use of object member variables.

**Comment by peterbrittain** [comment]
I'm assuming that this has fixed your problem.  Now closing.
