### ISSUE TITLE
Label widget text wrapping

### ISSUE THREAD

**Issue by innovate-invent** [peterbrittain/asciimatics#79]
An option should be added to wrap the text in a label to the frame.
I currently have to chop the string into several labels based on the frame width.
This seems like a bad way to do things.

Thanks

**Comment by peterbrittain** [comment]
Label text already wraps to the available number of lines for the widget.  I'm guessing you have this issue because you're using a widget that is only one line high.  If so, have you tried changing the height of you widget to something bigger?

**Comment by innovate-invent** [comment]
It isn't clear how to set the height of a Label widget.
I would also have expected this to be calculated dynamically by its containing frame or layout.

**Comment by peterbrittain** [comment]
The height is defined by the `required_height` property for the widget.  The Layout tries to fit the text within that height.  If there is space, it will wrap across lines.  If not, it truncates.  If you want to do something more bespoke with a Widget, see http://asciimatics.readthedocs.io/en/latest/widgets.html#custom-widgets.
But it sounds like you're trying to create multi-line static text...  If so, you should read http://asciimatics.readthedocs.io/en/latest/widgets.html#disabling-widgets.

**Comment by peterbrittain** [comment]
Next release, I'll look at exposing a new attribute to allow Labels to be more than one line.

**Comment by peterbrittain** [comment]
Done in latest build.
