### ISSUE TITLE
Error in _WindowsScreen._clear

### ISSUE THREAD

**Issue by rakiru** [peterbrittain/asciimatics#8]
Running the example given in the readme gives the following traceback:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Python27\lib\site-packages\asciimatics\screen.py", line 393, in wrapper
        func(win_screen)
      File "<stdin>", line 13, in demo
      File "C:\Python27\lib\site-packages\asciimatics\screen.py", line 560, in play
        self.clear()
      File "C:\Python27\lib\site-packages\asciimatics\screen.py", line 740, in clear
        self._clear()
      File "C:\Python27\lib\site-packages\asciimatics\screen.py", line 988, in _clear
        " ", box_size, win32console.PyCOORDType(0, 0))
    ValueError: Object must be a single unicode character

My setup:
 * Windows 7 x64
 * Python 2.7.8 x64 (same on x86 version)
 * asciimatics 1.2.0 (current PyPI release)

I had a quick look at the `FillConsoleOutputCharacter` docs, but couldn't figure out what it wanted.

**Comment by peterbrittain** [comment]
That;s surprising.  The docs are here: http://docs.activestate.com/activepython/2.7/pywin32/PyConsoleScreenBuffer__FillConsoleOutputCharacter_meth.html and a native example is here: https://msdn.microsoft.com/en-us/library/windows/desktop/ms682022%28v=vs.85%29.aspx

It's clearly the first parameter that's at fault.  I've previously tested that running on Python3.4, so I know the pywin32 bindings are good.  I suspect that this is therefore a difference between Python2 and Python3...  Aha - Python2 uses ASCII by default!  Does changing the " " to u' ' fix it?

**Comment by peterbrittain** [comment]
Yup - I've just installed 2.7 on my Windows box, hit the same error and fixed it with the above change.  Will be available in V1.3.0.

**Comment by rakiru** [comment]
I tried `u" "` to no avail. Perhaps I changed the wrong instance of the file... Woops. Thanks, and sorry.
