### ISSUE TITLE
Documentation for setting custom colours and attributes widget text 

### ISSUE THREAD

**Issue by innovate-invent** [peterbrittain/asciimatics#80]
Label widgets need an option for text attributes like bold or underline

**Comment by innovate-invent** [comment]
After digging into the code it looks like the custom_colour attribute needs to be documented better

**Comment by peterbrittain** [comment]
This is already documented in http://asciimatics.readthedocs.io/en/latest/widgets.html#custom-widget-colours.  What else would you like to see to explain this better?

**Comment by innovate-invent** [comment]
A link from the API documentation to the one you provided would help organize the information.
As a whole, links from the API reference to the relevant tutorial section would assist greatly when trying to understand how to use this library.
More explicit documentation of the fields in the tuple that needs to be assigned is needed too.

**Comment by peterbrittain** [comment]
Generally speaking, I'd hope people start with the docs when they don't understand how to use something, so I haven't peppered the whole code with reverse references.  I have now, however, provided some pointers for each module (and docs for colour tuples).
