### ISSUE TITLE
Text widgets are not clickable

### ISSUE THREAD

**Issue by innovate-invent** [peterbrittain/asciimatics#81]
Text widgets are not clickable to give focus across layouts unless tabbed to first.
Once a field receives focus once it is then clickable with focus in a different layout.

**Comment by peterbrittain** [comment]
Sounds like a bug in Layouts that was recently fixed in master.  Can you reproduce this on the latest build?

**Comment by peterbrittain** [comment]
Given no further response I'm assuming this was a duplicate.
