### ISSUE TITLE
Screen corrupts when entering character 127 into a text box

### ISSUE THREAD

**Issue by innovate-invent** [peterbrittain/asciimatics#82]
There is corruption of the screen and field data when a terminal transmits ASCII code 127 rather than 8 as a backspace with focus in a text widget.

**Comment by peterbrittain** [comment]
I can't reproduce this.  My terminal is using 127 as backspace and so reports it is translated correctly and I never see the corruption.  Can you please give me more details of how to reproduce this?

**Comment by peterbrittain** [comment]
Can't repro and no further details, so closing as invalid.
