### ISSUE TITLE
How to set background color of a screen object

### ISSUE THREAD

**Issue by BasLangenberg** [peterbrittain/asciimatics#84]
Ok, so I might be overlooking this, but I am not able to find it in the documentation nor by reviewing the source code.

I am trying to create a simple menu with a bunch of options which I will then select using it's corresponding number. That will be captured by the keyboard. At the moment I try to set a fixed color for the background. (black) 

For this I do not feel I need scenes, but it seems like I am not able to manipulate the screen object directly. When using examples I get the behavior I want, but I just don't need animation or sequenced output on the terminal window.

Example:
```
# Doesn’t work, Color stays like the terminal emulator in configured
# This is in the style I would like to solve this problem, but I need some way to set the background of the complete screen
def demo(screen):
  while True:

    date = time.strftime("%d/%m/%Y %H:%M:%S")
    screen.print_at('Test menu', 0, 0)
    screen.print_at(date, screen.width-len(date), 0)
    screen.print_at('1) Some test menu entry', 3, 2)
    screen.print_at('2) Another test menu entry', 3, 3)
    # Look and feel
    # input
    # do something with select
    screen._change_colours(7, 0, 0)
    screen.refresh()

while True:
  try:
    Screen.wrapper(demo)
    sys.exit()
  except ResizeScreenError:
    pass

# Works, but I am not able to use print_at which is convenient, I also do not know why this makes the background black
# Also for some reason the images text is displayed in some kind of ticker way
# This feels too complicated for my use case
# Stolen from Christmas example, :-)
def demo(screen):
  while True:
    scenes = []
    date = time.strftime("%d/%m/%Y %H:%M:%S"),

    effects = [
    Print(screen, StaticRenderer(images=r'''This is a test'''),
      x=screen.width - 15,
      y=screen.height - 15,
      colour=Screen.COLOUR_GREEN),
    ]

    scenes.append(Scene(effects))

    screen.play(scenes)

while True:
  try:
    Screen.wrapper(demo)
    sys.exit()
  except ResizeScreenError:
    pass
```

In the last case, with the effect array, I also have problems just putting a string on the screen without resorting to some kind of predefined object. (Like the text box or regular box)

What I am looking for is being able to control the screen object in it's appearance, with the simplicity of the first example.

Thanks.

**Comment by peterbrittain** [comment]
I think the issue is that you need to call `screen.clear()` before you start printing anything.  For example, this works for me:

    def demo(screen):
      screen.clear()
      while True:
        date = time.strftime("%d/%m/%Y %H:%M:%S")
        screen.print_at('Test menu', 0, 0)
        screen.print_at(date, screen.width-len(date), 0)
        screen.print_at('1) Some test menu entry', 3, 2)
        screen.print_at('2) Another test menu entry', 3, 3)
        ev = screen.get_key()
        if ev in (ord('Q'), ord('q')):
            return
        screen.refresh()

    while True:
      try:
        Screen.wrapper(demo)
        sys.exit()
      except ResizeScreenError:
        pass

Looks like I haven't mentioned it before.  I'll update the docs to cover it.

**Comment by BasLangenberg** [comment]
Thank you, sir!

This solved my issue. I cannot think of why I couldn't figure this out myself, but at least it will get documented.
