### ISSUE TITLE
Frame data property empty after user input

### ISSUE THREAD

**Issue by Imelstorm** [peterbrittain/asciimatics#94]
Frame.data empty after user input.

Expected behavior: dict with widget name and value

**Comment by Imelstorm** [comment]
Tested only OS X

**Comment by peterbrittain** [comment]
It's pretty hard to tell what the issue is here without sample code, but I'm going to guess anyway...  Do you call the `save()` method on your Frame before trying to access `data`?

**Comment by Imelstorm** [comment]
Your are right. I missed it. Sorry.
