### ISSUE TITLE
on_focus support

### ISSUE THREAD

**Issue by dylanjsa** [peterbrittain/asciimatics#97]
Hi Peter,

Fantastic library! I'm starting to use it for developing UIs I can easily access over SSH. Is there any support for a callback when a widget receives focus?

**Comment by peterbrittain** [comment]
Thanks!  There isn't anything right now, but I don't see why it couldn't be added.

Not sure when I'll get round to that.  In the meantime, you might be able to do something by overriding the call to `focus()` in the Widgets you care about (and then calling on to the original function).

**Comment by dylanjsa** [comment]
Thanks peter, I'll have a look at the contribution guide and try send a pull request.

**Comment by peterbrittain** [comment]
Great!

**Comment by peterbrittain** [comment]
Handled by pull request 99
